// SF50-g: write src/shards/sunscar-dunes/data/edges.ts from the committed WSTR bake: the four native boundary rows
// (north / south run west -> east, east / west run south -> north; east = +x), coloured exactly as the grid's legacy
// reader colours them (src/game/grid/edgeSources.ts: the map palette's ground ramp, sRGB -> linear), so declaring the rows
// in the shardfile changes no seam height or colour.
// Run from the repository root: node --import ./scripts/sim-node-loader.mjs progress/shard-platform/sf50/edges.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { SIGNAL_DUNES_MINIMAP } from '../../../src/shards/sunscar-dunes/look/minimap.ts';

const bytes = readFileSync('public/assets/baked/sunscar-dunes/terrain.bin');
const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
if (view.getUint32(0, true) !== 0x52545357 || view.getFloat32(12, true) !== 500) throw new Error('not a WSTR bake');
const res = view.getUint32(8, true), step = 500 / (res - 1);
const at = (i, j) => view.getFloat32(24 + (Math.max(0, Math.min(res - 1, j)) * res + Math.max(0, Math.min(res - 1, i))) * 4, true);
const linear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const unit = (c) => Math.max(0, Math.min(1, Number.isFinite(c) ? c : 0));
const scratch = [0, 0, 0];
const round = (n, d) => { const k = 10 ** d, r = Math.round(n * k) / k; return Object.is(r, -0) ? 0 : r; };
const rows = {};
for (const side of ['north', 'east', 'south', 'west']) {
  const heights = [], colours = [];
  for (let k = 0; k < res; k++) {
    const i = side === 'east' ? res - 1 : side === 'west' ? 0 : k, j = side === 'north' ? res - 1 : side === 'south' ? 0 : k, h = at(i, j);
    const slope = Math.min(1, Math.hypot(at(i + 1, j) - at(i - 1, j), at(i, j + 1) - at(i, j - 1)) / (2 * step) / 2);
    SIGNAL_DUNES_MINIMAP.ground(-250 + i * step, -250 + j * step, h, slope, 0, scratch);
    const scale = Math.max(...scratch) > 1 ? 255 : 1;
    heights.push(round(h, 3)); colours.push(scratch.map((c) => round(unit(linear(c / scale)), 4)));
  }
  rows[side] = { heights, colours };
}
// the narrowest run of exact road-height samples straddling an edge midpoint (the entry gap the engine's entry roads cut)
const gap = Math.min(...Object.values(rows).map(({ heights }) => {
  let lo = Math.floor((res - 1) / 2), hi = Math.ceil((res - 1) / 2);
  while (lo > 0 && Math.abs(heights[lo - 1]) <= 0.0005) lo--;
  while (hi < res - 1 && Math.abs(heights[hi + 1]) <= 0.0005) hi++;
  return Math.abs(heights[lo]) <= 0.0005 && Math.abs(heights[hi]) <= 0.0005 ? (hi - lo) * step : 0;
}));
const body = Object.entries(rows).map(([side, row]) => `  ${side}: {\n    heights: [${row.heights.join(',')}],\n    colours: [${row.colours.map((c) => `[${c.join(',')}]`).join(',')}],\n  },`).join('\n');
writeFileSync('src/shards/sunscar-dunes/data/edges.ts', `// Generated by progress/shard-platform/sf50/edges.mjs from public/assets/baked/sunscar-dunes/terrain.bin (the committed
// WSTR bake, ${res} samples over 500 m): Signal Dunes' four native boundary rows (north / south run west -> east, east / west run
// south -> north; east = +x), coloured as the grid's legacy reader colours them (the map palette's ground ramp, linear).
// SF50-g declares them so the grid's seams read the real dune field (to ${round(Math.max(...Object.values(rows).flatMap((r) => r.heights)), 1)} m) instead of an all-zero
// substitute; each midpoint is exactly road height across the bake's entry gap (${round(gap, 1)} m of exact zeros, wider than the 8 m opening).
export const SIGNAL_DUNES_EDGES: Record<'north' | 'east' | 'south' | 'west', { heights: readonly number[]; colours: readonly (readonly [number, number, number])[] }> = {
${body}
};
`);
console.log('wrote data/edges.ts', res, 'samples');
