// Generated by drafts/tools/atlas.ts from drafts/public/data/index.json; do not edit.
// The game's COMING SOON cards for the drafts (WORLDCLAW-TOOLS W9, J19, J38): public fields only, the key art on Blob.
export interface DraftTitle {
  readonly slug: string;
  readonly name: string;
  readonly line: string;
  readonly stage: string;
  readonly stageName: string;
  readonly thumb: string;
  readonly hero: string;
  readonly url: string;
}

export const DRAFT_TITLES: readonly DraftTitle[] = [
  {
    slug: "thin-ice",
    name: "Thin Ice",
    line: "The ferry is gone and the fjord has frozen.",
    stage: "P6",
    stageName: "First-person views",
    thumb: "https://64yencbq8tncsy39.public.blob.vercel-storage.com/draft/thin-ice/50ecc454e23ed708-thumb.webp",
    hero: "https://64yencbq8tncsy39.public.blob.vercel-storage.com/draft/thin-ice/50ecc454e23ed708-full.webp",
    url: "https://wildshard-drafts.vercel.app/#/thin-ice",
  },
];
