// oxlint-disable-next-line import/no-nodejs-modules -- Recompile committed author sources and compare every generated byte.
import { readFileSync } from 'node:fs';
// oxlint-disable-next-line import/no-nodejs-modules -- Native equality checks the complete compiled byte array.
import { Buffer } from 'node:buffer';
import { expect, it } from 'vitest';
import { compileDirectorSource } from '../scripts/bake/directorSource';

it.each(['driftwood-isle', 'nalati-grasslands', 'pine-hollow'])('reproduces %s director outputs through the retained SDK TypeScript bake', async slug => {
  const root = `src/shards/${slug}`;
  const baked = await compileDirectorSource(readFileSync(`${root}/behaviour/director.as`, 'utf8'));
  expect(Buffer.from(baked.bytes).equals(readFileSync(`${root}/assets/${baked.module}`))).toBe(true);
  if (slug !== 'nalati-grasslands') {
    const embedded: unknown = JSON.parse(readFileSync(`${root}/behaviour/director.json`, 'utf8'));
    expect(embedded).toEqual({
      ...(slug === 'driftwood-isle' ? { generated: 'DO NOT EDIT: behaviour/director.as -> scripts/bake/directorSource.ts (@wildshard/sdk/compileScript); regenerate with node scripts/bake/directors.mjs' } : {}),
      module: baked.module, bytes: Buffer.from(baked.bytes).toString('base64'),
    });
  }
}, 20_000);
