// E357 Z2: docs/ENGINE.md lists every export of the public indexes, and docs/SHARDS.md names the layout AG9 enforces.
// Regenerate the export appendix after an index change:
//   ENGINE_DOC_WRITE=1 pnpm exec vitest run test/engine-docs.test.ts
// oxlint-disable-next-line import/no-nodejs-modules -- The test reads committed docs and index sources.
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
// oxlint-disable-next-line import/no-nodejs-modules -- Repository-relative paths.
import { resolve } from 'node:path';
// oxlint-disable-next-line import/no-nodejs-modules -- The opt-in rewrite switch for the generated appendix.
import { env } from 'node:process';
import { describe, expect, it } from 'vitest';

const ROOT = resolve(import.meta.dirname, '..');
const ENGINE_DOC = 'docs/ENGINE.md';
const SHARDS_DOC = 'docs/SHARDS.md';
const START = '<!-- exports:start (generated by test/engine-docs.test.ts; do not edit by hand) -->';
const END = '<!-- exports:end -->';
const INDEXES: readonly (readonly [string, string])[] = [
  ['#engine', 'src/engine/index.ts'],
  ['#engine/data', 'src/engine/data.ts'],
  ['#game', 'src/game/index.ts'],
  ['#kit', 'src/kit/index.ts'],
];

const read = (path: string): string => readFileSync(resolve(ROOT, path), 'utf8');

interface IndexExports { alias: string; file: string; groups: Map<string, string[]> }

/** The index files are flat `export { … } from '…'` lists; anything else is refused so nothing escapes the check. */
function indexExports(alias: string, file: string, text: string): IndexExports {
  const code = text.replaceAll(/\/\*[\s\S]*?\*\//gu, '').replaceAll(/\/\/[^\n]*/gu, '');
  const groups = new Map<string, string[]>();
  const add = (from: string, name: string): void => {
    const list = groups.get(from) ?? [];
    if (!list.includes(name)) list.push(name);
    groups.set(from, list);
  };
  let matched = 0;
  for (const m of code.matchAll(/\bexport\s+(?:type\s+)?\{([^}]*)\}\s*from\s*'([^']+)'\s*;?/gu)) {
    matched += 1;
    const from = m[2] ?? '';
    for (const raw of (m[1] ?? '').split(',')) {
      const spec = raw.trim().replace(/^type\s+/u, '');
      if (spec === '') continue;
      const name = /\bas\s+(\w+)$/u.exec(spec)?.[1] ?? spec;
      if (!/^\w+$/u.test(name)) throw new Error(`${file}: cannot read export specifier "${raw.trim()}"`);
      add(from, name);
    }
  }
  for (const m of code.matchAll(/\bexport\s+const\s+(\w+)/gu)) { matched += 1; add('(local)', m[1] ?? ''); }
  const statements = [...code.matchAll(/(?:^|[;\n])\s*export\b/gu)].length;
  if (statements !== matched) throw new Error(`${file}: ${statements - matched} export statement(s) are not a flat \`export { … } from\` or \`export const\`; list them by name`);
  return { alias, file, groups };
}

const allIndexes = (): IndexExports[] => INDEXES.map(([alias, file]) => indexExports(alias, file, read(file)));
const names = (ix: IndexExports): Set<string> => new Set([...ix.groups.values()].flat());

function appendix(indexes: readonly IndexExports[]): string {
  let out = `${START}\n\n`;
  for (const ix of indexes) {
    out += `### \`${ix.alias}\` (\`${ix.file}\`)\n\n${names(ix).size} exports, grouped by the module they come from.\n\n`;
    for (const [from, list] of ix.groups) out += `- \`${from}\`: ${list.map((n) => `\`${n}\``).join(', ')}\n`;
    out += '\n';
  }
  return `${out}${END}`;
}

/** The names a doc's appendix lists under one index heading (module paths and prose excluded). */
function listed(block: string, alias: string): Set<string> {
  const heading = `### \`${alias}\` (`;
  const at = block.indexOf(heading);
  if (at === -1) return new Set();
  const rest = block.slice(at + heading.length);
  const stop = rest.indexOf('\n### ');
  const section = stop === -1 ? rest : rest.slice(0, stop);
  const found = new Set<string>();
  for (const line of section.split('\n')) {
    const item = /^- `[^`]+`: (.*)$/u.exec(line)?.[1];
    if (item === undefined) continue;
    for (const m of item.matchAll(/`(\w+)`/gu)) found.add(m[1] ?? '');
  }
  return found;
}

describe('docs/ENGINE.md (E357 Z2)', () => {
  const indexes = allIndexes();
  if (env['ENGINE_DOC_WRITE'] === '1') {
    const doc = read(ENGINE_DOC);
    const from = doc.indexOf(START), to = doc.indexOf(END);
    if (from === -1 || to === -1) throw new Error(`${ENGINE_DOC}: the export markers are missing`);
    writeFileSync(resolve(ROOT, ENGINE_DOC), doc.slice(0, from) + appendix(indexes) + doc.slice(to + END.length));
  }
  const doc = read(ENGINE_DOC);

  it('has the generated export appendix', () => {
    expect(doc.includes(START) && doc.includes(END)).toBe(true);
  });

  for (const ix of indexes) {
    it(`mentions every export of ${ix.alias} (and no stale name)`, () => {
      const block = doc.slice(doc.indexOf(START), doc.indexOf(END));
      const want = names(ix), have = listed(block, ix.alias);
      const missing = [...want].filter((n) => !have.has(n));
      const stale = [...have].filter((n) => !want.has(n));
      const hint = 'run ENGINE_DOC_WRITE=1 pnpm exec vitest run test/engine-docs.test.ts, then describe any new API in its section';
      expect({ missing, stale, hint: missing.length + stale.length > 0 ? hint : '' }).toEqual({ missing: [], stale: [], hint: '' });
    });
  }

  it('has one section per 01-architecture §', () => {
    const sections = ['0', '1', '2', '3', '4', '5', '5a', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24'];
    const missing = sections.filter((s) => !new RegExp(`^## ${s}\\. `, 'mu').test(doc));
    expect(missing).toEqual([]);
  });
});

describe('docs/SHARDS.md and the shard READMEs (E357 Z2, E362 AG22)', () => {
  const layout = JSON.parse(read('lint/shard-layout.json')) as { requiredFiles: string[]; allowedFiles: string[]; folders: string[] };
  const shards = read(SHARDS_DOC);

  it('names every file and folder the AG9 layout check knows', () => {
    const want = [...layout.requiredFiles, ...layout.allowedFiles, ...layout.folders.map((f) => `${f}/`)];
    expect(want.filter((name) => !shards.includes(`\`${name}\``))).toEqual([]);
  });

  it('every shard folder, the template included, has a README.md', () => {
    const slugs = readdirSync(resolve(ROOT, 'src/shards'), { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name);
    expect(slugs.length).toBeGreaterThanOrEqual(5);
    expect(slugs.filter((slug) => !existsSync(resolve(ROOT, 'src/shards', slug, 'README.md')))).toEqual([]);
  });
});
