// oxlint-disable-next-line import/no-nodejs-modules -- Real commits and child generators run in an isolated fixture repository.
import { execFileSync, spawnSync } from 'node:child_process';
// oxlint-disable-next-line import/no-nodejs-modules -- Own throwaway repositories only.
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
// oxlint-disable-next-line import/no-nodejs-modules -- Canonical temporary fixture paths.
import { tmpdir } from 'node:os';
// oxlint-disable-next-line import/no-nodejs-modules -- Canonical temporary fixture paths.
import { dirname, resolve } from 'node:path';
// oxlint-disable-next-line import/no-nodejs-modules -- Resolve fixture package links from the real checkout.
import { cwd, execPath } from 'node:process';
import { describe, expect, it } from 'vitest';
import { generatedFiles } from '../scripts/generated-files.mjs';
import { writeApiDocs } from '../scripts/gen-api.mjs';
import { checkShardfileReference } from '../scripts/docs/gen-shardfile-reference.mjs';
import { approvedIncreases, checkCommitted, regenerateCommitted, verifiedStamp } from '../scripts/regenerate-committed.mjs';
import { linkNodeModules } from '../scripts/link-node-modules.mjs';
import { precommitGenerated } from '../scripts/precommit-generated.mjs';
import { manifestOutcome, prepareWitnesses, refreshWitnesses, withInputs } from '../scripts/witness-manifests.mjs';
import { cachedWitnessManifest } from '../scripts/witness-checkpoints.mjs';

function fixture(run: (root: string, put: (file: string, value: string) => void, git: (args: string[]) => string) => void | Promise<void>): Promise<void> {
  const root = realpathSync(mkdtempSync(resolve(tmpdir(), 'sf6b-fixture-')));
  const put = (file: string, value: string): void => { mkdirSync(dirname(resolve(root, file)), { recursive: true }); writeFileSync(resolve(root, file), value); };
  const git = (args: string[]): string => execFileSync('git', args, { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }).trim();
  return (async () => {
    try {
      cpSync('lint', resolve(root, 'lint'), { recursive: true });
      for (const file of ['scripts/generated-files.mjs', 'scripts/generated-policy.mjs', 'scripts/precommit-generated.mjs', 'scripts/regenerate-committed.mjs', 'scripts/witness-manifests.mjs', 'scripts/witness-checkpoints.mjs', 'scripts/link-node-modules.mjs', 'scripts/gen-api.mjs', 'scripts/check-graph.mjs', 'scripts/legacy-shards.mjs', 'scripts/guard-counts.mjs', 'scripts/normalize/liveness.mjs', 'scripts/sim-node-loader.mjs', 'scripts/docs/schema-reference.mjs', 'scripts/docs/gen-shardfile-reference.mjs', 'scripts/docs/read-shardfile-reference.mjs', 'scripts/docs/sdk-schemas.mjs']) {
        mkdirSync(dirname(resolve(root, file)), { recursive: true }); cpSync(file, resolve(root, file));
      }
      for (const file of ['.oxlintrc.json', '.oxlintrc.ratchet.json']) cpSync(file, resolve(root, file));
      put('package.json', '{"type":"module"}'); put('tsconfig.json', '{"compilerOptions":{"strict":true,"types":[],"moduleResolution":"bundler","module":"esnext"}}');
      for (const layer of ['engine', 'game', 'sdk', 'commons']) put(`src/${layer}/package.json`, JSON.stringify({ name: `@wildshard/${layer}`, exports: layer === 'engine' ? { './clock': './clock.ts' } : {} }));
      put('src/engine/clock.ts', '/** Authoritative time. */\nexport const tick = 1;\n');
      put('src/engine/level/context.ts', '/** Generic context. */\nexport interface LevelContext {}\n');
      put('src/game/shard/context.ts', '/** Content context. */\nexport interface ShardContext {}\n');
      put('src/game/shardfile/schema.ts', "import * as v from 'valibot';\nexport const ShardfileSchema = v.strictObject({ version: v.literal('0.1') });\n");
      put('src/engine/script/abi.ts', 'export const SCRIPT_IMPORTS = { fuel: [127, 0] };\nexport const SCRIPT_EXPORTS = { on_tick: [] };\nexport const SCRIPT_ABI = { version: 0 };\n');
      put('lint/api-undocumented.json', '{"max":0}'); put('lint/layer-edges.json', '{"edges":{}}');
      put('lint/ratchet.json', '{"allow":{},"budgets":{"gpu":12},"debugRows":{"max":5,"raisedBy":["E435"]}}');
      put('docs/ENGINE.md', '<!-- exports:start (generated by test/engine-docs.test.ts; do not edit by hand) -->\n<!-- exports:end -->\n');
      linkNodeModules(cwd(), root);
      for (const [file, value] of Object.entries(generatedFiles(root).outputs)) put(file, value);
      git(['init', '-q', '-b', 'main']); git(['config', 'user.name', 'SF6b fixture']); git(['config', 'user.email', 'fixture@example.invalid']);
      git(['add', '--', 'src', 'scripts', 'lint', 'docs', 'package.json', 'tsconfig.json', '.oxlintrc.json', '.oxlintrc.ratchet.json']);
      git(['commit', '-qm', 'fixture baseline']);
      git(['commit', '-qm', 'baseline ready', '--allow-empty']);
      await run(root, put, git);
    } finally { rmSync(root, { recursive: true, force: true }); }
  })();
}
describe('SF6b clean committed regeneration', () => {
  it('builds the schema reference from committed sources at build time; the push has nothing to regenerate (SF74 W13)', async () => {
    await fixture(async (root, put, git) => {
      writeApiDocs(root);
      checkShardfileReference(root);
      put('src/game/shardfile/schema.ts', "import * as v from 'valibot';\nexport const ShardfileSchema = v.strictObject({ version: v.literal('0.1'), reward: v.optional(v.pipe(v.number(), v.minValue(0)), 7) });\n");
      git(['commit', '-qm', 'schema source change', '--', 'src/game/shardfile/schema.ts']);
      expect(() => checkShardfileReference(root)).toThrow('Stale generated shardfile reference');
      writeApiDocs(root);
      expect(readFileSync(resolve(root, 'docs/api/SHARDFILE.md'), 'utf8')).toContain('| $.reward | number | optional; default 7 | min_value 0 |');
      checkShardfileReference(root);
      const head = git(['rev-parse', 'HEAD']);
      expect(await regenerateCommitted(root)).toBe(head);
      await expect(checkCommitted(root, head)).resolves.toBeUndefined();
      rmSync(resolve(root, 'docs/api/SHARDFILE.md'));
      expect(() => checkShardfileReference(root)).toThrow('Stale generated shardfile reference');
    });
  }, 30_000);
  it('covers a moving count with a standing rule, and still refuses what no rule or exact row covers (SF74 W14)', () => {
    const down = { kind: 'graph' as const, key: 'shards/alpha → engine', before: 811, after: 816 };
    const up = { kind: 'graph' as const, key: 'engine → game', before: 0, after: 1 };
    const standing = { approver: 'wildshard-new', increases: [], standing: [{ kind: 'graph', key: '^shards/[^ ]+ → (engine|game|sdk|commons)$' }] };
    expect(approvedIncreases(standing, [down, up])).toEqual([down]);
    expect(approvedIncreases({ approver: 'wildshard-new', increases: [{ ...down, after: 813 }] }, [down, up])).toEqual([]);
    expect(approvedIncreases({ approver: 'wildshard-new', increases: [up] }, [down, up])).toEqual([up]);
  });
  it('warns about source-only graph increases but keeps shard reach and cross-layer cycles fatal', async () => {
    await fixture((root, put, git) => {
      put('src/game/clock.ts', "import { tick } from '@wildshard/engine/clock';\nexport const gameTick = tick;\n");
      git(['add', '--', 'src/game/clock.ts']);
      const args = ['scripts/check-graph.mjs', '--source-only', '--paths', 'src/game/clock.ts'];
      const warning = spawnSync(execPath, args, { cwd: root, encoding: 'utf8' });
      expect(warning.status, warning.stderr).toBe(0); expect(warning.stderr).toContain('coordinator approval');
      put('src/engine/clock.ts', "import { gameTick } from '@wildshard/game/clock';\nexport const tick = gameTick;\n"); git(['add', '--', 'src/engine/clock.ts']);
      const cycle = spawnSync(execPath, [...args, 'src/engine/clock.ts'], { cwd: root, encoding: 'utf8' });
      expect(cycle.status).toBe(1); expect(cycle.stderr).toContain('cycle across');
      put('src/shards/alpha/plugin.ts', 'export const run = 1;'); git(['add', '--', 'src/shards/alpha/plugin.ts']);
      put('src/game/clock.ts', "import { run } from '../shards/alpha/plugin';\nexport const gameTick = run;\n"); git(['add', '--', 'src/game/clock.ts']);
      const reach = spawnSync(execPath, args, { cwd: root, encoding: 'utf8' });
      expect(reach.status).toBe(1); expect(reach.stderr).toContain('reaches into');
    });
  });
  it('discovers a newly exported SDK schema and refuses missing fields or ABI calls in the committed reference', async () => {
    await fixture(async (root, put, git) => {
      writeApiDocs(root); // the build output of the commit before the schema change
      put('src/sdk/package.json', JSON.stringify({ name: '@wildshard/sdk', exports: { './worldSource': './worldSource.ts' } }));
      put('src/sdk/worldSource.ts', "import * as v from 'valibot';\n/** Build-only authored world input. */\nexport const WorldSourceSchema = v.strictObject({ glb: v.string(), scale: v.optional(v.number(), 1) });\n");
      put('src/engine/script/abi.ts', 'export const SCRIPT_IMPORTS = { fuel: [127, 0], query: [127, 127, 127, 127] };\nexport const SCRIPT_EXPORTS = { on_tick: [] };\nexport const SCRIPT_ABI = { version: 0 };\n');
      git(['add', '--', 'src/sdk/worldSource.ts']);
      git(['commit', '-qm', 'SDK schema and ABI source', '--', 'src/sdk/package.json', 'src/sdk/worldSource.ts', 'src/engine/script/abi.ts']);
      expect(() => checkShardfileReference(root)).toThrow('Schema documentation coverage');
      writeApiDocs(root);
      const path = resolve(root, 'docs/api/SHARDFILE.md');
      const document = readFileSync(path, 'utf8');
      expect(document).toContain('$sdk["./worldSource"].WorldSourceSchema.scale');
      expect(document).toContain('| import | query | i32, i32, i32 | i32 |');
      checkShardfileReference(root);
      put('docs/api/SHARDFILE.md', document.split('\n').filter(line => !line.startsWith('| $sdk["./worldSource"].WorldSourceSchema.glb |')).join('\n'));
      expect(() => checkShardfileReference(root)).toThrow('fields missing: $sdk["./worldSource"].WorldSourceSchema.glb');
      put('docs/api/SHARDFILE.md', document.split('\n').filter(line => !line.startsWith('| import | query |')).join('\n'));
      expect(() => checkShardfileReference(root)).toThrow('abi missing: import.query');
      put('docs/api/SHARDFILE.md', document);
      await expect(checkCommitted(root, git(['rev-parse', 'HEAD']))).resolves.toBeUndefined();
    });
  }, 30_000);
  it('checks staged generated edits while allowing source-only commits and manual prose or policy edits', async () => {
    await fixture((root, put, git) => {
      const baseline = readFileSync(resolve(root, 'lint/layer-edges.json'), 'utf8');
      // A foreign disk edit does not participate until it is explicitly staged in this fixture.
      put('lint/layer-edges.json', `${baseline}\n`);
      expect(() => precommitGenerated(root)).not.toThrow();
      git(['add', '--', 'lint/layer-edges.json']);
      expect(() => precommitGenerated(root)).toThrow('Builders commit source only');
      put('lint/layer-edges.json', baseline); git(['add', '--', 'lint/layer-edges.json']);
      const doc = readFileSync(resolve(root, 'docs/ENGINE.md'), 'utf8');
      put('docs/ENGINE.md', `Manual API explanation.\n${doc}`);
      git(['add', '--', 'docs/ENGINE.md']);
      expect(() => precommitGenerated(root)).not.toThrow();
    });
  });
  it('joins two export/import source commits within a minute with one regeneration, preserving foreign WIP and policy', async () => {
    await fixture(async (root, put, git) => {
      const start = Date.now();
      put('src/engine/clock.ts', '/** Authoritative time. */\nexport const tick = 1;\n/** Paused time. */\nexport const paused = 0;\n');
      git(['commit', '-qm', 'builder one export', '--', 'src/engine/clock.ts']);
      const approval = resolve(root, 'approved.json');
      writeFileSync(approval, JSON.stringify({ approver: 'wildshard-new', increases: [{ kind: 'graph', key: 'game → engine', before: 0, after: 1 }] }));
      // The second builder lands while the pusher is computing the first committed export.
      const pending = regenerateCommitted(root, approval);
      put('src/game/clock.ts', "import { tick } from '@wildshard/engine/clock';\n/** Shared clock. */\nexport const gameTick = tick;\n");
      git(['add', '--', 'src/game/clock.ts']); git(['commit', '-qm', 'builder two import', '--', 'src/game/clock.ts']);
      const source = git(['rev-parse', 'HEAD']);
      expect(Date.now() - start).toBeLessThan(60_000);
      const policy = JSON.parse(readFileSync(resolve(root, 'lint/ratchet.json'), 'utf8')) as unknown;
      // Independent working edits must not enter the clean export or be overwritten by its private-index landing.
      put('src/engine/clock.ts', '/** Foreign WIP. */\nexport const unpublished = 9;\n');
      put('lint/layer-edges.json', '{"edges":{"foreign":99}}');
      put('docs/NOTES.md', 'Independent staged note.\n'); git(['add', '--', 'docs/NOTES.md']);
      const sha = await pending;
      expect(git(['rev-list', '--count', `${source}..HEAD`])).toBe('1');
      expect(git(['show', '-s', '--format=%B', sha])).toContain(`Generated-Source: ${source}`);
      // The push gate skips its duplicate check only for a commit this regeneration built and stamped.
      expect(readFileSync(verifiedStamp(root, sha), 'utf8')).toBe(`${source}\n`);
      expect(existsSync(verifiedStamp(root, source))).toBe(false);
      expect(git(['show', `${sha}:lint/layer-edges.json`])).toContain('game → engine');
      expect(git(['show', `${sha}:lint/layer-edges.json`])).not.toContain('foreign');
      expect(git(['show', `${sha}:src/engine/clock.ts`])).toContain('paused');
      expect(readFileSync(resolve(root, 'src/engine/clock.ts'), 'utf8')).toContain('unpublished');
      expect(readFileSync(resolve(root, 'lint/layer-edges.json'), 'utf8')).toContain('foreign');
      expect(git(['diff', '--cached', '--name-only'])).toBe('docs/NOTES.md');
      expect(git(['show', ':docs/NOTES.md'])).toBe('Independent staged note.');
      expect(readFileSync(resolve(root, 'docs/NOTES.md'), 'utf8')).toBe('Independent staged note.\n');
      expect(JSON.parse(git(['show', `${sha}:lint/ratchet.json`]))).toEqual(policy);
      await expect(checkCommitted(root, sha)).resolves.toBeUndefined();
      expect(await regenerateCommitted(root)).toBe(sha);
    });
  }, 30_000);
  it('rejects stale docs, measured increases without approval and hand-edited counts without touching HEAD', async () => {
    await fixture(async (root, put, git) => {
      const baseline = git(['rev-parse', 'HEAD']);
      await expect(checkCommitted(root, baseline)).resolves.toBeUndefined();
      put('src/game/clock.ts', "import { tick } from '@wildshard/engine/clock';\n/** Shared clock. */\nexport const gameTick = tick;\n");
      git(['add', '--', 'src/game/clock.ts']); git(['commit', '-qm', 'unapproved source edge', '--', 'src/game/clock.ts']);
      const source = git(['rev-parse', 'HEAD']);
      await expect(regenerateCommitted(root)).rejects.toThrow('Coordinator approval required');
      expect(git(['rev-parse', 'HEAD'])).toBe(source);
      await expect(checkCommitted(root, source)).rejects.toThrow('Stale or hand-edited');
      put('lint/layer-edges.json', '{"edges":{"game → engine":99}}');
      git(['commit', '-qm', 'hand edited measurement', '--', 'lint/layer-edges.json']);
      await expect(checkCommitted(root, git(['rev-parse', 'HEAD']))).rejects.toThrow('serialized regeneration');
    });
  }, 30_000);
});

// A stand-in witness: inputs.txt plays the loaded-module hash, payload.txt and ticks.txt the recorded behaviour.
const FAKE_WITNESS = `import { appendFileSync, readFileSync, writeFileSync } from 'node:fs';
const at = (file) => new URL(file, import.meta.url), read = (file) => readFileSync(at(file), 'utf8').trim();
const inputs = read('inputs.txt'), manifest = JSON.parse(read('checkpoints/manifest.json'));
if (process.argv[2] === 'fresh') { console.info(JSON.stringify({ status: manifest.inputs === inputs ? 'fresh' : 'stale', inputs, recorded: manifest.inputs })); process.exitCode = manifest.inputs === inputs ? 0 : 1; }
else if (process.argv[2] === 'checkpoints') {
  appendFileSync(at('recordings.log'), 'x');
  writeFileSync(at('checkpoints/a.snap.gz'), read('payload.txt'));
  writeFileSync(at('checkpoints/manifest.json'), JSON.stringify({ inputs, ticks: Number(read('ticks.txt')) }, null, 2) + '\\n');
} else throw new Error('mode');
`;
const fakeManifest = (inputs: string, ticks = 7): string => `${JSON.stringify({ inputs, ticks }, null, 2)}\n`;
function fakeWitness(put: (file: string, value: string) => void, inputs = 'aa'): void {
  put('test/proof/fake/run.mjs', FAKE_WITNESS); put('test/proof/fake/inputs.txt', inputs); put('test/proof/fake/payload.txt', 'p1'); put('test/proof/fake/ticks.txt', '7');
  put('test/proof/fake/checkpoints/a.snap.gz', 'p1'); put('test/proof/fake/checkpoints/manifest.json', fakeManifest(inputs));
}
describe('SF6b witness manifests re-recorded at the serialized push', () => {
  it('refreshes a cached witness through its small manifest without writing committed payloads', async () => {
    const root = realpathSync(mkdtempSync(resolve(tmpdir(), 'cached-witness-fixture-')));
    const put = (file: string, value: string): void => { mkdirSync(dirname(resolve(root, file)), { recursive: true }); writeFileSync(resolve(root, file), value); };
    try {
      put('scripts/sim-node-loader.mjs', ''); fakeWitness(put);
      const directory = resolve(root, 'test/proof/fake/checkpoints');
      const committed = cachedWitnessManifest(directory);
      put('test/proof/fake/checkpoints/manifest.json', committed);
      // Simulate the later payload-removal phase: the recorder returns cached metadata; the push never writes a gzip.
      rmSync(resolve(directory, 'a.snap.gz'));
      put('test/proof/fake/run.mjs', `import { readFileSync } from 'node:fs';
const read = file => readFileSync(new URL(file, import.meta.url), 'utf8').trim();
const inputs = read('inputs.txt'), manifest = JSON.parse(read('checkpoints/manifest.json'));
if (process.argv[2] === 'fresh') { console.info(JSON.stringify({ status: manifest.inputs === inputs ? 'fresh' : 'stale', inputs, recorded: manifest.inputs })); process.exitCode = manifest.inputs === inputs ? 0 : 1; }
else if (['cache-record', 'cache-verify'].includes(process.argv[2])) {
  manifest.inputs = inputs; manifest.ticks = Number(read('ticks.txt'));
  console.info(JSON.stringify({ manifest: JSON.stringify(manifest, null, 2) + '\\n' }));
} else throw new Error('mode');
`);
      put('test/proof/fake/inputs.txt', 'bb');
      await expect(refreshWitnesses(root, resolve(root, 'receipts'))).resolves.toEqual({ 'test/proof/fake/checkpoints/manifest.json': withInputs(committed, 'bb') });
      expect(existsSync(resolve(directory, 'a.snap.gz'))).toBe(false);
      await expect(refreshWitnesses(root, resolve(root, 'receipts'))).resolves.toEqual({});
      await expect(prepareWitnesses(root)).resolves.toBeUndefined();
      put('test/proof/fake/ticks.txt', '8');
      await expect(refreshWitnesses(root, resolve(root, 'receipts'))).rejects.toThrow(/recorded outcome|hashes or outcomes/u);
      expect(readFileSync(resolve(directory, 'manifest.json'), 'utf8')).toBe(withInputs(committed, 'bb'));
    } finally { rmSync(root, { recursive: true, force: true }); }
  }, 30_000);
  it('blanks only the top-level inputs hash', () => {
    const text = '{\n  "inputs": "aa",\n  "nested": {\n    "inputs": "zz"\n  }\n}\n';
    expect(manifestOutcome(text)).toBe('{\n  "inputs": "",\n  "nested": {\n    "inputs": "zz"\n  }\n}\n');
    expect(withInputs(text, 'bb')).toBe(text.replace('"aa"', '"bb"'));
    expect(() => manifestOutcome('{\n  "ticks": 1\n}\n')).toThrow('single top-level');
  });
  it('refreshes input-only staleness, remembers the verified triple and names every changed payload', async () => {
    const root = realpathSync(mkdtempSync(resolve(tmpdir(), 'witness-fixture-'))), cache = resolve(root, 'cache');
    const put = (file: string, value: string): void => { mkdirSync(dirname(resolve(root, file)), { recursive: true }); writeFileSync(resolve(root, file), value); };
    const recordings = (): number => { try { return readFileSync(resolve(root, 'test/proof/fake/recordings.log'), 'utf8').length; } catch { return 0; } };
    try {
      put('scripts/sim-node-loader.mjs', ''); fakeWitness(put);
      await expect(refreshWitnesses(root, cache)).resolves.toEqual({});
      expect(recordings()).toBe(0);
      put('test/proof/fake/inputs.txt', 'bb');
      await expect(refreshWitnesses(root, cache)).resolves.toEqual({ 'test/proof/fake/checkpoints/manifest.json': fakeManifest('bb') });
      expect(recordings()).toBe(1);
      put('test/proof/fake/checkpoints/manifest.json', fakeManifest('aa')); // a retried export of the same commit
      await expect(refreshWitnesses(root, cache)).resolves.toEqual({ 'test/proof/fake/checkpoints/manifest.json': fakeManifest('bb') });
      expect(recordings()).toBe(1);
      put('test/proof/fake/checkpoints/manifest.json', fakeManifest('aa')); put('test/proof/fake/inputs.txt', 'cc'); put('test/proof/fake/payload.txt', 'p2');
      await expect(refreshWitnesses(root, cache)).rejects.toThrow(/fake: the re-record on clean HEAD changed a\.snap\.gz;/u);
      put('test/proof/fake/checkpoints/manifest.json', fakeManifest('aa')); put('test/proof/fake/checkpoints/a.snap.gz', 'p1'); put('test/proof/fake/payload.txt', 'p1'); put('test/proof/fake/ticks.txt', '8');
      await expect(refreshWitnesses(root, cache)).rejects.toThrow('fake: the re-record on clean HEAD changed manifest.json (recorded outcome)');
    } finally { rmSync(root, { recursive: true, force: true }); }
  }, 30_000);
  it('refreshes recorded bake files before hashing witnesses that load them', async () => {
    await fixture(async (root, put, git) => {
      fakeWitness(put);
      put('scripts/bake-loader.mjs', '');
      put('scripts/bake-input-hashes.mjs', `import { writeFileSync } from 'node:fs';
writeFileSync(process.argv[4], JSON.stringify({ 'test/proof/fake/inputs.txt': 'bb' }));
`);
      git(['add', '--', 'test', 'scripts/bake-loader.mjs', 'scripts/bake-input-hashes.mjs']);
      git(['commit', '-qm', 'witness consumes a recorded bake']);
      const sha = await regenerateCommitted(root);
      expect(git(['show', `${sha}:test/proof/fake/inputs.txt`])).toBe('bb');
      expect(git(['show', `${sha}:test/proof/fake/checkpoints/manifest.json`])).toBe(fakeManifest('bb').trim());
      expect(git(['show', `${sha}:test/proof/fake/checkpoints/a.snap.gz`])).toBe('p1');
      await expect(refreshWitnesses(root, resolve(root, 'cache'))).resolves.toEqual({});
    });
  }, 30_000);
  it('commits refreshed input hashes in the regeneration commit and refuses a changed payload without touching HEAD', async () => {
    await fixture(async (root, put, git) => {
      fakeWitness(put); git(['add', '--', 'test']); git(['commit', '-qm', 'witness', '--', 'test']);
      const fresh = git(['rev-parse', 'HEAD']);
      expect(await regenerateCommitted(root)).toBe(fresh);
      put('test/proof/fake/inputs.txt', 'bb'); git(['commit', '-qm', 'a loaded module changed', '--', 'test/proof/fake/inputs.txt']);
      const source = git(['rev-parse', 'HEAD']), sha = await regenerateCommitted(root);
      expect(git(['show', `${sha}:test/proof/fake/checkpoints/manifest.json`])).toBe(fakeManifest('bb').trim());
      expect(git(['diff-tree', '--no-commit-id', '--name-only', '-r', sha])).toBe('test/proof/fake/checkpoints/manifest.json');
      expect(git(['show', '-s', '--format=%B', sha])).toContain(`payloads byte-identical: fake\n\nGenerated-Source: ${source}`);
      expect(readFileSync(resolve(root, 'test/proof/fake/checkpoints/manifest.json'), 'utf8')).toBe(fakeManifest('bb'));
      await expect(checkCommitted(root, sha)).resolves.toBeUndefined();
      put('test/proof/fake/inputs.txt', 'cc'); put('test/proof/fake/payload.txt', 'p2');
      git(['commit', '-qm', 'behaviour changed without a rebake', '--', 'test/proof/fake/inputs.txt', 'test/proof/fake/payload.txt']);
      const behaviour = git(['rev-parse', 'HEAD']);
      await expect(regenerateCommitted(root)).rejects.toThrow(/payloads changed; the push refuses them:\n {2}fake: the re-record on clean HEAD changed a\.snap\.gz/u);
      expect(git(['rev-parse', 'HEAD'])).toBe(behaviour);
      put('test/proof/fake/checkpoints/manifest.json', `${JSON.stringify({ inputs: 'cc', ticks: 9 }, null, 2)}\n`);
      git(['commit', '-qm', `forged\n\nGenerated-Source: ${behaviour}`, '--', 'test/proof/fake/checkpoints/manifest.json']);
      await expect(checkCommitted(root, git(['rev-parse', 'HEAD']))).rejects.toThrow('never its payload records');
    });
  }, 60_000);
  it('refuses a builder commit that only refreshes a witness input hash, but admits a deliberate rebake', () => {
    const root = realpathSync(mkdtempSync(resolve(tmpdir(), 'witness-precommit-')));
    const put = (file: string, value: string): void => { mkdirSync(dirname(resolve(root, file)), { recursive: true }); writeFileSync(resolve(root, file), value); };
    const git = (args: string[]): string => execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim();
    try {
      git(['init', '-q', '-b', 'main']); git(['config', 'user.name', 'fixture']); git(['config', 'user.email', 'fixture@example.invalid']);
      fakeWitness(put); git(['add', '--', 'test']); git(['commit', '-qm', 'witness']);
      put('test/proof/fake/checkpoints/manifest.json', fakeManifest('bb')); git(['add', '--', 'test']);
      expect(() => { precommitGenerated(root); }).toThrow('Builders leave witness input hashes to scripts/push-main.sh');
      put('test/proof/fake/checkpoints/manifest.json', fakeManifest('bb', 8)); put('test/proof/fake/checkpoints/a.snap.gz', 'p2'); git(['add', '--', 'test']);
      expect(() => { precommitGenerated(root); }).not.toThrow();
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});
