// oxlint-disable-next-line import/no-nodejs-modules -- The fixture owns an isolated producer input and cache.
import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
// oxlint-disable-next-line import/no-nodejs-modules -- Temporary cache directories belong to this fixture.
import { tmpdir } from 'node:os';
// oxlint-disable-next-line import/no-nodejs-modules -- Resolve fixture and child-process paths.
import { join, resolve as absolutePath } from 'node:path';
// oxlint-disable-next-line import/no-nodejs-modules -- A content-addressed key records real input bytes.
import { createHash } from 'node:crypto';
// oxlint-disable-next-line import/no-nodejs-modules -- Independent producers exercise the interprocess lease.
import { spawn } from 'node:child_process';
// oxlint-disable-next-line import/no-nodejs-modules -- Spawn children with this exact Node toolchain.
import { execPath } from 'node:process';
import { expect, it } from 'vitest';
import { generationKey, runGenerationJob, type GenerationJob } from '../scripts/generation-cache.mjs';

const hash = (text: string): string => createHash('sha256').update(text).digest('hex');
function fixture(): {root:string; job:GenerationJob; cacheDir:string; generate:(directory:string)=>Promise<void>} {
  const root = mkdtempSync(join(tmpdir(), 'generation-test-'));
  writeFileSync(join(root, 'source.ts'), 'author source');
  const job: GenerationJob = {id:'fixture',inputs:{'source.ts':hash('author source')},command:['node','source.ts'],outputs:['out/result.bin'],platform:'native'};
  return {root,job,cacheDir:join(root,'cache'),generate:async directory => { await Promise.resolve(); mkdirSync(join(directory,'out'));writeFileSync(join(directory,'out/result.bin'),'generated bytes'); }};
}
it('coalesces cold callers, validates warm bytes and regenerates a corrupt or incomplete job', async () => {
  const f=fixture();let calls=0;
  const generate=async (directory:string):Promise<void> => {calls++;await f.generate(directory);};
  try {
    const [a,b]=await Promise.all([runGenerationJob(f.root,f.job,{...f,generate}),runGenerationJob(f.root,f.job,{...f,generate})]);
    expect(a).toEqual(b);expect(calls).toBe(1);expect(a.hit).toBe(false);
    expect((await runGenerationJob(f.root,f.job,{...f,generate})).hit).toBe(true);
    writeFileSync(join(a.directory,'out/result.bin'),'corruption');
    expect((await runGenerationJob(f.root,f.job,{...f,generate})).hit).toBe(false);
    rmSync(join(a.directory,'out/result.bin'));
    expect((await runGenerationJob(f.root,f.job,{...f,generate})).hit).toBe(false);expect(calls).toBe(3);
  } finally {rmSync(f.root,{recursive:true,force:true});}
});
it('keys command, source bytes, tools and native OS/arch while portable output shares hosts', () => {
  const f=fixture();
  try {
    const key=generationKey(f.root,f.job);
    expect(generationKey(f.root,{...f.job,command:['node','other.ts']})).not.toBe(key);
    expect(generationKey(f.root,{...f.job,tools:{encoder:'2'}})).not.toBe(key);
    expect(generationKey(f.root,f.job,{platform:'linux',arch:'x64'})).not.toBe(generationKey(f.root,f.job,{platform:'darwin',arch:'arm64'}));
    expect(generationKey(f.root,{...f.job,platform:'portable'},{platform:'linux',arch:'x64'})).toBe(generationKey(f.root,{...f.job,platform:'portable'},{platform:'darwin',arch:'arm64'}));
    writeFileSync(join(f.root,'source.ts'),'next source');
    expect(() => generationKey(f.root,f.job)).toThrow('input changed');
    expect(generationKey(f.root,{...f.job,inputs:{'source.ts':hash('next source')}})).not.toBe(key);
  } finally {rmSync(f.root,{recursive:true,force:true});}
});
it('publishes neither failure nor changed-input output, and never writes the source checkout', async () => {
  const f=fixture();
  try {
    await expect(runGenerationJob(f.root,f.job,{...f,generate:async dir => {await f.generate(dir);throw new Error('producer failed');}})).rejects.toThrow('producer failed');
    expect(existsSync(join(f.cacheDir,f.job.id,generationKey(f.root,f.job)))).toBe(false);
    await expect(runGenerationJob(f.root,f.job,{...f,generate:async dir => {await f.generate(dir);appendFileSync(join(f.root,'source.ts'),'mutation');}})).rejects.toThrow('input changed');
    expect(existsSync(join(f.root,'out'))).toBe(false);
  } finally {rmSync(f.root,{recursive:true,force:true});}
});
it('force-compare regenerates but refuses a differing output without replacing the original cache', async () => {
  const f=fixture();
  try {
    const a=await runGenerationJob(f.root,f.job,f);
    expect((await runGenerationJob(f.root,f.job,{...f,forceCompare:true})).hit).toBe(false);
    await expect(runGenerationJob(f.root,f.job,{...f,forceCompare:true,generate:async dir => {await f.generate(dir);writeFileSync(join(dir,'out/result.bin'),'different');}})).rejects.toThrow('Regenerate-and-compare');
    expect(readFileSync(join(a.directory,'out/result.bin'),'utf8')).toBe('generated bytes');
  } finally {rmSync(f.root,{recursive:true,force:true});}
});
it('refuses traversal, missing outputs and symlink escapes, and executes native jobs on Linux', async () => {
  const f=fixture();
  try {
    expect(() => generationKey(f.root,{...f.job,outputs:['../escape']})).toThrow();
    await expect(runGenerationJob(f.root,f.job,{...f,generate:async () => {await Promise.resolve();}})).rejects.toThrow();
    await expect(runGenerationJob(f.root,f.job,{...f,generate:async dir => {mkdirSync(join(dir,'out'));symlinkSync(join(f.root,'source.ts'),join(dir,'out/result.bin'));await Promise.resolve();}})).rejects.toThrow('Invalid generated file');
    expect((await runGenerationJob(f.root,f.job,{...f,platform:'linux',arch:'x64'})).hit).toBe(false);
    await expect(runGenerationJob(f.root,{...f.job,platform:'darwin'},{...f,platform:'linux'})).rejects.toThrow('Darwin-only');
  } finally {rmSync(f.root,{recursive:true,force:true});}
});
it('serializes independent producer processes under the same key', async () => {
  const f=fixture();
  const source=`import {runGenerationJob} from ${JSON.stringify(absolutePath('scripts/generation-cache.mjs'))};import fs from 'node:fs';
await runGenerationJob(${JSON.stringify(f.root)},${JSON.stringify(f.job)},{cacheDir:${JSON.stringify(f.cacheDir)},generate:async dir=>{fs.appendFileSync(${JSON.stringify(join(f.root,'calls'))},'call\\n');await new Promise(r=>setTimeout(r,50));fs.mkdirSync(dir+'/out');fs.writeFileSync(dir+'/out/result.bin','generated bytes');}});`;
  try {
    const children=[spawn(execPath,['--input-type=module','-e',source]),spawn(execPath,['--input-type=module','-e',source])];
    const results=await Promise.all(children.map(child=>new Promise<number|null>((resolve,reject)=>{child.once('close',resolve);child.once('error',reject);})));
    expect(results).toEqual([0,0]);expect(readFileSync(join(f.root,'calls'),'utf8')).toBe('call\n');
  } finally {rmSync(f.root,{recursive:true,force:true});}
});
