import { describe, expect, it } from 'vitest';
import { APPENDIX_END, builderGeneratedChanges, engineAppendix, generatedIncreases, increaseTrailers, replaceDebt, verifyIncreaseTrailers } from '../scripts/generated-policy.mjs';
import { compareCounts } from '../scripts/guard-counts.mjs';

describe('SF6b generated counts and their approvals', () => {
  it('defers legacy measurements without relaxing hard rules or zero-debt promotion', () => {
    const key = 'wildshard/example', file = 'src/example.ts';
    expect(compareCounts({}, { [key]: { [file]: 1 } }, new Set(), [file], false, true)).toMatchObject({ failures: [], warnings: [expect.stringContaining('coordinator approval')] });
    expect(compareCounts({}, { [key]: { [file]: 1 } }, new Set([key]), [file], false, true).failures).toHaveLength(1);
    expect(compareCounts({ [key]: { [file]: 1 } }, {}, new Set(), undefined, true, true).failures.join(',')).toContain('move it to .oxlintrc.json');
  });
  it('replaces debt without modifying or lowering any policy input', () => {
    const policy = { allow: { raw: { file: 'approved stopwatch' } }, budgets: { gpu: 12 }, debugRows: { max: 29, raisedBy: ['E435'] } };
    const before = { ...policy, 'wildshard/example': { old: 4 } };
    expect(replaceDebt(before, { 'wildshard/example': { old: 1 } })).toEqual({ ...policy, 'wildshard/example': { old: 1 } });
    expect(before['wildshard/example']).toEqual({ old: 4 });
    expect(replaceDebt(before, {})).toEqual(policy);
  });
  it('rejects invalid counts before accepting a generated candidate', () => {
    expect(() => replaceDebt({}, { 'wildshard/raw': { file: -1 } })).toThrow('Invalid debt');
    expect(() => generatedIncreases({ edges: {}, ratchet: {} }, { edges: { edge: 0.5 }, ratchet: {} })).toThrow('Invalid graph');
  });
  it('lists new files and graph pairs, with no transfer of removed slack', () => {
    const before = { edges: { 'game → engine': 4 }, ratchet: { 'wildshard/raw': { old: 5 } } };
    const after = { edges: { 'game → engine': 6, 'sdk → game': 1 }, ratchet: { 'wildshard/raw': { fresh: 1 } } };
    expect(generatedIncreases(before, after)).toEqual([
      { kind: 'debt', key: 'wildshard/raw', file: 'fresh', before: 0, after: 1 },
      { kind: 'graph', key: 'game → engine', before: 4, after: 6 },
      { kind: 'graph', key: 'sdk → game', before: 0, after: 1 },
    ]);
    expect(generatedIncreases(after, before)).toEqual([{ kind: 'debt', key: 'wildshard/raw', file: 'old', before: 0, after: 5 }]);
  });
  it('requires the named coordinator and every exact increase', () => {
    const changes = generatedIncreases({ edges: {}, ratchet: {} }, { edges: { 'game → engine': 1 }, ratchet: {} });
    expect(() => increaseTrailers(changes)).toThrow('coordinator');
    expect(() => increaseTrailers(changes, 'builder')).toThrow('coordinator');
    const message = increaseTrailers(changes, 'wildshard-new');
    expect(() => verifyIncreaseTrailers(changes, message)).not.toThrow();
    expect(() => verifyIncreaseTrailers(changes, '')).toThrow('approver');
    expect(() => verifyIncreaseTrailers(changes, 'Generated-Approver: wildshard-new')).toThrow('Unlisted');
    expect(() => verifyIncreaseTrailers(changes, `${message}\n${message}`)).toThrow();
    expect(() => verifyIncreaseTrailers([], message)).toThrow('Unlisted');
    expect(() => verifyIncreaseTrailers([{ ...changes[0], kind: 'graph', key: 'game → engine', before: 0, after: 2 }], message)).toThrow('Unlisted');
  });
  it('lets builders change prose and policy, while refusing even one generated byte', () => {
    const before: Record<string, string> = { 'docs/ENGINE.md': 'manual', 'lint/ratchet.json': JSON.stringify({ debugRows: { max: 29 }, 'wildshard/raw': { f: 1 } }), 'lint/layer-edges.json': '{}' };
    const staged: Record<string, string> = { ...before, 'docs/ENGINE.md': 'new prose', 'lint/ratchet.json': JSON.stringify({ debugRows: { max: 30 }, 'wildshard/raw': { f: 1 } }) };
    const read = (files: Record<string, string>) => (file: string): string => files[file] ?? '';
    expect(builderGeneratedChanges(Object.keys(staged), read(before), read(staged))).toEqual([]);
    staged['lint/layer-edges.json'] = '{"invented":1}';
    expect(builderGeneratedChanges(Object.keys(staged), read(before), read(staged))).toEqual(['lint/layer-edges.json']);
  });
  it('renders the existing appendix format deterministically with duplicate names counted once', () => {
    const output = engineAppendix({ indexes: { engine: [{ name: 'Clock', from: '@wildshard/engine/clock' }, { name: 'Clock', from: '@wildshard/engine/clock' }, { name: 'Clock', from: '@wildshard/engine/alias' }] } });
    expect(output).toContain('1 exports, grouped');
    expect(output.match(/- `@wildshard\/engine\/clock`: `Clock`/gu)).toHaveLength(1);
    expect(output.endsWith(APPENDIX_END)).toBe(true);
  });
});
