// oxlint-disable-next-line import/no-nodejs-modules -- Real commits and child generators run in an isolated fixture repository.
import { execFileSync, spawnSync } from 'node:child_process';
// oxlint-disable-next-line import/no-nodejs-modules -- Own throwaway repositories only.
import { cpSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
// oxlint-disable-next-line import/no-nodejs-modules -- Canonical temporary fixture paths.
import { tmpdir } from 'node:os';
// oxlint-disable-next-line import/no-nodejs-modules -- Canonical temporary fixture paths.
import { dirname, resolve } from 'node:path';
// oxlint-disable-next-line import/no-nodejs-modules -- Resolve fixture package links from the real checkout.
import { cwd, execPath } from 'node:process';
import { describe, expect, it } from 'vitest';
import { generatedFiles } from '../scripts/generated-files.mjs';
import { checkShardfileReference } from '../scripts/docs/gen-shardfile-reference.mjs';
import { checkCommitted, regenerateCommitted } from '../scripts/regenerate-committed.mjs';
import { linkNodeModules } from '../scripts/link-node-modules.mjs';
import { precommitGenerated } from '../scripts/precommit-generated.mjs';

function fixture(run: (root: string, put: (file: string, value: string) => void, git: (args: string[]) => string) => void | Promise<void>, reference = true): Promise<void> {
  const root = realpathSync(mkdtempSync(resolve(tmpdir(), 'sf6b-fixture-')));
  const put = (file: string, value: string): void => { mkdirSync(dirname(resolve(root, file)), { recursive: true }); writeFileSync(resolve(root, file), value); };
  const git = (args: string[]): string => execFileSync('git', args, { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }).trim();
  return (async () => {
    try {
      cpSync('lint', resolve(root, 'lint'), { recursive: true });
      for (const file of ['scripts/generated-files.mjs', 'scripts/generated-policy.mjs', 'scripts/precommit-generated.mjs', 'scripts/regenerate-committed.mjs', 'scripts/link-node-modules.mjs', 'scripts/gen-api.mjs', 'scripts/check-graph.mjs', 'scripts/guard-counts.mjs', 'scripts/normalize/liveness.mjs', 'scripts/sim-node-loader.mjs', 'scripts/docs/schema-reference.mjs', 'scripts/docs/gen-shardfile-reference.mjs', 'scripts/docs/read-shardfile-reference.mjs', 'scripts/docs/sdk-schemas.mjs']) {
        mkdirSync(dirname(resolve(root, file)), { recursive: true }); cpSync(file, resolve(root, file));
      }
      for (const file of ['.oxlintrc.json', '.oxlintrc.ratchet.json']) cpSync(file, resolve(root, file));
      put('package.json', '{"type":"module"}'); put('tsconfig.json', '{"compilerOptions":{"strict":true,"types":[],"moduleResolution":"bundler","module":"esnext"}}');
      for (const layer of ['engine', 'game', 'sdk', 'commons']) put(`src/${layer}/package.json`, JSON.stringify({ name: `@wildshard/${layer}`, exports: layer === 'engine' ? { './clock': './clock.ts' } : {} }));
      put('src/engine/clock.ts', '/** Authoritative time. */\nexport const tick = 1;\n');
      put('src/engine/level/context.ts', '/** Generic context. */\nexport interface LevelContext {}\n');
      put('src/game/shard/context.ts', '/** Content context. */\nexport interface ShardContext {}\n');
      put('src/game/shardfile/schema.ts', "import * as v from 'valibot';\nexport const ShardfileSchema = v.strictObject({ version: v.literal('0.1') });\n");
      put('src/engine/script/abi.ts', 'export const SCRIPT_IMPORTS = { fuel: [127, 0] };\nexport const SCRIPT_EXPORTS = { on_tick: [] };\nexport const SCRIPT_ABI = { version: 0 };\n');
      put('lint/api-undocumented.json', '{"max":0}'); put('lint/layer-edges.json', '{"edges":{}}');
      put('lint/ratchet.json', '{"allow":{},"budgets":{"gpu":12},"debugRows":{"max":5,"raisedBy":["E435"]}}');
      put('docs/ENGINE.md', '<!-- exports:start (generated by test/engine-docs.test.ts; do not edit by hand) -->\n<!-- exports:end -->\n');
      linkNodeModules(cwd(), root);
      for (const [file, value] of Object.entries(generatedFiles(root).outputs)) if (reference || file !== 'docs/api/SHARDFILE.md') put(file, value);
      git(['init', '-q', '-b', 'main']); git(['config', 'user.name', 'SF6b fixture']); git(['config', 'user.email', 'fixture@example.invalid']);
      git(['add', '--', 'src', 'scripts', 'lint', 'docs', 'package.json', 'tsconfig.json', '.oxlintrc.json', '.oxlintrc.ratchet.json']);
      git(['commit', '-qm', 'fixture baseline']);
      git(['commit', '-qm', 'baseline ready', '--allow-empty']);
      await run(root, put, git);
    } finally { rmSync(root, { recursive: true, force: true }); }
  })();
}
describe('SF6b clean committed regeneration', () => {
  it('adds the first generated schema appendix without a builder committing output', async () => {
    await fixture(async (root, _put, git) => {
      const sha = await regenerateCommitted(root);
      expect(git(['show', `${sha}:docs/api/SHARDFILE.md`])).toContain('$.version');
      expect(git(['diff', '--cached', '--name-only'])).toBe('');
      await expect(checkCommitted(root, sha)).resolves.toBeUndefined();
    }, false);
  }, 30_000);
  it('refuses stale schema references and regenerates only committed schema inputs', async () => {
    await fixture(async (root, put, git) => {
      checkShardfileReference(root);
      const old = readFileSync(resolve(root, 'docs/api/SHARDFILE.md'), 'utf8');
      put('src/game/shardfile/schema.ts', "import * as v from 'valibot';\nexport const ShardfileSchema = v.strictObject({ version: v.literal('0.1'), reward: v.optional(v.pipe(v.number(), v.minValue(0)), 7) });\n");
      git(['commit', '-qm', 'schema source change', '--', 'src/game/shardfile/schema.ts']);
      expect(() => checkShardfileReference(root)).toThrow('Stale generated shardfile reference');
      await expect(checkCommitted(root, git(['rev-parse', 'HEAD']))).rejects.toThrow('Stale or hand-edited');
      put('docs/api/SHARDFILE.md', 'Hand-edited reference.\n'); git(['add', '--', 'docs/api/SHARDFILE.md']);
      expect(() => precommitGenerated(root)).toThrow('Builders commit source only');
      put('docs/api/SHARDFILE.md', old); git(['add', '--', 'docs/api/SHARDFILE.md']);
      // Disk-only edits must never enter the reference generated from the source commit.
      put('src/game/shardfile/schema.ts', "import * as v from 'valibot';\nexport const ShardfileSchema = v.strictObject({ unpublished: v.string() });\n");
      const sha = await regenerateCommitted(root);
      const generated = git(['show', `${sha}:docs/api/SHARDFILE.md`]);
      expect(generated).toContain('| $.reward | number | optional; default 7 | min_value 0 |');
      expect(generated).not.toContain('unpublished');
      expect(readFileSync(resolve(root, 'src/game/shardfile/schema.ts'), 'utf8')).toContain('unpublished');
      await expect(checkCommitted(root, sha)).resolves.toBeUndefined();
      rmSync(resolve(root, 'docs/api/SHARDFILE.md'));
      expect(() => checkShardfileReference(root)).toThrow('Stale generated shardfile reference');
    });
  }, 30_000);
  it('warns about source-only graph increases but keeps shard reach and cross-layer cycles fatal', async () => {
    await fixture((root, put, git) => {
      put('src/game/clock.ts', "import { tick } from '@wildshard/engine/clock';\nexport const gameTick = tick;\n");
      git(['add', '--', 'src/game/clock.ts']);
      const args = ['scripts/check-graph.mjs', '--source-only', '--paths', 'src/game/clock.ts'];
      const warning = spawnSync(execPath, args, { cwd: root, encoding: 'utf8' });
      expect(warning.status, warning.stderr).toBe(0); expect(warning.stderr).toContain('coordinator approval');
      put('src/engine/clock.ts', "import { gameTick } from '@wildshard/game/clock';\nexport const tick = gameTick;\n"); git(['add', '--', 'src/engine/clock.ts']);
      const cycle = spawnSync(execPath, [...args, 'src/engine/clock.ts'], { cwd: root, encoding: 'utf8' });
      expect(cycle.status).toBe(1); expect(cycle.stderr).toContain('cycle across');
      put('src/shards/alpha/plugin.ts', 'export const run = 1;'); git(['add', '--', 'src/shards/alpha/plugin.ts']);
      put('src/game/clock.ts', "import { run } from '../shards/alpha/plugin';\nexport const gameTick = run;\n"); git(['add', '--', 'src/game/clock.ts']);
      const reach = spawnSync(execPath, args, { cwd: root, encoding: 'utf8' });
      expect(reach.status).toBe(1); expect(reach.stderr).toContain('reaches into');
    });
  });
  it('discovers a newly exported SDK schema and refuses missing fields or ABI calls in the committed reference', async () => {
    await fixture(async (root, put, git) => {
      put('src/sdk/package.json', JSON.stringify({ name: '@wildshard/sdk', exports: { './worldSource': './worldSource.ts' } }));
      put('src/sdk/worldSource.ts', "import * as v from 'valibot';\n/** Build-only authored world input. */\nexport const WorldSourceSchema = v.strictObject({ glb: v.string(), scale: v.optional(v.number(), 1) });\n");
      put('src/engine/script/abi.ts', 'export const SCRIPT_IMPORTS = { fuel: [127, 0], query: [127, 127, 127, 127] };\nexport const SCRIPT_EXPORTS = { on_tick: [] };\nexport const SCRIPT_ABI = { version: 0 };\n');
      git(['add', '--', 'src/sdk/worldSource.ts']);
      git(['commit', '-qm', 'SDK schema and ABI source', '--', 'src/sdk/package.json', 'src/sdk/worldSource.ts', 'src/engine/script/abi.ts']);
      expect(() => checkShardfileReference(root)).toThrow('Schema documentation coverage');
      const sha = await regenerateCommitted(root), path = resolve(root, 'docs/api/SHARDFILE.md');
      const document = readFileSync(path, 'utf8');
      expect(document).toContain('$sdk["./worldSource"].WorldSourceSchema.scale');
      expect(document).toContain('| import | query | i32, i32, i32 | i32 |');
      checkShardfileReference(root);
      put('docs/api/SHARDFILE.md', document.split('\n').filter(line => !line.startsWith('| $sdk["./worldSource"].WorldSourceSchema.glb |')).join('\n'));
      expect(() => checkShardfileReference(root)).toThrow('fields missing: $sdk["./worldSource"].WorldSourceSchema.glb');
      put('docs/api/SHARDFILE.md', document.split('\n').filter(line => !line.startsWith('| import | query |')).join('\n'));
      expect(() => checkShardfileReference(root)).toThrow('abi missing: import.query');
      put('docs/api/SHARDFILE.md', document);
      await expect(checkCommitted(root, sha)).resolves.toBeUndefined();
    });
  }, 30_000);
  it('checks staged generated edits while allowing source-only commits and manual prose or policy edits', async () => {
    await fixture((root, put, git) => {
      const baseline = readFileSync(resolve(root, 'lint/api-surface.json'), 'utf8');
      // A foreign disk edit does not participate until it is explicitly staged in this fixture.
      put('lint/api-surface.json', `${baseline}\n`);
      expect(() => precommitGenerated(root)).not.toThrow();
      git(['add', '--', 'lint/api-surface.json']);
      expect(() => precommitGenerated(root)).toThrow('Builders commit source only');
      put('lint/api-surface.json', baseline); git(['add', '--', 'lint/api-surface.json']);
      const doc = readFileSync(resolve(root, 'docs/ENGINE.md'), 'utf8');
      put('docs/ENGINE.md', `Manual API explanation.\n${doc}`);
      git(['add', '--', 'docs/ENGINE.md']);
      expect(() => precommitGenerated(root)).not.toThrow();
    });
  });
  it('joins two export/import source commits within a minute with one regeneration, preserving foreign WIP and policy', async () => {
    await fixture(async (root, put, git) => {
      const start = Date.now();
      put('src/engine/clock.ts', '/** Authoritative time. */\nexport const tick = 1;\n/** Paused time. */\nexport const paused = 0;\n');
      git(['commit', '-qm', 'builder one export', '--', 'src/engine/clock.ts']);
      const approval = resolve(root, 'approved.json');
      writeFileSync(approval, JSON.stringify({ approver: 'wildshard-new', increases: [{ kind: 'graph', key: 'game → engine', before: 0, after: 1 }] }));
      // The second builder lands while the pusher is computing the first committed export.
      const pending = regenerateCommitted(root, approval);
      put('src/game/clock.ts', "import { tick } from '@wildshard/engine/clock';\n/** Shared clock. */\nexport const gameTick = tick;\n");
      git(['add', '--', 'src/game/clock.ts']); git(['commit', '-qm', 'builder two import', '--', 'src/game/clock.ts']);
      const source = git(['rev-parse', 'HEAD']);
      expect(Date.now() - start).toBeLessThan(60_000);
      const policy = JSON.parse(readFileSync(resolve(root, 'lint/ratchet.json'), 'utf8')) as unknown;
      // Independent working edits must not enter the clean export or be overwritten by its private-index landing.
      put('src/engine/clock.ts', '/** Foreign WIP. */\nexport const unpublished = 9;\n');
      put('lint/layer-edges.json', '{"edges":{"foreign":99}}');
      put('docs/api/ENGINE.md', 'Independent staged table edit.\n'); git(['add', '--', 'docs/api/ENGINE.md']);
      const sha = await pending;
      expect(git(['rev-list', '--count', `${source}..HEAD`])).toBe('1');
      expect(git(['show', '-s', '--format=%B', sha])).toContain(`Generated-Source: ${source}`);
      expect(git(['show', `${sha}:lint/api-surface.json`])).toContain('paused');
      expect(git(['show', `${sha}:lint/api-surface.json`])).not.toContain('unpublished');
      expect(git(['show', `${sha}:src/engine/clock.ts`])).toContain('paused');
      expect(readFileSync(resolve(root, 'src/engine/clock.ts'), 'utf8')).toContain('unpublished');
      expect(readFileSync(resolve(root, 'lint/layer-edges.json'), 'utf8')).toContain('foreign');
      expect(git(['diff', '--cached', '--name-only'])).toBe('docs/api/ENGINE.md');
      expect(git(['show', ':docs/api/ENGINE.md'])).toBe('Independent staged table edit.');
      expect(readFileSync(resolve(root, 'docs/api/ENGINE.md'), 'utf8')).toBe('Independent staged table edit.\n');
      expect(JSON.parse(git(['show', `${sha}:lint/ratchet.json`]))).toEqual(policy);
      await expect(checkCommitted(root, sha)).resolves.toBeUndefined();
      expect(await regenerateCommitted(root)).toBe(sha);
    });
  }, 30_000);
  it('rejects stale docs, measured increases without approval and hand-edited counts without touching HEAD', async () => {
    await fixture(async (root, put, git) => {
      const baseline = git(['rev-parse', 'HEAD']);
      await expect(checkCommitted(root, baseline)).resolves.toBeUndefined();
      put('src/game/clock.ts', "import { tick } from '@wildshard/engine/clock';\n/** Shared clock. */\nexport const gameTick = tick;\n");
      git(['add', '--', 'src/game/clock.ts']); git(['commit', '-qm', 'unapproved source edge', '--', 'src/game/clock.ts']);
      const source = git(['rev-parse', 'HEAD']);
      await expect(regenerateCommitted(root)).rejects.toThrow('Coordinator approval required');
      expect(git(['rev-parse', 'HEAD'])).toBe(source);
      await expect(checkCommitted(root, source)).rejects.toThrow('Stale or hand-edited');
      put('lint/layer-edges.json', '{"edges":{"game → engine":99}}');
      git(['commit', '-qm', 'hand edited measurement', '--', 'lint/layer-edges.json']);
      await expect(checkCommitted(root, git(['rev-parse', 'HEAD']))).rejects.toThrow('serialized regeneration');
    });
  }, 30_000);
});
