// oxlint-disable-next-line import/no-nodejs-modules -- Real commits and child generators run in an isolated fixture repository.
import { execFileSync } from 'node:child_process';
// oxlint-disable-next-line import/no-nodejs-modules -- Own throwaway repositories only.
import { cpSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
// oxlint-disable-next-line import/no-nodejs-modules -- Canonical temporary fixture paths.
import { tmpdir } from 'node:os';
// oxlint-disable-next-line import/no-nodejs-modules -- Canonical temporary fixture paths.
import { dirname, resolve } from 'node:path';
// oxlint-disable-next-line import/no-nodejs-modules -- Resolve fixture package links from the real checkout.
import { cwd } from 'node:process';
import { describe, expect, it } from 'vitest';
import { generatedFiles } from '../scripts/generated-files.mjs';
import { checkCommitted, regenerateCommitted } from '../scripts/regenerate-committed.mjs';
import { linkNodeModules } from '../scripts/link-node-modules.mjs';

function fixture(run: (root: string, put: (file: string, value: string) => void, git: (args: string[]) => string) => Promise<void>): Promise<void> {
  const root = realpathSync(mkdtempSync(resolve(tmpdir(), 'sf6b-fixture-')));
  const put = (file: string, value: string): void => { mkdirSync(dirname(resolve(root, file)), { recursive: true }); writeFileSync(resolve(root, file), value); };
  const git = (args: string[]): string => execFileSync('git', args, { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }).trim();
  return (async () => {
    try {
      cpSync('lint', resolve(root, 'lint'), { recursive: true });
      for (const file of ['scripts/generated-files.mjs', 'scripts/generated-policy.mjs', 'scripts/regenerate-committed.mjs', 'scripts/link-node-modules.mjs', 'scripts/gen-api.mjs', 'scripts/check-graph.mjs', 'scripts/guard-counts.mjs', 'scripts/normalize/liveness.mjs']) {
        mkdirSync(dirname(resolve(root, file)), { recursive: true }); cpSync(file, resolve(root, file));
      }
      for (const file of ['.oxlintrc.json', '.oxlintrc.ratchet.json']) cpSync(file, resolve(root, file));
      put('package.json', '{"type":"module"}'); put('tsconfig.json', '{"compilerOptions":{"strict":true,"types":[],"moduleResolution":"bundler","module":"esnext"}}');
      for (const layer of ['engine', 'game', 'kit', 'sdk']) put(`src/${layer}/package.json`, JSON.stringify({ name: `@wildshard/${layer}`, exports: layer === 'engine' ? { './clock': './clock.ts' } : {} }));
      put('src/engine/clock.ts', '/** Authoritative time. */\nexport const tick = 1;\n');
      put('src/engine/level/context.ts', '/** Generic context. */\nexport interface LevelContext {}\n');
      put('src/game/shard/context.ts', '/** Content context. */\nexport interface ShardContext {}\n');
      put('lint/api-undocumented.json', '{"max":0}'); put('lint/layer-edges.json', '{"edges":{}}');
      put('lint/ratchet.json', '{"allow":{},"budgets":{"gpu":12},"debugRows":{"max":5,"raisedBy":["E435"]}}');
      put('docs/ENGINE.md', '<!-- exports:start (generated by test/engine-docs.test.ts; do not edit by hand) -->\n<!-- exports:end -->\n');
      linkNodeModules(cwd(), root);
      for (const [file, value] of Object.entries(generatedFiles(root).outputs)) put(file, value);
      git(['init', '-q', '-b', 'main']); git(['config', 'user.name', 'SF6b fixture']); git(['config', 'user.email', 'fixture@example.invalid']);
      git(['add', '--', 'src', 'scripts', 'lint', 'docs', 'package.json', 'tsconfig.json', '.oxlintrc.json', '.oxlintrc.ratchet.json']);
      git(['commit', '-qm', 'fixture baseline']);
      git(['commit', '-qm', 'baseline ready', '--allow-empty']);
      await run(root, put, git);
    } finally { rmSync(root, { recursive: true, force: true }); }
  })();
}
describe('SF6b clean committed regeneration', () => {
  it('joins two export/import source commits within a minute with one regeneration, preserving foreign WIP and policy', async () => {
    await fixture(async (root, put, git) => {
      const start = Date.now();
      put('src/engine/clock.ts', '/** Authoritative time. */\nexport const tick = 1;\n/** Paused time. */\nexport const paused = 0;\n');
      git(['commit', '-qm', 'builder one export', '--', 'src/engine/clock.ts']);
      const approval = resolve(root, 'approved.json');
      writeFileSync(approval, JSON.stringify({ approver: 'wildshard-new', increases: [{ kind: 'graph', key: 'game → engine', before: 0, after: 1 }] }));
      // The second builder lands while the pusher is computing the first committed export.
      const pending = regenerateCommitted(root, approval);
      put('src/game/clock.ts', "import { tick } from '@wildshard/engine/clock';\n/** Shared clock. */\nexport const gameTick = tick;\n");
      git(['add', '--', 'src/game/clock.ts']); git(['commit', '-qm', 'builder two import', '--', 'src/game/clock.ts']);
      const source = git(['rev-parse', 'HEAD']);
      expect(Date.now() - start).toBeLessThan(60_000);
      const policy = JSON.parse(readFileSync(resolve(root, 'lint/ratchet.json'), 'utf8')) as unknown;
      // Independent working edits must not enter the clean export or be overwritten by its private-index landing.
      put('src/engine/clock.ts', '/** Foreign WIP. */\nexport const unpublished = 9;\n');
      put('lint/layer-edges.json', '{"edges":{"foreign":99}}');
      const sha = await pending;
      expect(git(['rev-list', '--count', `${source}..HEAD`])).toBe('1');
      expect(git(['show', '-s', '--format=%B', sha])).toContain(`Generated-Source: ${source}`);
      expect(git(['show', `${sha}:lint/api-surface.json`])).toContain('paused');
      expect(git(['show', `${sha}:lint/api-surface.json`])).not.toContain('unpublished');
      expect(git(['show', `${sha}:src/engine/clock.ts`])).toContain('paused');
      expect(readFileSync(resolve(root, 'src/engine/clock.ts'), 'utf8')).toContain('unpublished');
      expect(readFileSync(resolve(root, 'lint/layer-edges.json'), 'utf8')).toContain('foreign');
      expect(git(['diff', '--cached', '--name-only'])).toBe('');
      expect(JSON.parse(git(['show', `${sha}:lint/ratchet.json`]))).toEqual(policy);
      await expect(checkCommitted(root, sha)).resolves.toBeUndefined();
      expect(await regenerateCommitted(root)).toBe(sha);
    });
  }, 30_000);
  it('rejects stale docs, measured increases without approval and hand-edited counts without touching HEAD', async () => {
    await fixture(async (root, put, git) => {
      const baseline = git(['rev-parse', 'HEAD']);
      await expect(checkCommitted(root, baseline)).resolves.toBeUndefined();
      put('src/game/clock.ts', "import { tick } from '@wildshard/engine/clock';\n/** Shared clock. */\nexport const gameTick = tick;\n");
      git(['add', '--', 'src/game/clock.ts']); git(['commit', '-qm', 'unapproved source edge', '--', 'src/game/clock.ts']);
      const source = git(['rev-parse', 'HEAD']);
      await expect(regenerateCommitted(root)).rejects.toThrow('Coordinator approval required');
      expect(git(['rev-parse', 'HEAD'])).toBe(source);
      await expect(checkCommitted(root, source)).rejects.toThrow('Stale or hand-edited');
      put('lint/layer-edges.json', '{"edges":{"game → engine":99}}');
      git(['commit', '-qm', 'hand edited measurement', '--', 'lint/layer-edges.json']);
      await expect(checkCommitted(root, git(['rev-parse', 'HEAD']))).rejects.toThrow('serialized regeneration');
    });
  }, 30_000);
});
