export const STRINGS = {
  name: 'Signal Dunes', biome: 'Desert dunes at dusk',
  blurb: 'Dark orange dunes just after sunset. Crack the bullwhip, drive off the dune rays and light the signal fire.',
  whip: 'Bullwhip', whipBlurb: 'A braided leather bullwhip: a long, narrow crack. Hold ATTACK (or HEAVY) for a double crack that yanks small beasts in and staggers big ones.',
  ray: 'Dune ray', rayBlurb: 'A great gliding ray that circles the dusk and swoops at walkers on the crests.',
  skitterer: 'Sand skitterer', skittererBlurb: 'A small burrowing scavenger that hunts in packs: it waits under the sand and bursts out at your heels.',
  strider: 'Dune strider', striderBlurb: 'A tall, slow grazer with a horned head. It paws the sand before it charges.',
  matriarch: 'The Dune Matriarch', matriarchTitle: 'Mother of the dusk rays', retry: 'The Matriarch circles again',
  phaseDives: 'Sweeping dives', phaseStorm: 'Sand storm', phaseGrounded: 'Grounded',
  bossReward: 'The Matriarch falls: 20 coins', bossRewardAgain: 'The Matriarch falls',
  tower: 'Signal tower', towerBlurb: 'A wooden signal tower on a far dune crest, its brazier cold.',
  brazier: 'Signal brazier', light: 'Light the signal fire', lit: 'Signal fire lit', fireHint: 'Light the three waymark braziers first',
  caravan: 'Half-buried caravan', well: 'Dry well', rocks: 'Wind-cut sandstone', dressing: 'Scrub, markers and bones', waymark: 'Waymark brazier',
  readLog: 'Read the logbook', logRead: 'The caravan logbook',
  logText: '"Oil sealed in the old well, east. Light the waymarks, then the tower: the signal calls the riders home."',
  wellDown: 'The bucket hangs down the well', wellHint: 'The bucket is down the shaft: pull the windlass crank with a heavy crack',
  pullHint: 'A heavy (double) crack pulls the crank', takeOil: 'Take the oil jar', oilTaken: 'The well is empty', oilGot: 'Oil jar taken',
  needOil: 'An empty waymark brazier', needOilHint: 'It needs oil: the logbook says the old well', pourOil: 'Pour oil into the brazier',
  crackToLight: 'Crack the whip at the bowl to light it', waymarkLit: 'Waymark lit', allLit: 'All three waymarks burn: now the tower',
  scoutName: 'Sefa, the caravan scout', talkScout: 'Talk to Sefa', scoutPin: 'Sefa', shortScout: 'SEFA',
  stepScout: 'Talk to Sefa on the crest', chipScout: 'Light signal fire', hintScout: 'An old scout waits on the spawn crest. She knows where the caravan went.',
  scoutHello: "You came over the crest at last light. Good. I'm Sefa: I scout for the caravan.",
  scoutAsk: 'Our riders rode out three days ago and never came back. The wagon broke down in the dunes, west of here.',
  scoutHow: "Read the logbook on its tailboard: it knows where the oil is. Light the waymarks, then the signal fire on the tower. They'll see it and come home.",
  scoutLater: "The wagon is west of the crest, half under the sand. The logbook knows the way.",
  scoutDone: 'Riders on the far dunes. You brought them home.',
  quest: 'The signal', stepLog: "Find the caravan's logbook", stepOil: 'Fetch oil from the dry well', stepWaymarks: 'Light the three waymark braziers',
  step: 'Light the signal fire', reward: 'The riders are coming home: 5 coins', summoned: 'The bowl erupts: the Dune Matriarch rises',
  stepBoss: 'Face the Dune Matriarch in the bowl', newQuest: 'New quest', objective: 'Objective', discovered: 'Discovered',
  chipLog: 'Caravan logbook', chipOil: 'Oil from the well', chipWaymarks: 'Light the waymarks', chipFire: 'The signal fire', chipBoss: 'The Matriarch',
  shortLog: 'LOGBOOK', shortWell: 'DRY WELL', shortWaymark: 'WAYMARK', shortTower: 'SIGNAL TOWER', shortBasin: 'THE BOWL',
  hintLog: 'The caravan lies half-buried west of the crest. Its logbook is on the tailboard.',
  hintOil: 'The logbook says the oil is sealed in the old well, east. A heavy (double) crack pulls the windlass crank.',
  hintWaymarks: 'Pour oil into each waymark brazier, then crack the whip at the bowl to light it.',
  hintFire: 'Climb the signal tower and light its brazier. The signal calls the riders home.',
  hintBoss: 'The fire woke her. Drive the Matriarch down in the sand bowl north of the tower.',
  placeCrest: 'Signal crest', placeBasin: 'The sand bowl',
  rewardKicker: 'Quest complete', rewardSubtitle: 'Answering fires on the far dunes: the riders are coming home',
  dunes: 'Dune sea', trail: 'Crest path',
  frameSpawn: 'Spawn: the crest, the signal tower far off', frameWhip: 'The bullwhip mid-crack',
  frameRay: 'The dune ray against the dusk', frameQuest: 'Quest done: the signal fire lit',
} as const;
