export const STRINGS = {
  name: 'Signal Dunes', biome: 'Desert dunes at dusk',
  blurb: 'Dark orange dunes just after sunset. Crack the bullwhip, drive off the dune rays and light the signal fire.',
  whip: 'Bullwhip', whipBlurb: 'A braided leather bullwhip: a long, narrow crack. Hold ATTACK (or HEAVY) for a double crack that yanks small beasts in and staggers big ones.',
  ray: 'Dune ray', rayBlurb: 'A great gliding ray that circles the dusk and swoops at walkers on the crests.',
  skitterer: 'Sand skitterer', skittererBlurb: 'A small burrowing scavenger that hunts in packs: it waits under the sand and bursts out at your heels.',
  strider: 'Dune strider', striderBlurb: 'A tall, slow grazer with a horned head. It paws the sand before it charges.',
  matriarch: 'The Dune Matriarch', matriarchTitle: 'Mother of the dusk rays', retry: 'The Matriarch circles again',
  phaseDives: 'Sweeping dives', phaseStorm: 'Sand storm', phaseGrounded: 'Grounded',
  bossReward: 'The Matriarch falls: 20 coins', bossRewardAgain: 'The Matriarch falls',
  tower: 'Signal tower', towerBlurb: 'A wooden signal tower on a far dune crest, its brazier cold.',
  brazier: 'Signal brazier', light: 'Light the signal fire', lit: 'Signal fire lit', fireHint: 'Light the three waymark braziers first',
  caravan: 'Half-buried caravan', well: 'Dry well', rocks: 'Wind-cut sandstone', waymark: 'Waymark brazier',
  readLog: 'Read the logbook', logRead: 'The caravan logbook',
  logText: '"Oil sealed in the old well, east. Light the waymarks, then the tower: the signal calls the riders home."',
  wellDown: 'The bucket hangs down the well', wellHint: 'The bucket is down the shaft: pull the windlass crank with a heavy crack',
  pullHint: 'A heavy (double) crack pulls the crank', takeOil: 'Take the oil jar', oilTaken: 'The well is empty', oilGot: 'Oil jar taken',
  needOil: 'An empty waymark brazier', needOilHint: 'It needs oil: the logbook says the old well', pourOil: 'Pour oil into the brazier',
  crackToLight: 'Crack the whip at the bowl to light it', waymarkLit: 'Waymark lit', allLit: 'All three waymarks burn: now the tower',
  quest: 'The signal', stepLog: "Find the caravan's logbook", stepOil: 'Fetch oil from the dry well', stepWaymarks: 'Light the three waymark braziers',
  step: 'Light the signal fire', reward: 'Signal lit: 5 coins', summoned: 'Something vast stirs in the basin',
  dunes: 'Dune sea', trail: 'Crest path',
  frameSpawn: 'Spawn: the crest, the signal tower far off', frameWhip: 'The bullwhip mid-crack',
  frameRay: 'The dune ray against the dusk', frameQuest: 'Quest done: the signal fire lit',
} as const;
