export const STRINGS = {
  name: 'Sky Reach', biome: 'Floating islands above the clouds', label: '(+1, +4)',
  blurb: 'Grassy islands drift over a sea of cloud at golden hour. Rope bridges hold your weight; the glowing ones carry only a hoverboard.',
  sunrest: 'Sunrest', windmill: 'Windmill isle', roost: 'The Roost', grove: 'Pine grove', keeper: 'Keeper\'s isle', ruin: 'Vane ruin', step: 'The high step', crown: 'The storm crown',
  rope: 'Rope bridge', hover: 'Hover bridge', fallen: 'Crown bridge', winch: 'Bridge winch', mill: 'Old windmill', pines: 'Island pines', updraft: 'Updraft',
  vane: 'Wind vane', notesName: 'Bridge-keeper\'s lectern',
  turnWinch: 'Turn the winch', winchPin: 'WINCH', readNotes: 'Read the keeper\'s notes', notesPin: 'NOTES', vanePin: 'VANE',
  notesToast: 'Keeper\'s notes: "The crown bridge only answers the winch when the vanes turn and the roost is quiet."',
  fan: 'War fan', fanBlurb: 'SWING slashes; GUST blows a cone of wind that throws creatures back, off the edge if they are near one.',
  swing: 'SWING', gust: 'GUST',
  ray: 'Drift ray', rayNote: 'A manta of the high air. It circles, hangs over you, then dives. Gust it out of the sky.',
  goat: 'Sky goat', goatNote: 'Grazes the island tops and rams whatever crowds it. A gust near the rim sends it into the clouds.',
  wisp: 'Gale wisp', wispNote: 'A knot of wind that darts in and bursts against you.',
  roc: 'Storm Roc', rocTitle: 'Lord of the storm crown', rocRetry: 'Face the Storm Roc again',
  rocP1: 'It stoops from the storm', rocP2: 'Walls of gale', rocP3: 'Grounded on the dais', rocDown: 'The Storm Roc falls into the clouds',
  quest: 'The crown bridge', notes: 'Find the bridge-keeper\'s notes', roostQuest: 'Clear the roost of drift rays', vanes: 'Turn the three wind vanes with GUST',
  raise: 'Raise the bridge to the storm crown', raised: 'The crown bridge is up', winchLocked: 'The winch will not turn while the roost is loud and the vanes are still', vaneTurned: 'A vane turns', reward: 'Quest reward: 10 coins', bossReward: 'The storm breaks: 25 coins',
} as const;
