import { defineConfig, type Plugin } from 'vite';
import { execSync } from 'node:child_process';
import { readdirSync, statSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { pwaPlugin } from './vite/pwa-plugin';

// Build stamp: short git sha + build time. Baked into the bundle as __BUILD_ID__ and
// emitted as /version.json so the running app can tell when the server has a newer build
// (iOS home-screen PWAs have no address bar, so the title screen offers the reload).
function buildId(): string {
  let sha = (process.env.VERCEL_GIT_COMMIT_SHA ?? '').slice(0, 7);
  try { sha ||= execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch {}
  return `${sha || 'b'}-${Date.now().toString(36)}`;
}
const BUILD_ID = buildId();
const versionJson = () => JSON.stringify({ build: BUILD_ID, time: new Date().toISOString() });

// /asset-index.json: every file under public/assets with its byte size, so the loading
// screen can show real "x / y MB" totals for the files it has requested so far.
function assetIndex(): string {
  const out: Record<string, number> = {};
  const walk = (dir: string, pub: string) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name); const st = statSync(p);
      if (st.isDirectory()) walk(p, `${pub}/${name}`); else out[`${pub}/${name}`] = st.size;
    }
  };
  try { walk('public/assets', '/assets'); } catch {}
  return JSON.stringify(out);
}

// Pre-bake every shard's terrain (scripts/bake-chunk.mjs → public/assets/baked/<slug>/terrain.bin) before
// the byte table below is written, so the bake is declared and downloaded like any other asset. Idempotent
// by content hash: a no-op unless a chunk's terrain sources changed. Never fatal (the game computes at launch).
function bakeChunks() {
  try { execSync('node --import ./scripts/bake-loader.mjs scripts/bake-chunk.mjs', { stdio: 'inherit' }); }
  catch (e) { console.warn('[bake] terrain bake failed — launch falls back to the analytic field', e); }
}
bakeChunks();

// src/boot/bytes.generated.ts: the same table as a committed TS module, so the boot plan's declared
// denominators need no fetch and `pnpm tsc` fails when a file a chunk declares disappears.
function writeBytesModule() {
  const rows = JSON.parse(assetIndex()) as Record<string, number>;
  const body = Object.keys(rows).filter((k) => !k.endsWith('.DS_Store')).sort().map((k) => `  ${JSON.stringify(k)}: ${rows[k]},`).join('\n');
  const src = `// generated by vite.config.ts from public/assets — do not edit. Regenerated by every vite build / dev.\nexport const PUBLIC_BYTES = {\n${body}\n} as const;\n`;
  const out = 'src/boot/bytes.generated.ts';
  if (!existsSync(out) || readFileSync(out, 'utf8') !== src) writeFileSync(out, src);
}
writeBytesModule();

const versionPlugin = (): Plugin => ({
  name: 'wildshard-version',
  generateBundle() {
    this.emitFile({ type: 'asset', fileName: 'version.json', source: versionJson() });
    this.emitFile({ type: 'asset', fileName: 'asset-index.json', source: assetIndex() });
  },
  configureServer(server) {
    const json = (body: () => string) => (_req: unknown, res: import('node:http').ServerResponse) => {
      res.setHeader('Content-Type', 'application/json'); res.setHeader('Cache-Control', 'no-store'); res.end(body());
    };
    server.middlewares.use('/version.json', json(versionJson));
    server.middlewares.use('/asset-index.json', json(assetIndex));
  },
});

export default defineConfig({
  server: { port: 5173, host: true },
  build: { target: 'es2022', chunkSizeWarningLimit: 4000 },
  assetsInclude: ['**/*.hdr', '**/*.gltf', '**/*.bin'],
  define: { __BUILD_ID__: JSON.stringify(BUILD_ID) },
  plugins: [versionPlugin(), pwaPlugin(BUILD_ID)],
});
