// Generated by scripts/bake-ktx2.mjs — commit this table with its KTX2 assets.
export const GPU_FILES: { readonly phone: Readonly<Record<string, string>>; readonly desktop: Readonly<Record<string, string>> } = {
  "phone": {
    "/assets/far-reach/fan/hand-hd.glb": "/assets/gpu/far-reach/fan/hand-hd-c0f55842.glb",
    "/assets/far-reach/models/crown/crown-dais.glb": "/assets/gpu/far-reach/models/crown/crown-dais-5be87ff4.glb",
    "/assets/far-reach/models/crown/crown-stone-b.glb": "/assets/gpu/far-reach/models/crown/crown-stone-b-29462c51.glb",
    "/assets/far-reach/models/crown/crown-stone.glb": "/assets/gpu/far-reach/models/crown/crown-stone-9f11341b.glb",
    "/assets/far-reach/models/isle-canopy-hd/isle-canopy-hd.glb": "/assets/gpu/far-reach/models/isle-canopy-hd/isle-canopy-hd-bf1fd6f4.glb",
    "/assets/far-reach/models/isle-falls-hd/isle-falls-hd.glb": "/assets/gpu/far-reach/models/isle-falls-hd/isle-falls-hd-e08d88b4.glb",
    "/assets/far-reach/models/isle-mass-hd/isle-mass-hd.glb": "/assets/gpu/far-reach/models/isle-mass-hd/isle-mass-hd-ddefbb74.glb",
    "/assets/far-reach/models/isle-shelf-hd/isle-shelf-hd.glb": "/assets/gpu/far-reach/models/isle-shelf-hd/isle-shelf-hd-2d4d0a78.glb",
    "/assets/far-reach/models/isle-spire-hd/isle-spire-hd.glb": "/assets/gpu/far-reach/models/isle-spire-hd/isle-spire-hd-4d9fa20b.glb",
    "/assets/far-reach/models/isle-twin-hd/isle-twin-hd.glb": "/assets/gpu/far-reach/models/isle-twin-hd/isle-twin-hd-f3db4a4e.glb",
    "/assets/far-reach/models/keeper-hd/keeper-hd.glb": "/assets/gpu/far-reach/models/keeper-hd/keeper-hd-9da1fe4b.glb",
    "/assets/far-reach/models/lantern-hd/lantern-hd.glb": "/assets/gpu/far-reach/models/lantern-hd/lantern-hd-e550eb78.glb",
    "/assets/far-reach/models/lectern-hd/lectern-hd.glb": "/assets/gpu/far-reach/models/lectern-hd/lectern-hd-4684ff2d.glb",
    "/assets/far-reach/models/mill/mill-foot.glb": "/assets/gpu/far-reach/models/mill/mill-foot-1ce9ad12.glb",
    "/assets/far-reach/models/mill/mill-tower.glb": "/assets/gpu/far-reach/models/mill/mill-tower-69879071.glb",
    "/assets/far-reach/models/post-hd/post-hd.glb": "/assets/gpu/far-reach/models/post-hd/post-hd-a79ab025.glb",
    "/assets/far-reach/models/roc-hd/roc-hd.glb": "/assets/gpu/far-reach/models/roc-hd/roc-hd-a92d7ac4.glb",
    "/assets/far-reach/models/trees/tree-bush.glb": "/assets/gpu/far-reach/models/trees/tree-bush-f83b25e1.glb",
    "/assets/far-reach/models/trees/tree-oak.glb": "/assets/gpu/far-reach/models/trees/tree-oak-eec69fd1.glb",
    "/assets/far-reach/models/trees/tree-pine-tall.glb": "/assets/gpu/far-reach/models/trees/tree-pine-tall-137f635a.glb",
    "/assets/far-reach/models/trees/tree-pine-wide.glb": "/assets/gpu/far-reach/models/trees/tree-pine-wide-36ae0de0.glb",
    "/assets/far-reach/models/trees/tree-pine-young.glb": "/assets/gpu/far-reach/models/trees/tree-pine-young-af30d3a7.glb"
  },
  "desktop": {}
};
