// Generated by scripts/bake/movers.mjs: the Rising Islet's admitted module (behaviour/islet.as).
export const LIFT_MODULE = { hash: 'f8f90ba2e03401910448a2af1e8b02420bc7b2e1003076bc6241d9cb0c688a22', bytes: 1748 } as const;
