#!/usr/bin/env node
// The Atlas: a draft's sources → drafts/public/data/<slug>/atlas.json, plus the title's drafts/public/data/index.json
// (WORLDCLAW-TOOLS W1, W2).
//
//   node drafts/tools/atlas.ts <slug>             regenerate from the sources and the committed images.json
//   node drafts/tools/atlas.ts <slug> --publish   first make + upload the phone copies of any new picture (Blob, J28)
//   node drafts/tools/atlas.ts --all [--publish]  every draft in drafts/shards/
//   node drafts/tools/atlas.ts --check            fail if any committed atlas is stale or has a picture with no copy
//
// Sources: drafts/shards/<slug>/draft.json (hand-kept by the run), its content.json, the art READMEs and the pictures.
import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { imgUrl, type Atlas, type DraftCard, type DraftIndex, type Terrain, type VariantStats } from '../src/atlas.ts';
import { buildAtlas, publicLeaks, type DraftConfig, type DraftContent } from './build-atlas.ts';
import { publishImages, type ImageIndex } from './images.ts';

const ROOT = resolve(import.meta.dirname, '..', '..');
const SHARDS = join(ROOT, 'drafts', 'shards');
const OUT = join(ROOT, 'drafts', 'public', 'data');
/** The game's COMING SOON cards (W9, J19, J38): the drafts' public cards as data the title deck reads. */
const GAME_CARDS = join(ROOT, 'src', 'game', 'draftTitles.ts');
export const SITE = 'https://wildshard-drafts.vercel.app';

/** The game's card data for every draft in the index: public fields only (name, line, stage, the key art on Blob). */
export function gameCards(index: DraftIndex): string {
  const rows = index.drafts.map((d) => ({
    slug: d.slug, name: d.name, line: d.line, stage: d.stage, stageName: d.stageName,
    thumb: d.keyArt ? imgUrl(index.blob, d.slug, d.keyArt, 'thumb') : '',
    hero: d.keyArt ? imgUrl(index.blob, d.slug, d.keyArt, 'full') : '',
    url: `${SITE}/#/${d.slug}`,
  }));
  return `// Generated by drafts/tools/atlas.ts from drafts/public/data/index.json; do not edit.
// The game's COMING SOON cards for the drafts (WORLDCLAW-TOOLS W9, J19, J38): public fields only, the key art on Blob.
export interface DraftTitle {
  readonly slug: string;
  readonly name: string;
  readonly line: string;
  readonly stage: string;
  readonly stageName: string;
  readonly thumb: string;
  readonly hero: string;
  readonly url: string;
}

export const DRAFT_TITLES: readonly DraftTitle[] = [
${rows.map((r) => `  {\n${Object.entries(r).map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n')}\n  },`).join('\n')}
];
`;
}

// oxlint-disable-next-line typescript/no-unnecessary-type-parameters -- JSON.parse is untyped; the caller names the file's shape
const readJson = <T>(p: string): T => JSON.parse(readFileSync(p, 'utf8')) as T;
const json = (v: unknown): string => `${JSON.stringify(v, null, 1)}\n`;
/** atlas.json ships to phones: one item per line keeps it diffable and small. */
const compact = (a: Atlas): string => `${JSON.stringify(a).replaceAll('},{"id"', '},\n{"id"')}\n`;

/** Map Lab's data: the blockout's binaries (already under drafts/public/data/<slug>/), the scene's roads, the spec's radii. */
function loadTerrain(config: DraftConfig): Terrain | null {
  const t = config.terrain;
  if (!t) return null;
  interface Scene { S: number; roads: Record<string, { w: number; pts: [number, number][] }>; places: Record<string, [number, number]> }
  interface Spec { regions: { id: string; color: string; walkable: boolean }[]; places: { id: string; r: number }[] }
  const scene = readJson<Scene>(join(ROOT, t.scene));
  const spec = readJson<Spec>(join(ROOT, t.spec));
  for (const f of [t.heights, t.labels]) {
    if (!existsSync(join(OUT, config.slug, f))) throw new Error(`${config.slug}: terrain file drafts/public/data/${config.slug}/${f} is missing`);
  }
  return {
    heights: t.heights, labels: t.labels, res: t.res, size: scene.S,
    cats: spec.regions.map((r) => ({ id: r.id, color: r.color, walkable: r.walkable })),
    roads: Object.entries(scene.roads).map(([name, r]) => ({ name, w: r.w, pts: r.pts })),
    places: Object.entries(scene.places).map(([id, [x, z]]) => ({
      id: t.placeIds[id] ?? id, x, z, r: spec.places.find((p) => p.id === id)?.r ?? 0,
    })),
    variants: t.variants.map((v) => ({ id: v.id, title: v.title, stats: readJson<VariantStats>(join(ROOT, v.stats)) })),
  };
}

interface Built { atlas: Atlas; card: DraftCard; problems: string[] }

async function one(slug: string, publish: boolean): Promise<Built> {
  const dir = join(SHARDS, slug);
  const config = readJson<DraftConfig>(join(dir, 'draft.json'));
  const content = readJson<DraftContent>(join(ROOT, config.content));
  const cams = config.cams ? readJson<Record<string, { eye: [number, number, number]; look: [number, number, number] }>>(join(ROOT, config.cams)) : {};
  const indexPath = join(dir, 'images.json');
  const index: ImageIndex = existsSync(indexPath) ? readJson<ImageIndex>(indexPath) : {};
  const now = new Date().toISOString();
  const terrain = loadTerrain(config);
  let res = buildAtlas({ root: ROOT, config, content, cams, terrain, index, now });
  if (publish) {
    const n = await publishImages(slug, res.sources, index, (s) => console.log(s));
    const sorted = Object.fromEntries(Object.entries(index).sort(([a], [b]) => a.localeCompare(b)));
    writeFileSync(indexPath, json(sorted));
    console.log(`${slug}: ${n} new picture(s) uploaded, ${Object.keys(index).length} in images.json`);
    res = buildAtlas({ root: ROOT, config, content, cams, terrain, index, now });
  }
  return { atlas: res.atlas, card: res.card, problems: [...res.problems, ...publicLeaks(res.card, res.atlas)] };
}

/** Atlases compare equal when only `generated` differs. */
function same(a: Atlas, b: Atlas): boolean {
  return JSON.stringify({ ...a, generated: '' }) === JSON.stringify({ ...b, generated: '' });
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const publish = args.includes('--publish');
  const check = args.includes('--check');
  const all = check || args.includes('--all');
  const slugs = all
    ? readdirSync(SHARDS).filter((d) => existsSync(join(SHARDS, d, 'draft.json'))).sort()
    : args.filter((a) => !a.startsWith('--'));
  if (slugs.length === 0) {
    console.error('usage: node drafts/tools/atlas.ts <slug> [--publish] | --all [--publish] | --check');
    process.exit(2);
  }
  let failed = false;
  const cards: DraftCard[] = [];
  let blob = '';
  for (const slug of slugs) {
    const { atlas, card, problems } = await one(slug, publish);
    cards.push(card);
    blob ||= atlas.blob;
    for (const p of problems) console.error(`${slug}: ${p}`);
    if (problems.length > 0) failed = true;
    const path = join(OUT, slug, 'atlas.json');
    if (check) {
      const prev = existsSync(path) ? readJson<Atlas>(path) : null;
      if (!prev || !same(prev, atlas)) {
        console.error(`${slug}: drafts/public/data/${slug}/atlas.json is stale; run node drafts/tools/atlas.ts ${slug}`);
        failed = true;
      }
      continue;
    }
    mkdirSync(join(OUT, slug), { recursive: true });
    const prev = existsSync(path) ? readJson<Atlas>(path) : null;
    if (!prev || !same(prev, atlas)) writeFileSync(path, compact(atlas));
    console.log(`${slug}: ${atlas.items.length} items, ${atlas.rounds.length} rounds, stage ${atlas.run.stage}`);
  }
  if (!check) {
    const indexPath = join(OUT, 'index.json');
    const prev = existsSync(indexPath) ? readJson<DraftIndex>(indexPath) : null;
    const keep = (prev?.drafts ?? []).filter((d) => !slugs.includes(d.slug));
    const drafts = [...keep, ...cards].sort((a, b) => a.slug.localeCompare(b.slug));
    if (JSON.stringify(prev?.drafts) !== JSON.stringify(drafts)) {
      writeFileSync(indexPath, json({ version: 1, blob: blob || (prev?.blob ?? ''), generated: new Date().toISOString(), drafts } satisfies DraftIndex));
    }
  }
  const index = readJson<DraftIndex>(join(OUT, 'index.json'));
  const cardsTs = gameCards(index);
  const prevTs = existsSync(GAME_CARDS) ? readFileSync(GAME_CARDS, 'utf8') : '';
  if (prevTs !== cardsTs) {
    if (check) {
      console.error('src/game/draftTitles.ts is stale; run node drafts/tools/atlas.ts --all');
      failed = true;
    } else writeFileSync(GAME_CARDS, cardsTs);
  }
  if (failed) process.exit(1);
}

await main();
