// Generated by scripts/bake-ktx2.mjs — commit this table with its KTX2 assets.
export const GPU_FILES: { readonly phone: Readonly<Record<string, string>>; readonly desktop: Readonly<Record<string, string>> } = {
  "phone": {
    "/assets/nine-dragon/lab/grapple/dragon-hook.glb": "/assets/gpu/nine-dragon/lab/grapple/dragon-hook-28bd7a4c.glb",
    "/assets/nine-dragon/lab/organic/leaf-atlas.webp": "/assets/gpu/nine-dragon/lab/organic/leaf-atlas-9658a9dd.ktx2",
    "/assets/nine-dragon/lab/organic/scroll.phone.webp": "/assets/gpu/nine-dragon/lab/organic/scroll.phone-580f21aa.ktx2",
    "/assets/nine-dragon/viewmodel/arm-r-maps.phone.webp": "/assets/gpu/nine-dragon/viewmodel/arm-r-maps.phone-2816edf9.ktx2",
    "/assets/nine-dragon/viewmodel/arm-r-nrm.phone.webp": "/assets/gpu/nine-dragon/viewmodel/arm-r-nrm.phone-1fa8943d.ktx2",
    "/assets/nine-dragon/viewmodel/fist-l-maps.phone.webp": "/assets/gpu/nine-dragon/viewmodel/fist-l-maps.phone-1d475e8f.ktx2",
    "/assets/nine-dragon/viewmodel/fist-l-nrm.phone.webp": "/assets/gpu/nine-dragon/viewmodel/fist-l-nrm.phone-92fb64b8.ktx2",
    "/assets/nine-dragon/viewmodel/gauntlet-maps.phone.webp": "/assets/gpu/nine-dragon/viewmodel/gauntlet-maps.phone-1be17999.ktx2",
    "/assets/nine-dragon/viewmodel/gauntlet-nrm.phone.webp": "/assets/gpu/nine-dragon/viewmodel/gauntlet-nrm.phone-f8d1632c.ktx2",
    "/assets/nine-dragon/viewmodel/hand-r-maps.phone.webp": "/assets/gpu/nine-dragon/viewmodel/hand-r-maps.phone-0e260f80.ktx2",
    "/assets/nine-dragon/viewmodel/hand-r-nrm.phone.webp": "/assets/gpu/nine-dragon/viewmodel/hand-r-nrm.phone-aa4d7ff1.ktx2"
  },
  "desktop": {
    "/assets/nine-dragon/lab/grapple/dragon-hook.glb": "/assets/gpu/nine-dragon/lab/grapple/dragon-hook-28bd7a4c.glb",
    "/assets/nine-dragon/lab/organic/leaf-atlas.webp": "/assets/gpu/nine-dragon/lab/organic/leaf-atlas-9658a9dd.ktx2",
    "/assets/nine-dragon/lab/organic/scroll.webp": "/assets/gpu/nine-dragon/lab/organic/scroll-6995996d.ktx2",
    "/assets/nine-dragon/viewmodel/arm-r-maps.webp": "/assets/gpu/nine-dragon/viewmodel/arm-r-maps-f6ec1be7.ktx2",
    "/assets/nine-dragon/viewmodel/arm-r-nrm.webp": "/assets/gpu/nine-dragon/viewmodel/arm-r-nrm-a78efc78.ktx2",
    "/assets/nine-dragon/viewmodel/fist-l-maps.webp": "/assets/gpu/nine-dragon/viewmodel/fist-l-maps-72e5d379.ktx2",
    "/assets/nine-dragon/viewmodel/fist-l-nrm.webp": "/assets/gpu/nine-dragon/viewmodel/fist-l-nrm-1486311c.ktx2",
    "/assets/nine-dragon/viewmodel/gauntlet-maps.webp": "/assets/gpu/nine-dragon/viewmodel/gauntlet-maps-bd5c98f6.ktx2",
    "/assets/nine-dragon/viewmodel/gauntlet-nrm.webp": "/assets/gpu/nine-dragon/viewmodel/gauntlet-nrm-b6a9ff02.ktx2",
    "/assets/nine-dragon/viewmodel/hand-r-maps.webp": "/assets/gpu/nine-dragon/viewmodel/hand-r-maps-9f246ed0.ktx2",
    "/assets/nine-dragon/viewmodel/hand-r-nrm.webp": "/assets/gpu/nine-dragon/viewmodel/hand-r-nrm-7f97d7d4.ktx2"
  }
};
