// Generated by scripts/bake/movers.mjs: the lantern lift's admitted module (behaviour/lift.as).
export const LIFT_MODULE = { hash: '734a577c8466d8bac0530cdef2929cc00e9ddd9120a453d0b0b4576e336b5cda', bytes: 1792 } as const;
