// Generated by scripts/bake/movers.mjs from today's collider/rest recipes.
import type { MoverData } from '@wildshard/sdk/movers';
/** Admitted modules own fixed-step motion; the engine owns collision and the rope solver. */
export const MOVERS: MoverData = [
  {
    "id": "nd.lift.n",
    "entity": 9001,
    "module": "2d64743636ae029714cc6aacb8874029e76dd38850c444b4e3a409c4908ff147",
    "kind": "platform",
    "at": {
      "x": 2.4,
      "y": 0,
      "z": -231.6
    },
    "euler": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "enabled": true,
    "boxes": [
      {
        "x": 0,
        "y": -0.15,
        "z": 0,
        "hx": 1.55,
        "hy": 0.15,
        "hz": 1.55,
        "rot": {
          "x": 0,
          "y": 0,
          "z": 0,
          "w": 1
        }
      },
      {
        "x": -1.5,
        "y": 1.3,
        "z": 0,
        "hx": 0.05,
        "hy": 1.3,
        "hz": 1.55,
        "rot": {
          "x": 0,
          "y": 0,
          "z": 0,
          "w": 1
        }
      },
      {
        "x": 1.5,
        "y": 1.3,
        "z": 0,
        "hx": 0.05,
        "hy": 1.3,
        "hz": 1.55,
        "rot": {
          "x": 0,
          "y": 0,
          "z": 0,
          "w": 1
        }
      },
      {
        "x": 0,
        "y": 2.75,
        "z": 0,
        "hx": 1.55,
        "hy": 0.15,
        "hz": 1.55,
        "rot": {
          "x": 0,
          "y": 0,
          "z": 0,
          "w": 1
        }
      }
    ],
    "input": [
      2.4,
      0,
      -231.6,
      2.4,
      125,
      -231.6,
      16,
      0
    ]
  },
  {
    "id": "nd.lift.n.gates",
    "entity": 9002,
    "module": "2d64743636ae029714cc6aacb8874029e76dd38850c444b4e3a409c4908ff147",
    "kind": "platform",
    "at": {
      "x": 2.4,
      "y": 0,
      "z": -231.6
    },
    "euler": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "enabled": false,
    "boxes": [
      {
        "x": 0,
        "y": 1.3,
        "z": -1.5,
        "hx": 1.55,
        "hy": 1.3,
        "hz": 0.05,
        "rot": {
          "x": 0,
          "y": 0,
          "z": 0,
          "w": 1
        }
      },
      {
        "x": 0,
        "y": 1.3,
        "z": 1.5,
        "hx": 1.55,
        "hy": 1.3,
        "hz": 0.05,
        "rot": {
          "x": 0,
          "y": 0,
          "z": 0,
          "w": 1
        }
      }
    ],
    "input": [
      2.4,
      0,
      -231.6,
      2.4,
      125,
      -231.6,
      16,
      1
    ]
  },
  {
    "id": "nd.lift.n.deck-door",
    "entity": 9003,
    "module": "2d64743636ae029714cc6aacb8874029e76dd38850c444b4e3a409c4908ff147",
    "kind": "static",
    "at": {
      "x": 2.4,
      "y": 0,
      "z": -231.6
    },
    "euler": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "enabled": false,
    "boxes": [
      {
        "x": 0,
        "y": 1.5,
        "z": -2,
        "hx": 1.6,
        "hy": 1.5,
        "hz": 0.18,
        "rot": {
          "x": 0,
          "y": 0,
          "z": 0,
          "w": 1
        }
      }
    ],
    "input": [
      2.4,
      0,
      -231.6,
      2.4,
      0,
      -231.6,
      16,
      2
    ]
  },
  {
    "id": "nd.lift.n.street-door",
    "entity": 9004,
    "module": "2d64743636ae029714cc6aacb8874029e76dd38850c444b4e3a409c4908ff147",
    "kind": "static",
    "at": {
      "x": 2.4,
      "y": 125,
      "z": -231.6
    },
    "euler": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "enabled": true,
    "boxes": [
      {
        "x": 0,
        "y": 1.5,
        "z": 1.8,
        "hx": 1.6,
        "hy": 1.5,
        "hz": 0.18,
        "rot": {
          "x": 0,
          "y": 0,
          "z": 0,
          "w": 1
        }
      }
    ],
    "input": [
      2.4,
      125,
      -231.6,
      2.4,
      125,
      -231.6,
      16,
      3
    ]
  }
];
