#!/usr/bin/env node
// Trusted SF30 compiler: immutable admitted modules, never dynamic git operations.
import { compileScript } from '../compile-script.mjs';
import { readFileSync, mkdirSync, writeFileSync, mkdtempSync, rmSync, symlinkSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, join } from 'node:path';
import { tmpdir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { build } from 'vite';
import { bridgeScriptSources } from '@wildshard/commons/scripts';

const repo = resolve(import.meta.dirname, '../..');
const modules = new Map();
const shared = bridgeScriptSources();
for (const [slug, file] of [['driftwood-isle', 'boat.as'], ['driftwood-isle', 'bridge.as'], ['far-reach', 'bridges.as'], ['far-reach', 'islet.as']]) {
  const bytes = await compileScript(readFileSync(join(repo, 'src/shards', slug, 'behaviour', file), 'utf8'), { maximumPages: 1, sources: shared.sources });
  const hash = createHash('sha256').update(bytes).digest('hex'), directory = join(repo, 'src/shards', slug, 'assets');
  mkdirSync(directory, { recursive: true }); writeFileSync(join(directory, hash), bytes);
  modules.set(`${slug}/${file}`, hash);
  process.stdout.write(`${slug}/${file} ${hash} ${bytes.length}\n`);
}
const scratch = mkdtempSync(join(tmpdir(), 'mover-export-'));
try {
  symlinkSync(join(repo, 'node_modules'), join(scratch, 'node_modules'));
  for (const slug of ['driftwood-isle', 'far-reach']) {
    const directory = join(scratch, slug);
    await build({ configFile: false, logLevel: 'silent', build: { target: 'esnext', outDir: directory, emptyOutDir: true,
      lib: { entry: join(repo, 'src/shards', slug, 'generators/movers.ts'), formats: ['es'], fileName: 'capture' },
      rolldownOptions: { platform: 'node', external: [/^node:/u] } } });
    const capture = await import(pathToFileURL(join(directory, 'capture.js')).href);
    const data = slug === 'driftwood-isle' ? capture.captureDriftwoodMovers(modules.get(`${slug}/boat.as`), modules.get(`${slug}/bridge.as`)) : capture.captureSkyMovers(modules.get(`${slug}/bridges.as`), modules.get(`${slug}/islet.as`));
    const target = join(repo, 'src/shards', slug, 'data'); mkdirSync(target, { recursive: true });
    writeFileSync(join(target, 'movers.ts'), `// Generated by scripts/bake/movers.mjs from today's collider/rest recipes.\nimport type { MoverData } from '@wildshard/sdk/movers';\n/** Admitted modules own fixed-step motion; the engine owns collision and the rope solver. */\nexport const MOVERS: MoverData = ${JSON.stringify(data, null, 2)};\n`);
  }
} finally { rmSync(scratch, { recursive: true, force: true }); }
