// generated by vite.config.ts from src/chunks/thumbs and src/explore/img — do not edit.
export const ART_BYTES: Readonly<Record<string, number>> = {
  "src/chunks/thumbs/driftwood-isle-landscape.jpg": 206802,
  "src/chunks/thumbs/driftwood-isle-portrait.jpg": 191996,
  "src/chunks/thumbs/driftwood-isle.jpg": 47431,
  "src/chunks/thumbs/nalati-grasslands-landscape.jpg": 388674,
  "src/chunks/thumbs/nalati-grasslands-portrait.jpg": 384246,
  "src/chunks/thumbs/nalati-grasslands.jpg": 72250,
  "src/chunks/thumbs/pine-hollow-landscape.jpg": 321432,
  "src/chunks/thumbs/pine-hollow-portrait.jpg": 381349,
  "src/chunks/thumbs/pine-hollow.jpg": 70244,
  "src/explore/img/models.webp": 21828,
  "src/explore/img/world.webp": 20798,
};
