// generated by vite.config.ts from public/assets/music/*/music.json and public/assets/sfx/*/sfx.json — do not edit.
export const MUSIC_MANIFESTS: Readonly<Record<string, unknown>> = {
 "folk": {
  "style": "folk",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "pine": {
    "calm": "pine-calm-10905c79.m4a",
    "tension": "pine-tension-180bc197.m4a",
    "bpm": 86.403,
    "beatsPerBar": 4,
    "loopStart": 25.542,
    "loopEnd": 69.9849,
    "duration": 72.768
   },
   "island": {
    "calm": "island-calm-d7d189f9.m4a",
    "tension": "island-tension-bb05ab64.m4a",
    "bpm": 85.186,
    "beatsPerBar": 4,
    "loopStart": 16.9738,
    "loopEnd": 42.33,
    "duration": 45.1627
   },
   "title": {
    "full": "title-50001128.m4a",
    "bpm": 104.908,
    "beatsPerBar": 4,
    "loopStart": 15.6735,
    "loopEnd": 63.7156,
    "duration": 66.0053
   }
  },
  "stings": {
   "death": "sting-death-67f54fe8.m4a",
   "chunk": "sting-chunk-31c10eaf.m4a",
   "pickup": "sting-pickup-332f81db.m4a"
  }
 },
 "nalati": {
  "style": "nalati",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "steppe-grass": {
    "calm": "steppe-grass-calm-68234a31.m4a",
    "tension": "steppe-grass-tension-e7aa4970.m4a",
    "bpm": 120.119,
    "beatsPerBar": 4,
    "loopStart": 3.4598,
    "loopEnd": 45.4182,
    "duration": 47.424
   },
   "steppe-sky": {
    "calm": "steppe-sky-calm-81e788bb.m4a",
    "tension": "steppe-sky-tension-478decfa.m4a",
    "bpm": 90.825,
    "beatsPerBar": 4,
    "loopStart": 17.0899,
    "loopEnd": 43.5142,
    "duration": 46.1653
   },
   "steppe-snow": {
    "calm": "steppe-snow-calm-2723fb59.m4a",
    "tension": "steppe-snow-tension-9f095e46.m4a",
    "bpm": 105.874,
    "beatsPerBar": 4,
    "loopStart": 28.6766,
    "loopEnd": 46.8114,
    "duration": 49.088
   },
   "steppe-night": {
    "calm": "steppe-night-calm-1b01c85d.m4a",
    "tension": "steppe-night-tension-849680a6.m4a",
    "bpm": 71.97,
    "beatsPerBar": 4,
    "loopStart": 8.6378,
    "loopEnd": 51.9895,
    "duration": 55.3387
   },
   "steppe-storm": {
    "calm": "steppe-storm-calm-e64bb429.m4a",
    "tension": "steppe-storm-tension-847136fa.m4a",
    "bpm": 87.177,
    "beatsPerBar": 4,
    "loopStart": 8.7307,
    "loopEnd": 52.779,
    "duration": 55.552
   },
   "steppe-king": {
    "calm": "steppe-king-calm-bbcfbe31.m4a",
    "tension": "steppe-king-tension-9d5ec1d2.m4a",
    "bpm": 79.712,
    "beatsPerBar": 4,
    "loopStart": 15.0233,
    "loopEnd": 42.121,
    "duration": 45.1413
   }
  },
  "stings": {
   "death": "sting-death-fc7a4dce.m4a",
   "chunk": "sting-chunk-c85d0270.m4a",
   "pickup": "sting-pickup-7ebca9f6.m4a"
  }
 },
 "orchestral": {
  "style": "orchestral",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "pine": {
    "calm": "pine-calm-fbc4a99e.m4a",
    "tension": "pine-tension-525d8c6d.m4a",
    "bpm": 95.925,
    "beatsPerBar": 4,
    "loopStart": 22.384,
    "loopEnd": 42.3996,
    "duration": 44.9067
   },
   "island": {
    "calm": "island-calm-27861d1b.m4a",
    "tension": "island-tension-73116f36.m4a",
    "bpm": 86.299,
    "beatsPerBar": 4,
    "loopStart": 16.1611,
    "loopEnd": 52.3146,
    "duration": 55.104
   },
   "title": {
    "full": "title-b47c8a52.m4a",
    "bpm": 116.041,
    "beatsPerBar": 4,
    "loopStart": 14.7911,
    "loopEnd": 43.7464,
    "duration": 45.824
   }
  },
  "stings": {
   "death": "sting-death-771d34f7.m4a",
   "chunk": "sting-chunk-a639b19e.m4a",
   "pickup": "sting-pickup-65f7ac5b.m4a"
  }
 },
 "piano": {
  "style": "piano",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "pine": {
    "calm": "pine-calm-923e0056.m4a",
    "tension": "pine-tension-cc014e5b.m4a",
    "bpm": 91.998,
    "beatsPerBar": 4,
    "loopStart": 6.757,
    "loopEnd": 58.9322,
    "duration": 61.5467
   },
   "island": {
    "calm": "island-calm-05125ed8.m4a",
    "tension": "island-tension-7faf0468.m4a",
    "bpm": 76.781,
    "beatsPerBar": 4,
    "loopStart": 14.3035,
    "loopEnd": 54.9384,
    "duration": 58.0693
   },
   "title": {
    "full": "title-3d1f713a.m4a",
    "bpm": 75.666,
    "beatsPerBar": 4,
    "loopStart": 27.3995,
    "loopEnd": 59.118,
    "duration": 62.2933
   }
  },
  "stings": {
   "death": "sting-death-99b071e0.m4a",
   "chunk": "sting-chunk-a4f2ffab.m4a",
   "pickup": "sting-pickup-6ed91318.m4a"
  }
 },
 "pine-hollow-folk": {
  "style": "folk",
  "set": "pine-hollow",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "night": {
    "calm": "night-calm-e5eeff22.m4a",
    "bpm": 86.006,
    "beatsPerBar": 4,
    "loopStart": 24.1952,
    "loopEnd": 71.6336,
    "duration": 74.432,
    "tension": "night-tension-0071c7a3.m4a"
   },
   "boss": {
    "calm": "boss-base-1ad74736.m4a",
    "bpm": 85.562,
    "beatsPerBar": 4,
    "loopStart": 15.2787,
    "loopEnd": 57.3533,
    "duration": 60.16,
    "layers": [
     "boss-bass-2f96accb.m4a",
     "boss-drums-90b1e7cb.m4a"
    ],
    "phases": {
     "1": [
      0.6,
      0
     ],
     "2": [
      1,
      0.55
     ],
     "3": [
      1,
      1
     ]
    },
    "phaseNames": {
     "1": "I - the Warden",
     "2": "II - Lanterns Fall",
     "3": "III - the Last Light"
    }
   }
  },
  "stings": {
   "dawn": "sting-dawn-35a7550c.m4a"
  }
 },
 "pine-hollow-orchestral": {
  "style": "orchestral",
  "set": "pine-hollow",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "night": {
    "calm": "night-calm-da54e0eb.m4a",
    "bpm": 85.421,
    "beatsPerBar": 4,
    "loopStart": 7.4072,
    "loopEnd": 41.1225,
    "duration": 43.9467,
    "tension": "night-tension-ba25e774.m4a"
   },
   "boss": {
    "calm": "boss-base-d7203ec0.m4a",
    "bpm": 89.221,
    "beatsPerBar": 4,
    "loopStart": 24.381,
    "loopEnd": 59.3502,
    "duration": 62.0587,
    "layers": [
     "boss-bass-c368d6c3.m4a",
     "boss-drums-4c4efeb7.m4a"
    ],
    "phases": {
     "1": [
      0.6,
      0
     ],
     "2": [
      1,
      0.55
     ],
     "3": [
      1,
      1
     ]
    },
    "phaseNames": {
     "1": "I - the Warden",
     "2": "II - Lanterns Fall",
     "3": "III - the Last Light"
    }
   }
  },
  "stings": {
   "dawn": "sting-dawn-eafd4a6d.m4a"
  }
 },
 "pine-hollow-piano": {
  "style": "piano",
  "set": "pine-hollow",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "night": {
    "calm": "night-calm-e935c4a1.m4a",
    "bpm": 93.892,
    "beatsPerBar": 4,
    "loopStart": 15.6502,
    "loopEnd": 46.3238,
    "duration": 48.896,
    "tension": "night-tension-48423068.m4a"
   },
   "boss": {
    "calm": "boss-base-8b00b5cf.m4a",
    "bpm": 84.375,
    "beatsPerBar": 4,
    "loopStart": 17.1828,
    "loopEnd": 51.3161,
    "duration": 54.1653,
    "layers": [
     "boss-bass-0ff27574.m4a",
     "boss-drums-c4644a0b.m4a"
    ],
    "phases": {
     "1": [
      0.6,
      0
     ],
     "2": [
      1,
      0.55
     ],
     "3": [
      1,
      1
     ]
    },
    "phaseNames": {
     "1": "I - the Warden",
     "2": "II - Lanterns Fall",
     "3": "III - the Last Light"
    }
   }
  },
  "stings": {
   "dawn": "sting-dawn-6b0b4004.m4a"
  }
 }
};
export const SFX_MANIFESTS: Readonly<Record<string, unknown>> = {
 "best": {
  "model": "MOSS-SoundEffect v2 + Stable Audio 3 Medium",
  "credit": "Sound effects: MOSS-SoundEffect v2 · Stable Audio 3 Medium — Powered by Stability AI",
  "licence": "Per file (see provenance.source): MOSS-SoundEffect v2.0 is Apache-2.0; Stable Audio 3 Medium is the Stability AI Community License (free below USD 1M revenue, register with Stability AI for commercial use, show 'Powered by Stability AI').",
  "beds": {
   "forest": {
    "file": "bed-forest-2-0cd11be5.m4a",
    "loopStart": 12.75,
    "loopEnd": 26.75,
    "duration": 27.7547,
    "gain": 0.5
   },
   "island": {
    "file": "bed-island-1-4611714d.m4a",
    "loopStart": 2.25,
    "loopEnd": 15.25,
    "duration": 16.256,
    "gain": 0.5
   },
   "underwater": {
    "file": "bed-underwater-3-cbe2810d.m4a",
    "loopStart": 9,
    "loopEnd": 21,
    "duration": 22.016,
    "gain": 0.5
   },
   "steppe-wind": {
    "file": "bed-steppe-wind-3-51fa5a78.m4a",
    "loopStart": 2,
    "loopEnd": 12,
    "duration": 13.0133,
    "gain": 0.5,
    "shard": "nalati"
   },
   "steppe-larks": {
    "file": "bed-steppe-larks-2-b0d20bcd.m4a",
    "loopStart": 2.75,
    "loopEnd": 17.75,
    "duration": 18.752,
    "gain": 0.5,
    "shard": "nalati"
   },
   "steppe-night": {
    "file": "bed-steppe-night-1-e1a88138.m4a",
    "loopStart": 2.75,
    "loopEnd": 17.75,
    "duration": 18.752,
    "gain": 0.5,
    "shard": "nalati"
   },
   "river": {
    "file": "bed-river-1-beb1a9a8.m4a",
    "loopStart": 6.25,
    "loopEnd": 21.25,
    "duration": 22.2507,
    "gain": 0.5,
    "shard": "nalati"
   },
   "meltwater": {
    "file": "bed-meltwater-2-608d0e3b.m4a",
    "loopStart": 8.75,
    "loopEnd": 18.75,
    "duration": 19.7547,
    "gain": 0.5,
    "shard": "nalati"
   },
   "camp": {
    "file": "bed-camp-1-c7570b1a.m4a",
    "loopStart": 9.5,
    "loopEnd": 19.5,
    "duration": 20.5013,
    "gain": 0.5,
    "shard": "nalati"
   },
   "highwind": {
    "file": "bed-highwind-1-95937f84.m4a",
    "loopStart": 2.5,
    "loopEnd": 12.5,
    "duration": 13.504,
    "gain": 0.5,
    "shard": "nalati"
   },
   "coldwind": {
    "file": "bed-coldwind-3-2fe1886b.m4a",
    "loopStart": 2,
    "loopEnd": 12,
    "duration": 13.0133,
    "gain": 0.5,
    "shard": "nalati"
   },
   "rain": {
    "file": "bed-rain-1-abadcece.m4a",
    "loopStart": 2.25,
    "loopEnd": 17.25,
    "duration": 18.2613,
    "gain": 0.5,
    "shard": "nalati"
   },
   "stormwind": {
    "file": "bed-stormwind-2-465916b5.m4a",
    "loopStart": 3,
    "loopEnd": 13,
    "duration": 14.016,
    "gain": 0.5,
    "shard": "nalati"
   }
  },
  "hums": {
   "pickup": {
    "file": "hum-pickup-3-7b7db58f.m4a",
    "loopStart": 3.25,
    "loopEnd": 9.25,
    "duration": 10.2613,
    "gain": 0.35
   },
   "shrine": {
    "file": "hum-shrine-2-d89ed03a.m4a",
    "loopStart": 2.75,
    "loopEnd": 8.75,
    "duration": 9.7707,
    "gain": 0.6
   }
  },
  "oneshots": {
   "crossbowFire": {
    "files": [
     "crossbowFire-3-18ccf9f0.m4a"
    ],
    "gain": 1
   },
   "dryFire": {
    "files": [
     "dryFire-2-88071d1d.m4a",
     "dryFire-3-173415cb.m4a"
    ],
    "gain": 1
   },
   "boltImpact-wood": {
    "files": [
     "boltImpact-wood-2-8e9e99ee.m4a",
     "boltImpact-wood-3-673a0ef6.m4a"
    ],
    "gain": 1
   },
   "boltImpact-ground": {
    "files": [
     "boltImpact-ground-2-5e8a3076.m4a",
     "boltImpact-ground-1-f81140e6.m4a"
    ],
    "gain": 1
   },
   "boltImpact-flesh": {
    "files": [
     "boltImpact-flesh-2-13ed7f2c.m4a",
     "boltImpact-flesh-3-62e25aa5.m4a"
    ],
    "gain": 1
   },
   "swordSwing": {
    "files": [
     "swordSwing-1-6303fc5d.m4a"
    ],
    "gain": 1
   },
   "swordHeavy": {
    "files": [
     "swordHeavy-2-1debcc8f.m4a",
     "swordHeavy-3-1bed510f.m4a"
    ],
    "gain": 1
   },
   "swordHit-flesh": {
    "files": [
     "swordHit-flesh-1-07225bb8.m4a",
     "swordHit-flesh-2-efbf5fd7.m4a"
    ],
    "gain": 1
   },
   "swordHit-wood": {
    "files": [
     "swordHit-wood-3-6381cc6b.m4a",
     "swordHit-wood-2-800b6fe9.m4a"
    ],
    "gain": 1
   },
   "dodge": {
    "files": [
     "dodge-2-13887dd8.m4a",
     "dodge-3-453516f6.m4a"
    ],
    "gain": 1
   },
   "lunge": {
    "files": [
     "lunge-3-be45ba7a.m4a"
    ],
    "gain": 1
   },
   "reload": {
    "files": [
     "reload-3-d81ab6e2.m4a",
     "reload-1-d3e6d32a.m4a"
    ],
    "gain": 1
   },
   "rifleFire": {
    "files": [
     "rifleFire-3-8ed56841.m4a",
     "rifleFire-2-a850ad83.m4a"
    ],
    "gain": 1
   },
   "rifleReload": {
    "files": [
     "rifleReload-2-1ad54372.m4a",
     "rifleReload-3-20027167.m4a"
    ],
    "gain": 1
   },
   "weaponSwap": {
    "files": [
     "weaponSwap-3-fbe81018.m4a"
    ],
    "gain": 1
   },
   "footstep-litter": {
    "files": [
     "footstep-litter-1-fe9cd8d9.m4a",
     "footstep-litter-3-09ceed7a.m4a"
    ],
    "gain": 1
   },
   "footstep-planks": {
    "files": [
     "footstep-planks-3-d919e436.m4a",
     "footstep-planks-2-ebb5a80c.m4a"
    ],
    "gain": 1
   },
   "footstep-sand": {
    "files": [
     "footstep-sand-2-4b40473a.m4a",
     "footstep-sand-1-09a40a2f.m4a"
    ],
    "gain": 1
   },
   "land": {
    "files": [
     "land-2-773487f2.m4a",
     "land-3-eebff605.m4a"
    ],
    "gain": 1
   },
   "land-hard": {
    "files": [
     "land-hard-3-5aed2a6b.m4a",
     "land-hard-1-2ce640be.m4a"
    ],
    "gain": 1
   },
   "splash": {
    "files": [
     "splash-3-9509efbe.m4a",
     "splash-2-03ab63ae.m4a"
    ],
    "gain": 1
   },
   "wadeStep": {
    "files": [
     "wadeStep-1-83e1423c.m4a",
     "wadeStep-2-402e850a.m4a"
    ],
    "gain": 1
   },
   "swimStroke": {
    "files": [
     "swimStroke-2-9e35721b.m4a"
    ],
    "gain": 1
   },
   "waterExit": {
    "files": [
     "waterExit-1-d85f0e47.m4a"
    ],
    "gain": 1
   },
   "dive": {
    "files": [
     "dive-1-4b978224.m4a",
     "dive-3-e74abc72.m4a"
    ],
    "gain": 1
   },
   "surface": {
    "files": [
     "surface-3-85550528.m4a",
     "surface-2-e5ac4e8a.m4a"
    ],
    "gain": 1
   },
   "hitMarker": {
    "files": [
     "hitMarker-1-46ef1236.m4a"
    ],
    "gain": 1
   },
   "kill": {
    "files": [
     "kill-3-5f7ea225.m4a",
     "kill-2-5e4acc1b.m4a"
    ],
    "gain": 1
   },
   "gull": {
    "files": [
     "gull-1-5fa9130b.m4a"
    ],
    "gain": 1
   },
   "deer_call": {
    "files": [
     "deer_call-3-1d601bb4.m4a",
     "deer_call-1-7cd35867.m4a"
    ],
    "gain": 1
   },
   "boar_grunt": {
    "files": [
     "boar_grunt-3-4e4a9bec.m4a"
    ],
    "gain": 1
   },
   "hoofsteps": {
    "files": [
     "hoofsteps-3-f1c11f8f.m4a",
     "hoofsteps-1-9580d36a.m4a"
    ],
    "gain": 1
   },
   "boar_squeal": {
    "files": [
     "boar_squeal-1-804df37c.m4a"
    ],
    "gain": 1
   },
   "elk_bugle": {
    "files": [
     "elk_bugle-3-f6e8030e.m4a",
     "elk_bugle-2-0e80875f.m4a"
    ],
    "gain": 1
   },
   "bear_growl": {
    "files": [
     "bear_growl-3-f91d7740.m4a"
    ],
    "gain": 1
   },
   "bear_roar": {
    "files": [
     "bear_roar-3-9f1e177e.m4a",
     "bear_roar-2-29e3055e.m4a"
    ],
    "gain": 1
   },
   "bear_hurt": {
    "files": [
     "bear_hurt-1-43b45d1e.m4a",
     "bear_hurt-3-3aea6172.m4a"
    ],
    "gain": 1
   },
   "crab_click": {
    "files": [
     "crab_click-2-aefbc41d.m4a",
     "crab_click-3-f47e95a3.m4a"
    ],
    "gain": 1
   },
   "crab_snap": {
    "files": [
     "crab_snap-2-bff601ad.m4a",
     "crab_snap-3-69ea11c0.m4a"
    ],
    "gain": 1
   },
   "monkey_chatter": {
    "files": [
     "monkey_chatter-3-1c7d7e2d.m4a"
    ],
    "gain": 1
   },
   "monkey_shriek": {
    "files": [
     "monkey_shriek-2-54acd647.m4a",
     "monkey_shriek-1-1a358b4e.m4a"
    ],
    "gain": 1
   },
   "sailor_groan": {
    "files": [
     "sailor_groan-2-43e2a981.m4a"
    ],
    "gain": 1
   },
   "sailor_slash": {
    "files": [
     "sailor_slash-3-5a10eada.m4a",
     "sailor_slash-1-611ba654.m4a"
    ],
    "gain": 1
   },
   "coconut_hit": {
    "files": [
     "coconut_hit-3-9c8e8fd7.m4a",
     "coconut_hit-2-83ed831d.m4a"
    ],
    "gain": 1
   },
   "coconut_land": {
    "files": [
     "coconut_land-1-42389b0a.m4a"
    ],
    "gain": 1
   },
   "wolf_howl": {
    "files": [
     "wolf_howl-3-b1d62e56.m4a",
     "wolf_howl-1-9f1204b6.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "wolf_snarl": {
    "files": [
     "wolf_snarl-1-cbccb5ca.m4a",
     "wolf_snarl-2-14ee8a80.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "wolf_bite": {
    "files": [
     "wolf_bite-1-a7669147.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "wolf_yip": {
    "files": [
     "wolf_yip-3-57734ee6.m4a",
     "wolf_yip-1-916cfc1c.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "wolf_yelp": {
    "files": [
     "wolf_yelp-3-0b926af1.m4a",
     "wolf_yelp-1-0a654844.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "horse_neigh": {
    "files": [
     "horse_neigh-1-2d461ec9.m4a",
     "horse_neigh-3-0fb050e4.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "horse_snort": {
    "files": [
     "horse_snort-3-71c7762c.m4a",
     "horse_snort-1-e17c9310.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "horse_squeal": {
    "files": [
     "horse_squeal-2-deba46fc.m4a",
     "horse_squeal-3-d3ec1b12.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "dog_bark": {
    "files": [
     "dog_bark-1-b5697b0b.m4a",
     "dog_bark-2-b970e2be.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "dog_yelp": {
    "files": [
     "dog_yelp-1-3c70e498.m4a",
     "dog_yelp-3-ff2849fb.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "sheep_bleat": {
    "files": [
     "sheep_bleat-1-e8ac7f93.m4a",
     "sheep_bleat-3-aeefea06.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "marmot_whistle": {
    "files": [
     "marmot_whistle-1-b7eecab8.m4a",
     "marmot_whistle-3-cb2183cf.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "eagle_cry": {
    "files": [
     "eagle_cry-3-4fc31339.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "leopard_growl": {
    "files": [
     "leopard_growl-3-35bd3b8b.m4a",
     "leopard_growl-2-d3af9bac.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "king_call": {
    "files": [
     "king_call-2-be937d44.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "king_hurt": {
    "files": [
     "king_hurt-3-170faca9.m4a",
     "king_hurt-2-af879fbf.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "hoof-grass": {
    "files": [
     "hoof-grass-2-5f364e1d.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "hoof-gravel": {
    "files": [
     "hoof-gravel-1-44e6b20f.m4a",
     "hoof-gravel-2-ee23d114.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "hoof-wood": {
    "files": [
     "hoof-wood-1-90597c92.m4a",
     "hoof-wood-2-b5f90eb8.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "stampede": {
    "files": [
     "stampede-2-17664d37.m4a",
     "stampede-1-2e9f5914.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "footstep-grass": {
    "files": [
     "footstep-grass-2-5a248407.m4a",
     "footstep-grass-1-12997b46.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "footstep-gravel": {
    "files": [
     "footstep-gravel-2-fd612069.m4a",
     "footstep-gravel-1-19e4eea2.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "bowDraw": {
    "files": [
     "bowDraw-3-c29c9c43.m4a",
     "bowDraw-2-a565b317.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "bowFullDraw": {
    "files": [
     "bowFullDraw-2-ee0e4dd9.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "bowLetDown": {
    "files": [
     "bowLetDown-2-06e19a6d.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "bowTwang": {
    "files": [
     "bowTwang-2-04acbe73.m4a",
     "bowTwang-1-66536b93.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "arrowWhoosh": {
    "files": [
     "arrowWhoosh-2-3792e59f.m4a",
     "arrowWhoosh-1-a831cab6.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "arrowImpact-wood": {
    "files": [
     "arrowImpact-wood-2-b5a11d70.m4a",
     "arrowImpact-wood-3-6940161f.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "arrowImpact-ground": {
    "files": [
     "arrowImpact-ground-2-a04ed94d.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "arrowImpact-flesh": {
    "files": [
     "arrowImpact-flesh-3-a82fa369.m4a",
     "arrowImpact-flesh-2-bb61e810.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "sabreSwing": {
    "files": [
     "sabreSwing-1-ae5a26f0.m4a",
     "sabreSwing-2-02d47131.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "sabreHit-flesh": {
    "files": [
     "sabreHit-flesh-3-762ce5fc.m4a",
     "sabreHit-flesh-2-e6417bf6.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "sabreHit-wood": {
    "files": [
     "sabreHit-wood-2-a5b2f0b1.m4a",
     "sabreHit-wood-1-e4853660.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "javelinThrow": {
    "files": [
     "javelinThrow-2-0cb3c85f.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "javelinImpact-wood": {
    "files": [
     "javelinImpact-wood-1-1d56a392.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "javelinImpact-ground": {
    "files": [
     "javelinImpact-ground-1-30313064.m4a",
     "javelinImpact-ground-3-8ebe2f3b.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "thunder-near": {
    "files": [
     "thunder-near-1-25a8635e.m4a",
     "thunder-near-2-63591c82.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "thunder-far": {
    "files": [
     "thunder-far-1-615a697f.m4a",
     "thunder-far-3-a9a4b0c0.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "lightningCrackle": {
    "files": [
     "lightningCrackle-1-38ea4f51.m4a",
     "lightningCrackle-2-f39ea4ea.m4a"
    ],
    "gain": 1,
    "shard": "nalati"
   },
   "footstep-mud": {
    "files": [
     "footstep-mud-2-99e4a10d.m4a",
     "footstep-mud-1-1dd22736.m4a"
    ],
    "gain": 1
   },
   "footstep-rock": {
    "files": [
     "footstep-rock-2-58c2cc26.m4a",
     "footstep-rock-3-98e0e874.m4a"
    ],
    "gain": 1
   },
   "footstep-wet": {
    "files": [
     "footstep-wet-1-58d313a2.m4a"
    ],
    "gain": 1
   }
  }
 },
 "pine-hollow": {
  "model": "MOSS-SoundEffect v2 + Stable Audio 3 Medium",
  "credit": "Sound effects: MOSS-SoundEffect v2 · Stable Audio 3 Medium — Powered by Stability AI",
  "licence": "Per file (see provenance.source): MOSS-SoundEffect v2.0 is Apache-2.0; Stable Audio 3 Medium is the Stability AI Community License (free below USD 1M revenue, register with Stability AI for commercial use, show 'Powered by Stability AI').",
  "set": "pine-hollow",
  "beds": {
   "hollow": {
    "file": "bed-hollow-1-17c54253.m4a",
    "loopStart": 2.25,
    "loopEnd": 17.25,
    "duration": 18.26,
    "gain": 0.5,
    "zone": "hollow",
    "live": true
   },
   "pond": {
    "file": "bed-pond-1-d085e52c.m4a",
    "loopStart": 9,
    "loopEnd": 21,
    "duration": 22.016,
    "gain": 0.5,
    "zone": "pond",
    "live": true
   },
   "cabin": {
    "file": "bed-cabin-2-c2b7a02b.m4a",
    "loopStart": 10.25,
    "loopEnd": 18.25,
    "duration": 19.264,
    "gain": 0.5,
    "zone": "cabin",
    "live": true
   },
   "creek": {
    "file": "bed-creek-1-e1414cd8.m4a",
    "loopStart": 8,
    "loopEnd": 20,
    "duration": 21.0133,
    "gain": 0.5,
    "zone": "creek",
    "live": false
   },
   "waterfall": {
    "file": "bed-waterfall-1-02ff171d.m4a",
    "loopStart": 10.5,
    "loopEnd": 18.5,
    "duration": 19.52,
    "gain": 0.5,
    "zone": "waterfall",
    "live": false
   },
   "mill": {
    "file": "bed-mill-3-a20c4c53.m4a",
    "loopStart": 2,
    "loopEnd": 14,
    "duration": 15.0187,
    "gain": 0.5,
    "zone": "mill",
    "live": false
   },
   "ridge": {
    "file": "bed-ridge-1-6aecf680.m4a",
    "loopStart": 6.25,
    "loopEnd": 17.25,
    "duration": 18.26,
    "gain": 0.5,
    "zone": "ridge",
    "live": false
   },
   "oldgrowth": {
    "file": "bed-oldgrowth-3-abf1ab68.m4a",
    "loopStart": 11.75,
    "loopEnd": 22.75,
    "duration": 23.764,
    "gain": 0.5,
    "zone": "oldgrowth",
    "live": false
   },
   "cave": {
    "file": "bed-cave-1-9f212e8f.m4a",
    "loopStart": 10.75,
    "loopEnd": 22.75,
    "duration": 23.764,
    "gain": 0.5,
    "zone": "cave",
    "live": false
   },
   "night": {
    "file": "bed-night-1-bb291c08.m4a",
    "loopStart": 9.25,
    "loopEnd": 19.25,
    "duration": 20.2667,
    "gain": 0.5,
    "zone": "night",
    "live": false
   },
   "nightfog": {
    "file": "bed-nightfog-1-7e88dd54.m4a",
    "loopStart": 2,
    "loopEnd": 18,
    "duration": 19.008,
    "gain": 0.5,
    "zone": "night",
    "live": false
   },
   "rain-canopy": {
    "file": "bed-rain-canopy-3-b1ccc4c3.m4a",
    "loopStart": 4,
    "loopEnd": 18,
    "duration": 19.008,
    "gain": 0.5,
    "zone": "rain",
    "live": false
   },
   "rain-open": {
    "file": "bed-rain-open-1-6035278a.m4a",
    "loopStart": 11,
    "loopEnd": 19,
    "duration": 20.0093,
    "gain": 0.5,
    "zone": "rain",
    "live": false
   },
   "dawn": {
    "file": "bed-dawn-2-27bd5ac4.m4a",
    "loopStart": 9.25,
    "loopEnd": 24.25,
    "duration": 25.2573,
    "gain": 0.5,
    "zone": "dawn",
    "live": false
   }
  },
  "hums": {},
  "oneshots": {
   "deer_snort": {
    "files": [
     "deer_snort-2-29cb5be9.m4a"
    ],
    "gain": 1
   },
   "leverCycle": {
    "files": [
     "leverCycle-1-0bc0a070.m4a",
     "leverCycle-3-db4d61a3.m4a"
    ],
    "gain": 1
   },
   "leverShot": {
    "files": [
     "leverShot-1-f43899bf.m4a",
     "leverShot-3-551ac455.m4a"
    ],
    "gain": 1
   },
   "leverEcho": {
    "files": [
     "leverEcho-3-31387108.m4a"
    ],
    "gain": 1
   },
   "longbowDraw": {
    "files": [
     "longbowDraw-2-08004dc6.m4a",
     "longbowDraw-3-13c08903.m4a"
    ],
    "gain": 1
   },
   "thrall_call": {
    "files": [
     "thrall_call-1-d9d16a02.m4a",
     "thrall_call-3-f6736e19.m4a"
    ],
    "gain": 1
   },
   "thrall_groan": {
    "files": [
     "thrall_groan-2-44c87d6d.m4a",
     "thrall_groan-3-7fad18a9.m4a"
    ],
    "gain": 1
   },
   "thrall_move": {
    "files": [
     "thrall_move-2-000b58d3.m4a",
     "thrall_move-3-fbb0b7a0.m4a"
    ],
    "gain": 1
   },
   "king_bells": {
    "files": [
     "king_bells-3-382976e6.m4a"
    ],
    "gain": 1
   },
   "king_stomp": {
    "files": [
     "king_stomp-2-fb8d3696.m4a",
     "king_stomp-3-fbcd79cf.m4a"
    ],
    "gain": 1
   },
   "king_roar": {
    "files": [
     "king_roar-2-3c879291.m4a",
     "king_roar-3-ac03b790.m4a"
    ],
    "gain": 1
   },
   "doorOpen": {
    "files": [
     "doorOpen-1-c289151d.m4a"
    ],
    "gain": 1
   },
   "doorClose": {
    "files": [
     "doorClose-3-6e783142.m4a",
     "doorClose-2-93812e54.m4a"
    ],
    "gain": 1
   },
   "lanternLight": {
    "files": [
     "lanternLight-1-864cd94b.m4a",
     "lanternLight-2-45776ffa.m4a"
    ],
    "gain": 1
   },
   "lanternCreak": {
    "files": [
     "lanternCreak-1-6d38d61d.m4a",
     "lanternCreak-3-b84fd75d.m4a"
    ],
    "gain": 1
   },
   "zipline": {
    "files": [
     "zipline-3-1612a3d1.m4a",
     "zipline-1-894e055e.m4a"
    ],
    "gain": 1
   },
   "bark-ranger-1": {
    "files": [
     "bark-ranger-1-3-b757c6a1.m4a"
    ],
    "gain": 1
   },
   "bark-ranger-3": {
    "files": [
     "bark-ranger-3-2-b0fc9905.m4a"
    ],
    "gain": 1
   },
   "bark-ranger-4": {
    "files": [
     "bark-ranger-4-1-87281e9a.m4a"
    ],
    "gain": 1
   },
   "bark-ranger-5": {
    "files": [
     "bark-ranger-5-2-02a65c3e.m4a",
     "bark-ranger-5-3-27302687.m4a"
    ],
    "gain": 1
   },
   "bark-ranger-7": {
    "files": [
     "bark-ranger-7-3-8b66382d.m4a",
     "bark-ranger-7-1-8b4552d2.m4a"
    ],
    "gain": 1
   },
   "bark-ranger-8": {
    "files": [
     "bark-ranger-8-1-6d92f66c.m4a",
     "bark-ranger-8-3-07112504.m4a"
    ],
    "gain": 1
   },
   "bark-miller-1": {
    "files": [
     "bark-miller-1-2-0db388d1.m4a",
     "bark-miller-1-1-e3db8e1d.m4a"
    ],
    "gain": 1
   },
   "bark-miller-2": {
    "files": [
     "bark-miller-2-1-b3ab2d49.m4a",
     "bark-miller-2-3-46ae62f9.m4a"
    ],
    "gain": 1
   },
   "bark-miller-3": {
    "files": [
     "bark-miller-3-3-bdc8c199.m4a",
     "bark-miller-3-2-b7c218bf.m4a"
    ],
    "gain": 1
   },
   "bark-miller-4": {
    "files": [
     "bark-miller-4-1-1b867b1c.m4a",
     "bark-miller-4-2-8bf90b08.m4a"
    ],
    "gain": 1
   },
   "bark-miller-6": {
    "files": [
     "bark-miller-6-2-ca606f6a.m4a",
     "bark-miller-6-1-24d91e2e.m4a"
    ],
    "gain": 1
   },
   "bark-miller-7": {
    "files": [
     "bark-miller-7-3-a8c4238e.m4a"
    ],
    "gain": 1
   },
   "bark-miller-8": {
    "files": [
     "bark-miller-8-3-b396019d.m4a"
    ],
    "gain": 1
   },
   "bark-trader-1": {
    "files": [
     "bark-trader-1-2-11e0f6b3.m4a",
     "bark-trader-1-3-1f1d6562.m4a"
    ],
    "gain": 1
   },
   "bark-trader-2": {
    "files": [
     "bark-trader-2-1-8ac027ef.m4a",
     "bark-trader-2-2-9b5ec2d9.m4a"
    ],
    "gain": 1
   },
   "bark-trader-3": {
    "files": [
     "bark-trader-3-2-d71e3d35.m4a",
     "bark-trader-3-1-928354ac.m4a"
    ],
    "gain": 1
   },
   "bark-trader-4": {
    "files": [
     "bark-trader-4-3-ecc68b8e.m4a",
     "bark-trader-4-1-2e7e09c3.m4a"
    ],
    "gain": 1
   },
   "bark-trader-5": {
    "files": [
     "bark-trader-5-1-f6ad16fb.m4a",
     "bark-trader-5-2-5344dcfa.m4a"
    ],
    "gain": 1
   },
   "bark-trader-6": {
    "files": [
     "bark-trader-6-3-f29e1de3.m4a"
    ],
    "gain": 1
   },
   "bark-trader-7": {
    "files": [
     "bark-trader-7-2-5746d56d.m4a"
    ],
    "gain": 1
   },
   "bark-trader-8": {
    "files": [
     "bark-trader-8-3-43cd6fcd.m4a",
     "bark-trader-8-2-aebeb467.m4a"
    ],
    "gain": 1
   },
   "boltImpact-rock": {
    "files": [
     "boltImpact-rock-5-8817d8c7.m4a",
     "boltImpact-rock-3-91f80620.m4a"
    ],
    "gain": 1
   },
   "longbowLoose": {
    "files": [
     "longbowLoose-4-aaeb804d.m4a"
    ],
    "gain": 1
   },
   "raven_caw": {
    "files": [
     "raven_caw-4-29cdf0f3.m4a",
     "raven_caw-6-23989150.m4a"
    ],
    "gain": 1
   },
   "raven_pair": {
    "files": [
     "raven_pair-1-f8070ef6.m4a",
     "raven_pair-2-d6566778.m4a"
    ],
    "gain": 1
   },
   "raven_flap": {
    "files": [
     "raven_flap-3-d8de68a0.m4a",
     "raven_flap-1-ef724c18.m4a"
    ],
    "gain": 1
   },
   "owl_hoot": {
    "files": [
     "owl_hoot-3-cdbe93cd.m4a",
     "owl_hoot-1-805b5cfa.m4a"
    ],
    "gain": 1
   },
   "woodpecker_drum": {
    "files": [
     "woodpecker_drum-1-6125f4ba.m4a",
     "woodpecker_drum-2-1ce56686.m4a"
    ],
    "gain": 1
   },
   "woodpecker_call": {
    "files": [
     "woodpecker_call-3-caf7f9bc.m4a",
     "woodpecker_call-1-82e24909.m4a"
    ],
    "gain": 1
   },
   "skinCut-a": {
    "files": [
     "skinCut-a-1-a68e8922.m4a",
     "skinCut-a-2-22d9c5b6.m4a"
    ],
    "gain": 1
   },
   "skinCut-b": {
    "files": [
     "skinCut-b-3-f5ea4aeb.m4a",
     "skinCut-b-1-63445de8.m4a"
    ],
    "gain": 1
   },
   "leverDry": {
    "files": [
     "leverDry-2-6fc79d84.m4a",
     "leverDry-3-4d807418.m4a"
    ],
    "gain": 1
   },
   "leverRoundIn": {
    "files": [
     "leverRoundIn-3-c42635c5.m4a",
     "leverRoundIn-1-ad1c3d11.m4a"
    ],
    "gain": 1
   }
  },
  "sprite": {
   "file": "oneshots-2e703ba3.m4a",
   "gap": 0.2,
   "duration": 162.036,
   "clips": {
    "deer_snort-2-29cb5be9.m4a": [
     0.2,
     1.5
    ],
    "leverCycle-1-0bc0a070.m4a": [
     1.9,
     0.596437
    ],
    "leverCycle-3-db4d61a3.m4a": [
     2.696438,
     0.977208
    ],
    "leverShot-1-f43899bf.m4a": [
     3.873646,
     1.945833
    ],
    "leverShot-3-551ac455.m4a": [
     6.019479,
     1.390458
    ],
    "leverEcho-3-31387108.m4a": [
     7.609938,
     3
    ],
    "longbowDraw-2-08004dc6.m4a": [
     10.809938,
     1.5
    ],
    "longbowDraw-3-13c08903.m4a": [
     12.509937,
     1.5
    ],
    "thrall_call-1-d9d16a02.m4a": [
     14.209938,
     3.005
    ],
    "thrall_call-3-f6736e19.m4a": [
     17.414938,
     3.005
    ],
    "thrall_groan-2-44c87d6d.m4a": [
     20.619937,
     2.407354
    ],
    "thrall_groan-3-7fad18a9.m4a": [
     23.227292,
     2.447062
    ],
    "thrall_move-2-000b58d3.m4a": [
     25.874354,
     2.418771
    ],
    "thrall_move-3-fbb0b7a0.m4a": [
     28.493125,
     2.5
    ],
    "king_bells-3-382976e6.m4a": [
     31.193125,
     3
    ],
    "king_stomp-2-fb8d3696.m4a": [
     34.393125,
     2.691146
    ],
    "king_stomp-3-fbcd79cf.m4a": [
     37.284271,
     2.458542
    ],
    "king_roar-2-3c879291.m4a": [
     39.942813,
     3.005
    ],
    "king_roar-3-ac03b790.m4a": [
     43.147813,
     3.005
    ],
    "doorOpen-1-c289151d.m4a": [
     46.352812,
     1.596958
    ],
    "doorClose-3-6e783142.m4a": [
     48.149771,
     1.307708
    ],
    "doorClose-2-93812e54.m4a": [
     49.657479,
     1.379813
    ],
    "lanternLight-1-864cd94b.m4a": [
     51.237292,
     1.879583
    ],
    "lanternLight-2-45776ffa.m4a": [
     53.316875,
     1.089063
    ],
    "lanternCreak-1-6d38d61d.m4a": [
     54.605938,
     3
    ],
    "lanternCreak-3-b84fd75d.m4a": [
     57.805937,
     3
    ],
    "zipline-3-1612a3d1.m4a": [
     61.005938,
     3
    ],
    "zipline-1-894e055e.m4a": [
     64.205938,
     3.005
    ],
    "bark-ranger-1-3-b757c6a1.m4a": [
     67.410938,
     1.457729
    ],
    "bark-ranger-3-2-b0fc9905.m4a": [
     69.068667,
     1.423646
    ],
    "bark-ranger-4-1-87281e9a.m4a": [
     70.692312,
     1.448917
    ],
    "bark-ranger-5-2-02a65c3e.m4a": [
     72.341229,
     1.699667
    ],
    "bark-ranger-5-3-27302687.m4a": [
     74.240896,
     1.599938
    ],
    "bark-ranger-7-3-8b66382d.m4a": [
     76.040833,
     1.468167
    ],
    "bark-ranger-7-1-8b4552d2.m4a": [
     77.709,
     1.417521
    ],
    "bark-ranger-8-1-6d92f66c.m4a": [
     79.326521,
     1.4175
    ],
    "bark-ranger-8-3-07112504.m4a": [
     80.944021,
     1.205208
    ],
    "bark-miller-1-2-0db388d1.m4a": [
     82.349229,
     1.449104
    ],
    "bark-miller-1-1-e3db8e1d.m4a": [
     83.998333,
     1.420375
    ],
    "bark-miller-2-1-b3ab2d49.m4a": [
     85.618708,
     1.382562
    ],
    "bark-miller-2-3-46ae62f9.m4a": [
     87.201271,
     1.409687
    ],
    "bark-miller-3-3-bdc8c199.m4a": [
     88.810958,
     1.353208
    ],
    "bark-miller-3-2-b7c218bf.m4a": [
     90.364167,
     1.408292
    ],
    "bark-miller-4-1-1b867b1c.m4a": [
     91.972458,
     1.449458
    ],
    "bark-miller-4-2-8bf90b08.m4a": [
     93.621917,
     1.416313
    ],
    "bark-miller-6-2-ca606f6a.m4a": [
     95.238229,
     1.274854
    ],
    "bark-miller-6-1-24d91e2e.m4a": [
     96.713083,
     1.162688
    ],
    "bark-miller-7-3-a8c4238e.m4a": [
     98.075771,
     1.458458
    ],
    "bark-miller-8-3-b396019d.m4a": [
     99.734229,
     1.416521
    ],
    "bark-trader-1-2-11e0f6b3.m4a": [
     101.35075,
     0.886021
    ],
    "bark-trader-1-3-1f1d6562.m4a": [
     102.436771,
     1.457062
    ],
    "bark-trader-2-1-8ac027ef.m4a": [
     104.093833,
     1.235125
    ],
    "bark-trader-2-2-9b5ec2d9.m4a": [
     105.528958,
     1.214771
    ],
    "bark-trader-3-2-d71e3d35.m4a": [
     106.943729,
     1.485667
    ],
    "bark-trader-3-1-928354ac.m4a": [
     108.629396,
     1.466958
    ],
    "bark-trader-4-3-ecc68b8e.m4a": [
     110.296354,
     1.088188
    ],
    "bark-trader-4-1-2e7e09c3.m4a": [
     111.584542,
     1.235313
    ],
    "bark-trader-5-1-f6ad16fb.m4a": [
     113.019854,
     1.487979
    ],
    "bark-trader-5-2-5344dcfa.m4a": [
     114.707833,
     1.463667
    ],
    "bark-trader-6-3-f29e1de3.m4a": [
     116.3715,
     1.476063
    ],
    "bark-trader-7-2-5746d56d.m4a": [
     118.047562,
     0.973938
    ],
    "bark-trader-8-3-43cd6fcd.m4a": [
     119.2215,
     1.423667
    ],
    "bark-trader-8-2-aebeb467.m4a": [
     120.845167,
     1.486312
    ],
    "boltImpact-rock-5-8817d8c7.m4a": [
     122.531479,
     0.825042
    ],
    "boltImpact-rock-3-91f80620.m4a": [
     123.556521,
     0.682667
    ],
    "longbowLoose-4-aaeb804d.m4a": [
     124.439188,
     1.103875
    ],
    "raven_caw-4-29cdf0f3.m4a": [
     125.743062,
     1.5
    ],
    "raven_caw-6-23989150.m4a": [
     127.443062,
     1.374333
    ],
    "raven_pair-1-f8070ef6.m4a": [
     129.017396,
     2.834
    ],
    "raven_pair-2-d6566778.m4a": [
     132.051396,
     2.896604
    ],
    "raven_flap-3-d8de68a0.m4a": [
     135.148,
     1.649917
    ],
    "raven_flap-1-ef724c18.m4a": [
     136.997917,
     1.621458
    ],
    "owl_hoot-3-cdbe93cd.m4a": [
     138.819375,
     3
    ],
    "owl_hoot-1-805b5cfa.m4a": [
     142.019375,
     3
    ],
    "woodpecker_drum-1-6125f4ba.m4a": [
     145.219375,
     2
    ],
    "woodpecker_drum-2-1ce56686.m4a": [
     147.419375,
     2
    ],
    "woodpecker_call-3-caf7f9bc.m4a": [
     149.619375,
     2.500021
    ],
    "woodpecker_call-1-82e24909.m4a": [
     152.319396,
     2.500021
    ],
    "skinCut-a-1-a68e8922.m4a": [
     155.019417,
     0.2935
    ],
    "skinCut-a-2-22d9c5b6.m4a": [
     155.512917,
     1
    ],
    "skinCut-b-3-f5ea4aeb.m4a": [
     156.712917,
     0.842458
    ],
    "skinCut-b-1-63445de8.m4a": [
     157.755375,
     0.933021
    ],
    "leverDry-2-6fc79d84.m4a": [
     158.888396,
     0.679146
    ],
    "leverDry-3-4d807418.m4a": [
     159.767542,
     0.589083
    ],
    "leverRoundIn-3-c42635c5.m4a": [
     160.556625,
     0.516312
    ],
    "leverRoundIn-1-ad1c3d11.m4a": [
     161.272938,
     0.563625
    ]
   }
  }
 }
};
