// generated by vite.config.ts from public/assets/music/*/music.json and public/assets/sfx/*/sfx.json — do not edit.
export const MUSIC_MANIFESTS: Readonly<Record<string, unknown>> = {
 "folk": {
  "style": "folk",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "pine": {
    "calm": "pine-calm-10905c79.m4a",
    "tension": "pine-tension-180bc197.m4a",
    "bpm": 86.403,
    "beatsPerBar": 4,
    "loopStart": 25.542,
    "loopEnd": 69.9849,
    "duration": 72.768
   },
   "island": {
    "calm": "island-calm-d7d189f9.m4a",
    "tension": "island-tension-bb05ab64.m4a",
    "bpm": 85.186,
    "beatsPerBar": 4,
    "loopStart": 16.9738,
    "loopEnd": 42.33,
    "duration": 45.1627
   },
   "title": {
    "full": "title-50001128.m4a",
    "bpm": 104.908,
    "beatsPerBar": 4,
    "loopStart": 15.6735,
    "loopEnd": 63.7156,
    "duration": 66.0053
   }
  },
  "stings": {
   "death": "sting-death-67f54fe8.m4a",
   "chunk": "sting-chunk-31c10eaf.m4a",
   "pickup": "sting-pickup-332f81db.m4a"
  }
 },
 "orchestral": {
  "style": "orchestral",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "pine": {
    "calm": "pine-calm-fbc4a99e.m4a",
    "tension": "pine-tension-525d8c6d.m4a",
    "bpm": 95.925,
    "beatsPerBar": 4,
    "loopStart": 22.384,
    "loopEnd": 42.3996,
    "duration": 44.9067
   },
   "island": {
    "calm": "island-calm-27861d1b.m4a",
    "tension": "island-tension-73116f36.m4a",
    "bpm": 86.299,
    "beatsPerBar": 4,
    "loopStart": 16.1611,
    "loopEnd": 52.3146,
    "duration": 55.104
   },
   "title": {
    "full": "title-b47c8a52.m4a",
    "bpm": 116.041,
    "beatsPerBar": 4,
    "loopStart": 14.7911,
    "loopEnd": 43.7464,
    "duration": 45.824
   }
  },
  "stings": {
   "death": "sting-death-771d34f7.m4a",
   "chunk": "sting-chunk-a639b19e.m4a",
   "pickup": "sting-pickup-65f7ac5b.m4a"
  }
 },
 "piano": {
  "style": "piano",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "pine": {
    "calm": "pine-calm-923e0056.m4a",
    "tension": "pine-tension-cc014e5b.m4a",
    "bpm": 91.998,
    "beatsPerBar": 4,
    "loopStart": 6.757,
    "loopEnd": 58.9322,
    "duration": 61.5467
   },
   "island": {
    "calm": "island-calm-05125ed8.m4a",
    "tension": "island-tension-7faf0468.m4a",
    "bpm": 76.781,
    "beatsPerBar": 4,
    "loopStart": 14.3035,
    "loopEnd": 54.9384,
    "duration": 58.0693
   },
   "title": {
    "full": "title-3d1f713a.m4a",
    "bpm": 75.666,
    "beatsPerBar": 4,
    "loopStart": 27.3995,
    "loopEnd": 59.118,
    "duration": 62.2933
   }
  },
  "stings": {
   "death": "sting-death-99b071e0.m4a",
   "chunk": "sting-chunk-a4f2ffab.m4a",
   "pickup": "sting-pickup-6ed91318.m4a"
  }
 }
};
export const SFX_MANIFESTS: Readonly<Record<string, unknown>> = {
 "sa3": {
  "model": "Stable Audio 3 Small-SFX",
  "credit": "SFX: Stable Audio 3 Small-SFX — Powered by Stability AI",
  "beds": {
   "forest": {
    "file": "bed-forest-1-f0afc13d.m4a",
    "loopStart": 2.25,
    "loopEnd": 12.25,
    "duration": 13.2693,
    "gain": 0.5
   },
   "island": {
    "file": "bed-island-3-7ed8b52e.m4a",
    "loopStart": 9.75,
    "loopEnd": 25.75,
    "duration": 26.752,
    "gain": 0.5
   },
   "underwater": {
    "file": "bed-underwater-2-8f05913e.m4a",
    "loopStart": 9.5,
    "loopEnd": 21.5,
    "duration": 22.5067,
    "gain": 0.5
   }
  },
  "hums": {
   "pickup": {
    "file": "hum-pickup-1-fc8dbc35.m4a",
    "loopStart": 2.25,
    "loopEnd": 4.25,
    "duration": 5.2693,
    "gain": 0.35
   },
   "shrine": {
    "file": "hum-shrine-3-726f7f01.m4a",
    "loopStart": 5.5,
    "loopEnd": 10.5,
    "duration": 11.52,
    "gain": 0.6
   }
  },
  "oneshots": {
   "bear_growl": {
    "files": [
     "bear_growl-1-cfaad7d9.m4a",
     "bear_growl-3-17897b00.m4a"
    ],
    "gain": 1
   },
   "bear_hurt": {
    "files": [
     "bear_hurt-3-d20c9066.m4a"
    ],
    "gain": 1
   },
   "bear_roar": {
    "files": [
     "bear_roar-1-1675d7f9.m4a",
     "bear_roar-3-f50b18ee.m4a"
    ],
    "gain": 1
   },
   "boar_grunt": {
    "files": [
     "boar_grunt-3-2be4f58b.m4a",
     "boar_grunt-1-37e39535.m4a"
    ],
    "gain": 1
   },
   "boar_squeal": {
    "files": [
     "boar_squeal-1-02ee94b1.m4a"
    ],
    "gain": 1
   },
   "coconut_hit": {
    "files": [
     "coconut_hit-1-6480c3fa.m4a",
     "coconut_hit-3-a10de251.m4a"
    ],
    "gain": 1
   },
   "crab_snap": {
    "files": [
     "crab_snap-2-4f957d06.m4a"
    ],
    "gain": 1
   },
   "dodge": {
    "files": [
     "dodge-1-45e8fa4e.m4a",
     "dodge-2-ce3eac0f.m4a"
    ],
    "gain": 1
   },
   "dryFire": {
    "files": [
     "dryFire-2-039d37fc.m4a",
     "dryFire-1-817c2a64.m4a"
    ],
    "gain": 1
   },
   "elk_bugle": {
    "files": [
     "elk_bugle-2-38dd5647.m4a",
     "elk_bugle-1-24cf4ae3.m4a"
    ],
    "gain": 1
   },
   "hoofsteps": {
    "files": [
     "hoofsteps-2-c791fb45.m4a"
    ],
    "gain": 1
   },
   "kill": {
    "files": [
     "kill-1-0b938ad3.m4a"
    ],
    "gain": 1
   },
   "land-hard": {
    "files": [
     "land-hard-1-959fa190.m4a",
     "land-hard-3-59678f89.m4a"
    ],
    "gain": 1
   },
   "monkey_shriek": {
    "files": [
     "monkey_shriek-3-3d3fb221.m4a"
    ],
    "gain": 1
   },
   "reload": {
    "files": [
     "reload-2-90440f32.m4a",
     "reload-1-0e71d951.m4a"
    ],
    "gain": 1
   },
   "rifleFire": {
    "files": [
     "rifleFire-2-5543cbcc.m4a",
     "rifleFire-3-a12c28f1.m4a"
    ],
    "gain": 1
   },
   "rifleReload": {
    "files": [
     "rifleReload-2-edbc5734.m4a",
     "rifleReload-3-ca0b808b.m4a"
    ],
    "gain": 1
   },
   "swordHeavy": {
    "files": [
     "swordHeavy-2-c36c692d.m4a"
    ],
    "gain": 1
   },
   "swordSwing": {
    "files": [
     "swordSwing-1-8eb16019.m4a"
    ],
    "gain": 1
   },
   "weaponSwap": {
    "files": [
     "weaponSwap-3-eaafb6a5.m4a"
    ],
    "gain": 1
   }
  }
 },
 "sa3-medium": {
  "model": "Stable Audio 3 Medium",
  "credit": "SFX: Stable Audio 3 Medium — Powered by Stability AI",
  "beds": {
   "forest": {
    "file": "bed-forest-2-0cd11be5.m4a",
    "loopStart": 12.75,
    "loopEnd": 26.75,
    "duration": 27.7547,
    "gain": 0.5
   },
   "island": {
    "file": "bed-island-2-b56f8b01.m4a",
    "loopStart": 9,
    "loopEnd": 29,
    "duration": 30.016,
    "gain": 0.5
   },
   "underwater": {
    "file": "bed-underwater-3-cbe2810d.m4a",
    "loopStart": 9,
    "loopEnd": 21,
    "duration": 22.016,
    "gain": 0.5
   }
  },
  "hums": {
   "shrine": {
    "file": "hum-shrine-2-8b274f39.m4a",
    "loopStart": 4.25,
    "loopEnd": 6.25,
    "duration": 7.2533,
    "gain": 0.6
   }
  },
  "oneshots": {
   "bear_growl": {
    "files": [
     "bear_growl-3-d51162f5.m4a",
     "bear_growl-2-2384d717.m4a"
    ],
    "gain": 1
   },
   "bear_hurt": {
    "files": [
     "bear_hurt-2-e3decd9a.m4a",
     "bear_hurt-3-2e189d21.m4a"
    ],
    "gain": 1
   },
   "bear_roar": {
    "files": [
     "bear_roar-3-6e416479.m4a",
     "bear_roar-1-cdda7f3d.m4a"
    ],
    "gain": 1
   },
   "boar_grunt": {
    "files": [
     "boar_grunt-3-4e4a9bec.m4a"
    ],
    "gain": 1
   },
   "boar_squeal": {
    "files": [
     "boar_squeal-1-6415e380.m4a"
    ],
    "gain": 1
   },
   "boltImpact-flesh": {
    "files": [
     "boltImpact-flesh-1-91000a74.m4a",
     "boltImpact-flesh-3-99224c6c.m4a"
    ],
    "gain": 1
   },
   "boltImpact-ground": {
    "files": [
     "boltImpact-ground-2-c6623243.m4a",
     "boltImpact-ground-1-e51592f5.m4a"
    ],
    "gain": 1
   },
   "boltImpact-wood": {
    "files": [
     "boltImpact-wood-1-518c4568.m4a",
     "boltImpact-wood-2-8fdffc5d.m4a"
    ],
    "gain": 1
   },
   "coconut_hit": {
    "files": [
     "coconut_hit-1-25548225.m4a",
     "coconut_hit-3-f33c352d.m4a"
    ],
    "gain": 1
   },
   "coconut_land": {
    "files": [
     "coconut_land-2-a3e51bbb.m4a"
    ],
    "gain": 1
   },
   "crab_click": {
    "files": [
     "crab_click-2-aefbc41d.m4a",
     "crab_click-3-f47e95a3.m4a"
    ],
    "gain": 1
   },
   "crab_snap": {
    "files": [
     "crab_snap-2-bff601ad.m4a",
     "crab_snap-3-69ea11c0.m4a"
    ],
    "gain": 1
   },
   "crossbowFire": {
    "files": [
     "crossbowFire-1-40af4c48.m4a"
    ],
    "gain": 1
   },
   "deer_call": {
    "files": [
     "deer_call-1-e7e6c631.m4a"
    ],
    "gain": 1
   },
   "dive": {
    "files": [
     "dive-3-00913360.m4a",
     "dive-1-34a595a8.m4a"
    ],
    "gain": 1
   },
   "dodge": {
    "files": [
     "dodge-3-500357b6.m4a",
     "dodge-2-dc30a942.m4a"
    ],
    "gain": 1
   },
   "dryFire": {
    "files": [
     "dryFire-2-0755e765.m4a",
     "dryFire-1-8aafdf79.m4a"
    ],
    "gain": 1
   },
   "elk_bugle": {
    "files": [
     "elk_bugle-2-7048925b.m4a",
     "elk_bugle-1-375e7428.m4a"
    ],
    "gain": 1
   },
   "footstep-litter": {
    "files": [
     "footstep-litter-2-19b0df36.m4a",
     "footstep-litter-1-b1476674.m4a"
    ],
    "gain": 1
   },
   "footstep-planks": {
    "files": [
     "footstep-planks-2-0df42a23.m4a"
    ],
    "gain": 1
   },
   "footstep-sand": {
    "files": [
     "footstep-sand-2-4b40473a.m4a",
     "footstep-sand-1-09a40a2f.m4a"
    ],
    "gain": 1
   },
   "hitMarker": {
    "files": [
     "hitMarker-1-46ef1236.m4a"
    ],
    "gain": 1
   },
   "hoofsteps": {
    "files": [
     "hoofsteps-2-0b709888.m4a"
    ],
    "gain": 1
   },
   "kill": {
    "files": [
     "kill-3-5f7ea225.m4a",
     "kill-2-5e4acc1b.m4a"
    ],
    "gain": 1
   },
   "land": {
    "files": [
     "land-2-773487f2.m4a",
     "land-3-eebff605.m4a"
    ],
    "gain": 1
   },
   "land-hard": {
    "files": [
     "land-hard-2-6d3dd78c.m4a",
     "land-hard-1-2e7ed6b5.m4a"
    ],
    "gain": 1
   },
   "lunge": {
    "files": [
     "lunge-3-be45ba7a.m4a"
    ],
    "gain": 1
   },
   "monkey_chatter": {
    "files": [
     "monkey_chatter-1-db5ae27b.m4a"
    ],
    "gain": 1
   },
   "monkey_shriek": {
    "files": [
     "monkey_shriek-2-54acd647.m4a",
     "monkey_shriek-1-1a358b4e.m4a"
    ],
    "gain": 1
   },
   "reload": {
    "files": [
     "reload-1-4d6ccf59.m4a",
     "reload-2-a1799660.m4a"
    ],
    "gain": 1
   },
   "rifleFire": {
    "files": [
     "rifleFire-3-8ed56841.m4a",
     "rifleFire-2-a850ad83.m4a"
    ],
    "gain": 1
   },
   "rifleReload": {
    "files": [
     "rifleReload-2-1ad54372.m4a",
     "rifleReload-3-20027167.m4a"
    ],
    "gain": 1
   },
   "sailor_groan": {
    "files": [
     "sailor_groan-3-5398492d.m4a"
    ],
    "gain": 1
   },
   "sailor_slash": {
    "files": [
     "sailor_slash-2-ec93b9b6.m4a",
     "sailor_slash-3-4d01e059.m4a"
    ],
    "gain": 1
   },
   "surface": {
    "files": [
     "surface-3-b3341d88.m4a",
     "surface-2-320893c5.m4a"
    ],
    "gain": 1
   },
   "swordHeavy": {
    "files": [
     "swordHeavy-2-f7aaea0a.m4a",
     "swordHeavy-1-ef85d2f8.m4a"
    ],
    "gain": 1
   },
   "swordHit-flesh": {
    "files": [
     "swordHit-flesh-1-07225bb8.m4a",
     "swordHit-flesh-2-efbf5fd7.m4a"
    ],
    "gain": 1
   },
   "swordSwing": {
    "files": [
     "swordSwing-2-5c2aae32.m4a"
    ],
    "gain": 1
   },
   "wadeStep": {
    "files": [
     "wadeStep-2-8b85a652.m4a",
     "wadeStep-1-5699ba77.m4a"
    ],
    "gain": 1
   },
   "waterExit": {
    "files": [
     "waterExit-2-27aeb501.m4a"
    ],
    "gain": 1
   },
   "weaponSwap": {
    "files": [
     "weaponSwap-2-4aca394e.m4a",
     "weaponSwap-1-d9ab6f26.m4a"
    ],
    "gain": 1
   }
  }
 }
};
