// generated by vite.config.ts from public/assets/music/*/music.json and public/assets/sfx/*/sfx.json — do not edit.
export const MUSIC_MANIFESTS: Readonly<Record<string, unknown>> = {
 "folk": {
  "style": "folk",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "pine": {
    "calm": "pine-calm-10905c79.m4a",
    "tension": "pine-tension-180bc197.m4a",
    "bpm": 86.403,
    "beatsPerBar": 4,
    "loopStart": 25.542,
    "loopEnd": 69.9849,
    "duration": 72.768
   },
   "island": {
    "calm": "island-calm-d7d189f9.m4a",
    "tension": "island-tension-bb05ab64.m4a",
    "bpm": 85.186,
    "beatsPerBar": 4,
    "loopStart": 16.9738,
    "loopEnd": 42.33,
    "duration": 45.1627
   },
   "title": {
    "full": "title-50001128.m4a",
    "bpm": 104.908,
    "beatsPerBar": 4,
    "loopStart": 15.6735,
    "loopEnd": 63.7156,
    "duration": 66.0053
   }
  },
  "stings": {
   "death": "sting-death-67f54fe8.m4a",
   "chunk": "sting-chunk-31c10eaf.m4a",
   "pickup": "sting-pickup-332f81db.m4a"
  }
 },
 "orchestral": {
  "style": "orchestral",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "pine": {
    "calm": "pine-calm-fbc4a99e.m4a",
    "tension": "pine-tension-525d8c6d.m4a",
    "bpm": 95.925,
    "beatsPerBar": 4,
    "loopStart": 22.384,
    "loopEnd": 42.3996,
    "duration": 44.9067
   },
   "island": {
    "calm": "island-calm-27861d1b.m4a",
    "tension": "island-tension-73116f36.m4a",
    "bpm": 86.299,
    "beatsPerBar": 4,
    "loopStart": 16.1611,
    "loopEnd": 52.3146,
    "duration": 55.104
   },
   "title": {
    "full": "title-b47c8a52.m4a",
    "bpm": 116.041,
    "beatsPerBar": 4,
    "loopStart": 14.7911,
    "loopEnd": 43.7464,
    "duration": 45.824
   }
  },
  "stings": {
   "death": "sting-death-771d34f7.m4a",
   "chunk": "sting-chunk-a639b19e.m4a",
   "pickup": "sting-pickup-65f7ac5b.m4a"
  }
 },
 "piano": {
  "style": "piano",
  "model": "MiniMax-Music3",
  "credit": "Music: MiniMax-Music3",
  "slots": {
   "pine": {
    "calm": "pine-calm-923e0056.m4a",
    "tension": "pine-tension-cc014e5b.m4a",
    "bpm": 91.998,
    "beatsPerBar": 4,
    "loopStart": 6.757,
    "loopEnd": 58.9322,
    "duration": 61.5467
   },
   "island": {
    "calm": "island-calm-05125ed8.m4a",
    "tension": "island-tension-7faf0468.m4a",
    "bpm": 76.781,
    "beatsPerBar": 4,
    "loopStart": 14.3035,
    "loopEnd": 54.9384,
    "duration": 58.0693
   },
   "title": {
    "full": "title-3d1f713a.m4a",
    "bpm": 75.666,
    "beatsPerBar": 4,
    "loopStart": 27.3995,
    "loopEnd": 59.118,
    "duration": 62.2933
   }
  },
  "stings": {
   "death": "sting-death-99b071e0.m4a",
   "chunk": "sting-chunk-a4f2ffab.m4a",
   "pickup": "sting-pickup-6ed91318.m4a"
  }
 }
};
export const SFX_MANIFESTS: Readonly<Record<string, unknown>> = {
 "best": {
  "model": "MOSS-SoundEffect v2 + Stable Audio 3 Medium",
  "credit": "Sound effects: MOSS-SoundEffect v2 · Stable Audio 3 Medium — Powered by Stability AI",
  "licence": "Per file (see provenance.source): MOSS-SoundEffect v2.0 is Apache-2.0; Stable Audio 3 Medium is the Stability AI Community License (free below USD 1M revenue, register with Stability AI for commercial use, show 'Powered by Stability AI').",
  "beds": {
   "forest": {
    "file": "bed-forest-2-0cd11be5.m4a",
    "loopStart": 12.75,
    "loopEnd": 26.75,
    "duration": 27.7547,
    "gain": 0.5
   },
   "island": {
    "file": "bed-island-1-4611714d.m4a",
    "loopStart": 2.25,
    "loopEnd": 15.25,
    "duration": 16.256,
    "gain": 0.5
   },
   "underwater": {
    "file": "bed-underwater-3-cbe2810d.m4a",
    "loopStart": 9,
    "loopEnd": 21,
    "duration": 22.016,
    "gain": 0.5
   }
  },
  "hums": {
   "pickup": {
    "file": "hum-pickup-3-7b7db58f.m4a",
    "loopStart": 3.25,
    "loopEnd": 9.25,
    "duration": 10.2613,
    "gain": 0.35
   },
   "shrine": {
    "file": "hum-shrine-2-d89ed03a.m4a",
    "loopStart": 2.75,
    "loopEnd": 8.75,
    "duration": 9.7707,
    "gain": 0.6
   }
  },
  "oneshots": {
   "crossbowFire": {
    "files": [
     "crossbowFire-1-40af4c48.m4a"
    ],
    "gain": 1
   },
   "dryFire": {
    "files": [
     "dryFire-2-88071d1d.m4a",
     "dryFire-3-173415cb.m4a"
    ],
    "gain": 1
   },
   "boltImpact-wood": {
    "files": [
     "boltImpact-wood-1-2cae58f6.m4a",
     "boltImpact-wood-2-d803992d.m4a"
    ],
    "gain": 1
   },
   "boltImpact-ground": {
    "files": [
     "boltImpact-ground-2-c6623243.m4a",
     "boltImpact-ground-1-e51592f5.m4a"
    ],
    "gain": 1
   },
   "boltImpact-flesh": {
    "files": [
     "boltImpact-flesh-3-da30d4fb.m4a"
    ],
    "gain": 1
   },
   "swordSwing": {
    "files": [
     "swordSwing-1-6303fc5d.m4a"
    ],
    "gain": 1
   },
   "swordHeavy": {
    "files": [
     "swordHeavy-2-1debcc8f.m4a",
     "swordHeavy-3-1bed510f.m4a"
    ],
    "gain": 1
   },
   "swordHit-flesh": {
    "files": [
     "swordHit-flesh-1-07225bb8.m4a",
     "swordHit-flesh-2-efbf5fd7.m4a"
    ],
    "gain": 1
   },
   "swordHit-wood": {
    "files": [
     "swordHit-wood-3-6381cc6b.m4a",
     "swordHit-wood-2-800b6fe9.m4a"
    ],
    "gain": 1
   },
   "dodge": {
    "files": [
     "dodge-2-13887dd8.m4a",
     "dodge-3-453516f6.m4a"
    ],
    "gain": 1
   },
   "lunge": {
    "files": [
     "lunge-3-be45ba7a.m4a"
    ],
    "gain": 1
   },
   "reload": {
    "files": [
     "reload-2-c48de6a0.m4a",
     "reload-1-a220fb6e.m4a"
    ],
    "gain": 1
   },
   "rifleFire": {
    "files": [
     "rifleFire-3-8ed56841.m4a",
     "rifleFire-2-a850ad83.m4a"
    ],
    "gain": 1
   },
   "rifleReload": {
    "files": [
     "rifleReload-2-1ad54372.m4a",
     "rifleReload-3-20027167.m4a"
    ],
    "gain": 1
   },
   "weaponSwap": {
    "files": [
     "weaponSwap-3-fbe81018.m4a"
    ],
    "gain": 1
   },
   "footstep-litter": {
    "files": [
     "footstep-litter-2-19b0df36.m4a",
     "footstep-litter-1-b1476674.m4a"
    ],
    "gain": 1
   },
   "footstep-planks": {
    "files": [
     "footstep-planks-1-cec98032.m4a",
     "footstep-planks-3-77f11491.m4a"
    ],
    "gain": 1
   },
   "footstep-sand": {
    "files": [
     "footstep-sand-2-4b40473a.m4a",
     "footstep-sand-1-09a40a2f.m4a"
    ],
    "gain": 1
   },
   "land": {
    "files": [
     "land-2-773487f2.m4a",
     "land-3-eebff605.m4a"
    ],
    "gain": 1
   },
   "land-hard": {
    "files": [
     "land-hard-3-5aed2a6b.m4a",
     "land-hard-1-2ce640be.m4a"
    ],
    "gain": 1
   },
   "splash": {
    "files": [
     "splash-3-9509efbe.m4a",
     "splash-2-03ab63ae.m4a"
    ],
    "gain": 1
   },
   "wadeStep": {
    "files": [
     "wadeStep-1-83e1423c.m4a",
     "wadeStep-2-402e850a.m4a"
    ],
    "gain": 1
   },
   "swimStroke": {
    "files": [
     "swimStroke-2-9e35721b.m4a"
    ],
    "gain": 1
   },
   "waterExit": {
    "files": [
     "waterExit-1-d85f0e47.m4a"
    ],
    "gain": 1
   },
   "dive": {
    "files": [
     "dive-1-4b978224.m4a",
     "dive-3-e74abc72.m4a"
    ],
    "gain": 1
   },
   "surface": {
    "files": [
     "surface-3-85550528.m4a",
     "surface-2-e5ac4e8a.m4a"
    ],
    "gain": 1
   },
   "hitMarker": {
    "files": [
     "hitMarker-1-46ef1236.m4a"
    ],
    "gain": 1
   },
   "kill": {
    "files": [
     "kill-3-5f7ea225.m4a",
     "kill-2-5e4acc1b.m4a"
    ],
    "gain": 1
   },
   "gull": {
    "files": [
     "gull-1-5fa9130b.m4a"
    ],
    "gain": 1
   },
   "deer_call": {
    "files": [
     "deer_call-3-1d601bb4.m4a",
     "deer_call-1-7cd35867.m4a"
    ],
    "gain": 1
   },
   "boar_grunt": {
    "files": [
     "boar_grunt-3-4e4a9bec.m4a"
    ],
    "gain": 1
   },
   "hoofsteps": {
    "files": [
     "hoofsteps-3-f1c11f8f.m4a",
     "hoofsteps-1-9580d36a.m4a"
    ],
    "gain": 1
   },
   "boar_squeal": {
    "files": [
     "boar_squeal-1-6415e380.m4a"
    ],
    "gain": 1
   },
   "elk_bugle": {
    "files": [
     "elk_bugle-2-7048925b.m4a",
     "elk_bugle-1-375e7428.m4a"
    ],
    "gain": 1
   },
   "bear_growl": {
    "files": [
     "bear_growl-3-97b2d496.m4a",
     "bear_growl-2-7996ef48.m4a"
    ],
    "gain": 1
   },
   "bear_roar": {
    "files": [
     "bear_roar-3-6e416479.m4a",
     "bear_roar-1-cdda7f3d.m4a"
    ],
    "gain": 1
   },
   "bear_hurt": {
    "files": [
     "bear_hurt-1-43b45d1e.m4a",
     "bear_hurt-3-3aea6172.m4a"
    ],
    "gain": 1
   },
   "crab_click": {
    "files": [
     "crab_click-2-aefbc41d.m4a",
     "crab_click-3-f47e95a3.m4a"
    ],
    "gain": 1
   },
   "crab_snap": {
    "files": [
     "crab_snap-2-bff601ad.m4a",
     "crab_snap-3-69ea11c0.m4a"
    ],
    "gain": 1
   },
   "monkey_chatter": {
    "files": [
     "monkey_chatter-3-1c7d7e2d.m4a"
    ],
    "gain": 1
   },
   "monkey_shriek": {
    "files": [
     "monkey_shriek-2-54acd647.m4a",
     "monkey_shriek-1-1a358b4e.m4a"
    ],
    "gain": 1
   },
   "sailor_groan": {
    "files": [
     "sailor_groan-2-43e2a981.m4a"
    ],
    "gain": 1
   },
   "sailor_slash": {
    "files": [
     "sailor_slash-3-5a10eada.m4a",
     "sailor_slash-1-611ba654.m4a"
    ],
    "gain": 1
   },
   "coconut_hit": {
    "files": [
     "coconut_hit-3-9c8e8fd7.m4a",
     "coconut_hit-2-83ed831d.m4a"
    ],
    "gain": 1
   },
   "coconut_land": {
    "files": [
     "coconut_land-1-42389b0a.m4a"
    ],
    "gain": 1
   }
  }
 }
};
