// Generated by scripts/gen-shards.mjs — do not edit or commit.
export type BuiltinShardSlug = "_template" | "blender-template" | "driftwood-isle" | "driftwood-isle-legacy" | "far-reach" | "far-reach-legacy" | "ink-cel-valley" | "nalati-grasslands" | "nalati-grasslands-legacy" | "nine-dragon-stack" | "nine-dragon-stack-legacy" | "pastel-plain" | "pine-hollow" | "pine-hollow-legacy" | "sunscar-dunes" | "sunscar-dunes-legacy";
/** Built-ins are validated during generation; other names cross the branded parser. */
export type ShardSlug = BuiltinShardSlug | import('./slug').ValidatedShardSlug;
