// Generated by scripts/gen-shards.mjs — do not edit or commit.
export type BuiltinShardSlug = "_template" | "blender-template" | "driftwood-isle" | "far-reach" | "nalati-grasslands" | "nine-dragon-stack" | "pine-hollow" | "sunscar-dunes";
/** Built-ins are validated during generation; other names cross the branded parser. */
export type ShardSlug = BuiltinShardSlug | import('./slug').ValidatedShardSlug;
