// The production version file is generated by vite.config.ts from the Git SHA.
// Scheduled deploys skip work when production already serves this exact commit.
import { appendFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const versionUrl = 'https://wildshard-singleplayer.vercel.app/version.json';
// DEPLOY_SHA (the deploy pin, GAME-NORMALIZATION F3.1) wins: a workflow cannot override GITHUB_SHA.
const set = (v) => (v === undefined || v === '' ? undefined : v); // an unset workflow output arrives as ''
const fullSha = (set(process.env.DEPLOY_SHA) ?? set(process.env.GITHUB_SHA) ?? execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim());
const sha = fullSha.slice(0, 7);

/** A build id is `<short sha>-<deployment>`; the short sha's length varies (git's abbrev grows with the repo: 7, then 8
 *  chars), so match on a shared prefix of at least 7 hex, not an exact `<7 chars>-` (2026-10-02: verify failed on a
 *  live c2453984-… against c245398). */
export function matchesCommit(build, commit = fullSha) {
  if (typeof build !== 'string') return false;
  const short = build.split('-')[0] ?? '';
  return /^[0-9a-f]{7,40}$/.test(short) && /^[0-9a-f]{7,40}$/.test(commit) && (commit.startsWith(short) || short.startsWith(commit));
}

async function liveBuild() {
  const url = `${versionUrl}?deployment-check=${Date.now()}`;
  const response = await fetch(url, { headers: { 'Cache-Control': 'no-store' }, signal: AbortSignal.timeout(12_000) });
  if (!response.ok) throw new Error(`version.json returned HTTP ${response.status}`);
  const value = await response.json();
  if (typeof value?.build !== 'string') throw new Error('version.json has no build ID');
  return value.build;
}

async function main() {
  const mode = process.argv[2];
  if (mode !== 'check' && mode !== 'verify') throw new Error('usage: node scripts/deploy-version.mjs check|verify');
  const force = process.env.DEPLOY_FORCE === 'true';
  const attempts = mode === 'verify' ? 18 : 1;
  for (let attempt = 1; attempt <= attempts; attempt++) {
    try {
      const build = await liveBuild();
      const match = matchesCommit(build);
      console.log(`Production ${build}; target ${sha}; match ${match}`);
      if (mode === 'check') {
        const skip = match && !force;
        if (process.env.GITHUB_OUTPUT) appendFileSync(process.env.GITHUB_OUTPUT, `skip=${skip}\n`);
        console.log(skip ? 'Already deployed; skipping.' : 'Deploy required.');
        return;
      }
      if (match) return;
    } catch (error) {
      console.log(`Production version check ${attempt}/${attempts}: ${error.message}`);
      if (mode === 'check') {
        if (process.env.GITHUB_OUTPUT) appendFileSync(process.env.GITHUB_OUTPUT, 'skip=false\n');
        console.log('Version unavailable; deploying to recover.');
        return;
      }
    }
    if (attempt < attempts) await new Promise((resolve) => { setTimeout(resolve, 10_000); });
  }
  throw new Error(`Production did not serve commit ${sha} after deployment`);
}

if (process.argv[1]?.endsWith('/deploy-version.mjs')) await main();
