// The production version file is generated by vite.config.ts from the Git SHA.
// Scheduled deploys skip work when production already serves this exact commit.
import { appendFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const versionUrl = 'https://wildshard-singleplayer.vercel.app/version.json';
const sha = (process.env.GITHUB_SHA ?? execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim()).slice(0, 7);

export function matchesCommit(build, commit = sha) {
  return typeof build === 'string' && build.startsWith(`${commit}-`);
}

async function liveBuild() {
  const url = `${versionUrl}?deployment-check=${Date.now()}`;
  const response = await fetch(url, { headers: { 'Cache-Control': 'no-store' }, signal: AbortSignal.timeout(12_000) });
  if (!response.ok) throw new Error(`version.json returned HTTP ${response.status}`);
  const value = await response.json();
  if (typeof value?.build !== 'string') throw new Error('version.json has no build ID');
  return value.build;
}

async function main() {
  const mode = process.argv[2];
  if (mode !== 'check' && mode !== 'verify') throw new Error('usage: node scripts/deploy-version.mjs check|verify');
  const force = process.env.DEPLOY_FORCE === 'true';
  const attempts = mode === 'verify' ? 18 : 1;
  for (let attempt = 1; attempt <= attempts; attempt++) {
    try {
      const build = await liveBuild();
      const match = matchesCommit(build);
      console.log(`Production ${build}; target ${sha}; match ${match}`);
      if (mode === 'check') {
        const skip = match && !force;
        if (process.env.GITHUB_OUTPUT) appendFileSync(process.env.GITHUB_OUTPUT, `skip=${skip}\n`);
        console.log(skip ? 'Already deployed; skipping.' : 'Deploy required.');
        return;
      }
      if (match) return;
    } catch (error) {
      console.log(`Production version check ${attempt}/${attempts}: ${error.message}`);
      if (mode === 'check') {
        if (process.env.GITHUB_OUTPUT) appendFileSync(process.env.GITHUB_OUTPUT, 'skip=false\n');
        console.log('Version unavailable; deploying to recover.');
        return;
      }
    }
    if (attempt < attempts) await new Promise((resolve) => { setTimeout(resolve, 10_000); });
  }
  throw new Error(`Production did not serve commit ${sha} after deployment`);
}

if (process.argv[1]?.endsWith('/deploy-version.mjs')) await main();
