// E357 F9: folder discovery is the sole authored shard list.
import { existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, resolve, relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import ts from '@typescript/typescript6';
import { genShardWords } from './gen-shard-words.mjs';

/** Static runtime imports only: lazy plugin/look thunks and erased types stay out of the startup closure. */
export function manifestClosure(root) {
  const configPath = ts.findConfigFile(root, (file) => ts.sys.fileExists(file));
  const config = configPath ? ts.readConfigFile(configPath, (file) => ts.sys.readFile(file)).config : {};
  const { options } = ts.parseJsonConfigFileContent(config, ts.sys, root);
  const result = {};
  for (const slug of shardFolders(root)) {
    const seen = new Set();
    const visit = (file) => {
      const id = relative(root, file).replaceAll('\\', '/');
      if (seen.has(id)) return;
      seen.add(id);
      if (!/\.[cm]?[jt]sx?$/.test(file)) return;
      const source = ts.createSourceFile(file, readFileSync(file, 'utf8'), ts.ScriptTarget.Latest, true);
      for (const node of source.statements) {
        if (!ts.isImportDeclaration(node) && !ts.isExportDeclaration(node)) continue;
        if (!node.moduleSpecifier || !ts.isStringLiteral(node.moduleSpecifier)) continue;
        if (ts.isImportDeclaration(node)) {
          if (node.importClause?.phaseModifier === ts.SyntaxKind.TypeKeyword) continue;
          const bindings = node.importClause?.namedBindings;
          if (!node.importClause?.name && bindings && ts.isNamedImports(bindings) && bindings.elements.length > 0 && bindings.elements.every((e) => e.isTypeOnly)) continue;
        } else if (node.isTypeOnly || (node.exportClause && ts.isNamedExports(node.exportClause) && node.exportClause.elements.length > 0 && node.exportClause.elements.every((e) => e.isTypeOnly))) continue;
        const specifier = node.moduleSpecifier.text;
        const target = ts.resolveModuleName(specifier, file, options, ts.sys).resolvedModule?.resolvedFileName;
        if (target && !target.includes('/node_modules/') && !target.endsWith('.d.ts')) visit(target);
        // TypeScript intentionally does not resolve raster imports; include their bundler module ids too.
        else if (specifier.startsWith('.') && existsSync(resolve(dirname(file), specifier))) visit(resolve(dirname(file), specifier));
      }
    };
    visit(resolve(root, `src/shards/${slug}/manifest.ts`));
    result[slug] = [...seen].sort((a, b) => a.localeCompare(b));
  }
  return result;
}

export function shardFolders(root) {
  return readdirSync(resolve(root, 'src/shards'), { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(resolve(root, 'src/shards', entry.name, 'manifest.ts')))
    .map((entry) => entry.name).sort();
}

/**
 * The shard list (E362 AG4): every manifest, imported by the composition root (src/shards.generated.ts, installed by
 * src/shardList.ts) so the game layer imports no shard, and its TypeScript project builds without them.
 */
export function shardSource(root) {
  const slugs = shardFolders(root);
  if (slugs.length === 0) throw new Error('gen-shards: no shard manifests');
  const catalogue = resolve(root, 'src/game/grid/singleplayer.json');
  const placements = existsSync(catalogue) ? JSON.parse(readFileSync(catalogue, 'utf8')).placements : null;
  if (placements !== null) {
    const seen = new Set();
    for (const p of placements) {
      if (!slugs.includes(p.slug) || seen.has(p.slug) || !Array.isArray(p.cell) || p.cell.length !== 2 || !p.cell.every(Number.isSafeInteger) || !Array.isArray(p.size) || p.size.length !== 3 || !p.size.every((n) => n === 500) || typeof p.instance !== 'string') throw new Error('gen-shards: invalid grid placement');
      seen.add(p.slug);
    }
    if (seen.size !== slugs.length) throw new Error('gen-shards: missing grid placement');
  }
  const placed = placements === null ? slugs.map((_, i) => `m${i}`) : slugs.map((slug, i) => {
    const p = placements.find((entry) => entry.slug === slug);
    return `{ ...m${i}, placement: { grid: ${JSON.stringify(p.cell)}, size: ${JSON.stringify(p.size)}, instance: ${JSON.stringify(p.instance)} } }`;
  });
  const metadata = placements === null ? '' : ' & { placement: { grid: [number, number]; size: [number, number, number]; instance: string } }';
  return `// Generated by scripts/gen-shards.mjs — do not edit or commit.
import type { ShardManifest } from './game/shard/manifest';
${slugs.map((slug, i) => `import m${i} from './shards/${slug}/manifest';`).join('\n')}
const placed: (ShardManifest${metadata})[] = [${placed.join(', ')}];
export const SHARDS = placed.sort((a, b) => a.order - b.order);
`;
}
/** the slugs as a type, for the game (no import: the game knows that shards exist, not which) */
export function slugSource(root) {
  const slugs = shardFolders(root);
  return `// Generated by scripts/gen-shards.mjs — do not edit or commit.
export type ShardSlug = ${slugs.map((slug) => JSON.stringify(slug)).join(' | ')};
`;
}

const LOAD = /\bload:\s*\(\)\s*=>\s*import\(\s*['"]\.\/plugin(?:\.ts)?['"]\s*\)/u;
const BUDGET_FILE = 'lint/manifest-closure-budget.json';
/**
 * E362 AG10, the manifest contract: `load` is `() => import('./plugin')` (the plugin never rides in cold boot); the
 * manifest's static closure stays inside its file budget (`lint/manifest-closure-budget.json`, `default` for a new
 * shard; it may only fall); every `ShardManifest` field is read by the engine, the game or the tooling (`fields`).
 * Slug = folder is check-shards' (AG9).
 */
export function manifestContract(root, closure, fields = false) {
  const failures = [];
  const budgetPath = resolve(root, BUDGET_FILE);
  const budgets = existsSync(budgetPath) ? JSON.parse(readFileSync(budgetPath, 'utf8')).budgets : {};
  for (const slug of shardFolders(root)) {
    const source = readFileSync(resolve(root, `src/shards/${slug}/manifest.ts`), 'utf8');
    if (!LOAD.test(source)) failures.push(`src/shards/${slug}/manifest.ts: load must be \`() => import('./plugin')\` (a lazy plugin, never a static import)`);
    if (/^import\s[^;]*['"]\.\/plugin(?:\.ts)?['"]/mu.test(source)) failures.push(`src/shards/${slug}/manifest.ts imports ./plugin statically: it would ride in cold boot`);
    const budget = budgets[slug] ?? budgets.default, size = closure[slug]?.length ?? 0;
    if (typeof budget === 'number' && size > budget) failures.push(`src/shards/${slug}/manifest.ts: its static closure is ${size} files, over its budget ${budget} (${BUDGET_FILE}); move the new imports behind load / a lazy thunk`);
  }
  if (fields) {
    const file = resolve(root, 'src/game/shard/manifest.ts');
    const decl = ts.createSourceFile(file, readFileSync(file, 'utf8'), ts.ScriptTarget.Latest, true);
    let names = [];
    decl.forEachChild((n) => { if (ts.isInterfaceDeclaration(n) && n.name.text === 'ShardManifest') names = n.members.filter(ts.isPropertySignature).map((m) => m.name.getText(decl)); });
    const texts = [];
    const scan = (dir) => {
      if (!existsSync(resolve(root, dir))) return;
      for (const entry of readdirSync(resolve(root, dir), { withFileTypes: true })) {
        const path = `${dir}/${entry.name}`;
        if (entry.isDirectory()) scan(path);
        else if (/\.[cm]?[jt]s$/u.test(entry.name) && !entry.name.endsWith('.generated.ts')) texts.push(readFileSync(resolve(root, path), 'utf8'));
      }
    };
    for (const dir of ['src/engine', 'src/game', 'lint', 'scripts']) scan(dir);
    const all = texts.join('\n');
    for (const name of names) if (!new RegExp(`\\.${name}\\b|['"]${name}['"]`, 'u').test(all)) failures.push(`ShardManifest.${name}: nothing in the engine, the game or the tooling reads it; drop the field`);
  }
  return failures;
}

export function genShards(root = resolve(import.meta.dirname, '..'), check = false, initializeMissing = false, shard = '') {
  genShardWords(root, check, shard);
  const closure = manifestClosure(root);
  const outputs = { 'src/shards.generated.ts': shardSource(root), 'src/game/shard/slugs.generated.ts': slugSource(root), 'src/game/shard/manifest-closure.generated.json': `${JSON.stringify(closure, null, 2)}\n` };
  for (const [name, source] of Object.entries(outputs)) {
    const out = resolve(root, name);
    const exists = existsSync(out), same = exists && readFileSync(out, 'utf8') === source;
    // A staged-tree export lacks these untracked tables. Only that caller initializes missing outputs;
    // committed vocabulary above and any existing runtime table still have strict --check semantics.
    const initialize = initializeMissing && !exists;
    if (check && !same && !initialize) throw new Error(`gen-shards: stale ${name} (run pnpm gen)`);
    if ((!check || initialize) && !same) { mkdirSync(dirname(out), { recursive: true }); writeFileSync(out, source); }
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  try {
    const shard = process.argv.find((arg) => arg.startsWith('--shard='))?.slice(8);
    genShards(undefined, process.argv.includes('--check'), false, shard);
    // Vite runs discovery before boot byte tables exist. Budget generation belongs to pnpm gen after those tables.
    if (process.argv.includes('--check')) {
      const root = resolve(import.meta.dirname, '..'), failures = manifestContract(root, manifestClosure(root), true);
      if (failures.length > 0) throw new Error(`gen-shards: the manifest contract (AG10):\n  ${failures.join('\n  ')}`);
      const { genBudgetDerivations } = await import('./gen-budget-derivations.mjs');
      await genBudgetDerivations(undefined, true, shard);
    }
  }
  catch (error) { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; }
}
