// E357 F9: folder discovery is the sole authored shard list.
import { existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, resolve, relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import ts from '@typescript/typescript6';
import { genShardWords } from './gen-shard-words.mjs';

/** Static runtime imports only: lazy plugin/look thunks and erased types stay out of the startup closure. */
export function manifestClosure(root) {
  const configPath = ts.findConfigFile(root, (file) => ts.sys.fileExists(file));
  const config = configPath ? ts.readConfigFile(configPath, (file) => ts.sys.readFile(file)).config : {};
  const { options } = ts.parseJsonConfigFileContent(config, ts.sys, root);
  const result = {};
  for (const slug of shardFolders(root)) {
    const seen = new Set();
    const visit = (file) => {
      const id = relative(root, file).replaceAll('\\', '/');
      if (seen.has(id)) return;
      seen.add(id);
      if (!/\.[cm]?[jt]sx?$/.test(file)) return;
      const source = ts.createSourceFile(file, readFileSync(file, 'utf8'), ts.ScriptTarget.Latest, true);
      for (const node of source.statements) {
        if (!ts.isImportDeclaration(node) && !ts.isExportDeclaration(node)) continue;
        if (!node.moduleSpecifier || !ts.isStringLiteral(node.moduleSpecifier)) continue;
        if (ts.isImportDeclaration(node)) {
          if (node.importClause?.phaseModifier === ts.SyntaxKind.TypeKeyword) continue;
          const bindings = node.importClause?.namedBindings;
          if (!node.importClause?.name && bindings && ts.isNamedImports(bindings) && bindings.elements.length > 0 && bindings.elements.every((e) => e.isTypeOnly)) continue;
        } else if (node.isTypeOnly || (node.exportClause && ts.isNamedExports(node.exportClause) && node.exportClause.elements.length > 0 && node.exportClause.elements.every((e) => e.isTypeOnly))) continue;
        const specifier = node.moduleSpecifier.text;
        const target = ts.resolveModuleName(specifier, file, options, ts.sys).resolvedModule?.resolvedFileName;
        if (target && !target.includes('/node_modules/') && !target.endsWith('.d.ts')) visit(target);
        // TypeScript intentionally does not resolve raster imports; include their bundler module ids too.
        else if (specifier.startsWith('.') && existsSync(resolve(dirname(file), specifier))) visit(resolve(dirname(file), specifier));
      }
    };
    visit(resolve(root, `src/shards/${slug}/manifest.ts`));
    result[slug] = [...seen].sort((a, b) => a.localeCompare(b));
  }
  return result;
}

export function shardFolders(root) {
  return readdirSync(resolve(root, 'src/shards'), { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(resolve(root, 'src/shards', entry.name, 'manifest.ts')))
    .map((entry) => entry.name).sort();
}

export function shardSource(root) {
  const slugs = shardFolders(root);
  if (slugs.length === 0) throw new Error('gen-shards: no shard manifests');
  return `// Generated by scripts/gen-shards.mjs — do not edit or commit.
import type { ShardManifest } from './manifest';
${slugs.map((slug, i) => `import m${i} from '#shards/${slug}/manifest';`).join('\n')}
export const SHARDS: readonly ShardManifest[] = [${slugs.map((_, i) => `m${i}`).join(', ')}].sort((a, b) => a.order - b.order);
export type ShardSlug = ${slugs.map((slug) => JSON.stringify(slug)).join(' | ')};
`;
}

export function genShards(root = resolve(import.meta.dirname, '..'), check = false, initializeMissing = false) {
  genShardWords(root, check);
  const outputs = { 'shards.generated.ts': shardSource(root), 'manifest-closure.generated.json': `${JSON.stringify(manifestClosure(root), null, 2)}\n` };
  for (const [name, source] of Object.entries(outputs)) {
    const out = resolve(root, 'src/game/shard', name);
    const exists = existsSync(out), same = exists && readFileSync(out, 'utf8') === source;
    // A staged-tree export lacks these untracked tables. Only that caller initializes missing outputs;
    // committed vocabulary above and any existing runtime table still have strict --check semantics.
    const initialize = initializeMissing && !exists;
    if (check && !same && !initialize) throw new Error(`gen-shards: stale src/game/shard/${name} (run pnpm gen)`);
    if ((!check || initialize) && !same) { mkdirSync(dirname(out), { recursive: true }); writeFileSync(out, source); }
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  try { genShards(undefined, process.argv.includes('--check')); }
  catch (error) { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; }
}
