// SF6b: generated measurements are separate from human-reviewed policy and exact increase receipts.
// SF74 W13 (G281): the API surface, docs/api/ and the export index left git (build outputs of `pnpm gen`).
export const GENERATED_FILES = ['lint/layer-edges.json', 'lint/ratchet.json', 'scripts/README.md'];
// The export index's list markers (docs/api/EXPORTS.md strips them; ENGINE.md no longer carries the list).
export const APPENDIX_START = '<!-- exports:start (generated by test/engine-docs.test.ts; do not edit by hand) -->';
export const APPENDIX_END = '<!-- exports:end -->';
const object = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);
const canonical = (value) => {
  if (Array.isArray(value)) return value.map(canonical);
  if (!object(value)) return value;
  return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonical(item)]));
};
const json = (value) => JSON.stringify(canonical(value));
const count = (value) => Number.isSafeInteger(value) && value >= 0;

/** Only violation counts are generated; every other ratchet field remains a policy input. */
export function debtCounts(ratchet) {
  if (!object(ratchet)) throw new Error('Ratchet must be an object');
  const result = {};
  for (const [rule, files] of Object.entries(ratchet)) {
    if (!rule.startsWith('wildshard/')) continue;
    if (!object(files) || Object.values(files).some((n) => !count(n))) throw new Error(`Invalid debt counts: ${rule}`);
    result[rule] = files;
  }
  return result;
}

/** Preserve allow lists, budgets and caps byte-for-value when replacing measured debt. */
export function replaceDebt(ratchet, current) {
  debtCounts(current);
  return { ...Object.fromEntries(Object.entries(ratchet).filter(([key]) => !key.startsWith('wildshard/'))), ...debtCounts(current) };
}

/** Compare exact aggregate graph and per-file debt increases, never exchanging slack between entries. */
export function generatedIncreases(previous, current) {
  const result = [];
  for (const [key, after] of Object.entries(current.edges)) {
    const before = previous.edges[key] ?? 0;
    if (!count(before) || !count(after)) throw new Error(`Invalid graph count: ${key}`);
    if (after > before) result.push({ kind: 'graph', key, before, after });
  }
  const oldDebt = debtCounts(previous.ratchet), newDebt = debtCounts(current.ratchet);
  for (const [key, files] of Object.entries(newDebt)) for (const [file, after] of Object.entries(files)) {
    const before = oldDebt[key]?.[file] ?? 0;
    if (after > before) result.push({ kind: 'debt', key, file, before, after });
  }
  return result.sort((a, b) => a.kind.localeCompare(b.kind) || a.key.localeCompare(b.key) || (a.file ?? '').localeCompare(b.file ?? ''));
}

/** A pusher must name the coordinator and each exact increase in the regeneration commit. */
export function increaseTrailers(increases, approver) {
  if (increases.length === 0) return '';
  if (approver !== 'wildshard-new') throw new Error('Generated increases require the coordinator approver wildshard-new');
  return ['Generated-Approver: wildshard-new', ...increases.map((row) => `Generated-Increase: ${json(row)}`)].join('\n');
}

/** No unlisted, overbroad, duplicate or unused approval can cover a measured increase. */
export function verifyIncreaseTrailers(increases, message) {
  const listed = message.split('\n').filter((line) => line.startsWith('Generated-Increase: ')).map((line) => {
    try { return json(JSON.parse(line.slice('Generated-Increase: '.length))); }
    catch { throw new Error('Invalid Generated-Increase JSON'); }
  }).sort((a, b) => a.localeCompare(b));
  const wanted = increases.map(json).sort((a, b) => a.localeCompare(b));
  const approvers = message.split('\n').filter((line) => line.startsWith('Generated-Approver: '));
  if (wanted.length > 0 && (approvers.length !== 1 || approvers[0] !== 'Generated-Approver: wildshard-new')) throw new Error('Generated increase has no coordinator approver');
  if (json(listed) !== json(wanted)) throw new Error(`Unlisted or stale generated increases: expected ${json(wanted)}, got ${json(listed)}`);
}

/** Select exactly what builders must leave to the serialized pusher. */
export function generatedPart(file, text) {
  if (file === 'lint/ratchet.json') return json(debtCounts(JSON.parse(text)));
  return text;
}

/** Source commits may change ENGINE prose and ratchet policy, but cannot carry generated edits. */
export function builderGeneratedChanges(paths, before, staged) {
  return paths.filter((file) => GENERATED_FILES.includes(file) && generatedPart(file, before(file)) !== generatedPart(file, staged(file)));
}

/** The same appendix renderer serves the generator and its documentation check. */
export function engineAppendix(surface) {
  let text = `${APPENDIX_START}\n\n`;
  for (const [layer, rows] of Object.entries(surface.indexes)) {
    const groups = new Map();
    for (const row of rows) {
      const names = groups.get(row.from) ?? [];
      if (!names.includes(row.name)) names.push(row.name);
      groups.set(row.from, names);
    }
    const n = new Set([...groups.values()].flat()).size;
    text += `### \`@wildshard/${layer}\` (\`src/${layer}/package.json\`)\n\n${n} exports, grouped by the module to import them from.\n\n`;
    for (const [from, names] of groups) text += `- \`${from}\`: ${names.map((name) => `\`${name}\``).join(', ')}\n`;
    text += '\n';
  }
  return `${text}${APPENDIX_END}`;
}
