// The encoder and the F9 migration share this partition; generation never needs basisu.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { defaultAssetGlobs, globToRegExp } from './check-lock.mjs';

export function splitKtx2(map, shards) {
  const tables = new Map([['engine', { phone: {}, desktop: {} }], ...shards.map((m) => [m.slug, { phone: {}, desktop: {} }])]);
  const owners = shards.map((m) => ({ slug: m.slug, patterns: [...defaultAssetGlobs(m.slug), ...(m.assetGlobs ?? [])].map(globToRegExp) }));
  for (const tier of ['phone', 'desktop']) for (const [url, target] of Object.entries(map[tier])) {
    // Procedural texture keys name CPU-generated pixels, not downloadable source images.
    const path = `public${url.replace(/^procedural:/u, '').split('#')[0]}`;
    const matches = owners.filter((owner) => owner.patterns.some((pattern) => pattern.test(path)));
    if (matches.length > 1) throw new Error(`KTX2 table has ambiguous ownership: ${url}`);
    tables.get(matches[0]?.slug ?? 'engine')[tier][url] = target;
  }
  return tables;
}

export function writeKtx2Tables(root, map, shards) {
  for (const [slug, table] of splitKtx2(map, shards)) {
    if (slug !== 'engine' && Object.keys(table.phone).length + Object.keys(table.desktop).length === 0) continue;
    const out = resolve(root, slug === 'engine' ? 'src/engine/boot/ktx2.generated.ts' : `src/shards/${slug}/ktx2.generated.ts`);
    const ordered = Object.fromEntries(['phone', 'desktop'].map((tier) => [tier, Object.fromEntries(Object.entries(table[tier]).sort(([a], [b]) => a.localeCompare(b)))]));
    const source = '// Generated by scripts/bake-ktx2.mjs — commit this table with its KTX2 assets.\n'
      + `export const GPU_FILES: { readonly phone: Readonly<Record<string, string>>; readonly desktop: Readonly<Record<string, string>> } = ${JSON.stringify(ordered, null, 2)};\n`;
    if (!existsSync(out) || readFileSync(out, 'utf8') !== source) writeFileSync(out, source);
  }
}
