import { manifestClosure } from '../scripts/gen-shards.mjs';
import { genStarterBag } from '../scripts/gen-starter-bag.mjs';
import { execFileSync } from 'node:child_process';
import { readdirSync, statSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { contentNamed, hashTree } from './assetHashes';
import { copyRapierWasm } from './rapier';
import { copyBasisTranscoder } from './basis';

// /asset-index.json: every file under public/assets with its byte size, so the loading
// screen can show real "x / y MB" totals for the files it has requested so far.
export function assetIndex(): string {
  const out: Record<string, number> = {};
  const walk = (dir: string, pub: string) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name); const st = statSync(p);
      if (st.isDirectory()) { if (`${pub}/${name}` !== '/assets/packs') walk(p, `${pub}/${name}`); } // packs: generated from these very files, below
      else out[`${pub}/${name}`] = st.size;
    }
  };
  try { walk('public/assets', '/assets'); } catch { /* no assets dir */ }
  return JSON.stringify(out);
}

// src/game/boot/bytes.generated.ts: the same table as a committed TS module, so the boot plan's declared
// denominators need no fetch and `pnpm tsc` fails when a file a chunk declares disappears.
function writeBytesModule() {
  const rows = JSON.parse(assetIndex()) as Record<string, number>;
  const body = Object.keys(rows).filter((k) => !k.endsWith('.DS_Store')).sort().map((k) => `  ${JSON.stringify(k)}: ${rows[k]},`).join('\n');
  const src = `// generated by vite.config.ts from public/assets — do not edit. Regenerated by every vite build / dev.\nexport const PUBLIC_BYTES = {\n${body}\n} as const;\n`;
  const out = 'src/game/boot/bytes.generated.ts';
  if (!existsSync(out) || readFileSync(out, 'utf8') !== src) writeFileSync(out, src);
}

// src/game/boot/versions.generated.ts: a content hash per file under public/assets (E160; NALATI-MERGE F4 started it for
// public/assets/nalati/). Those files are unhashed and get edited or re-baked in place, so the network sees them as
// `<path>?v=<hash8>` (src/engine/boot/bytes.ts `versionedUrl`): an edit is a new URL to the HTTP cache and the service worker
// (cache-first on `?v=`), an unchanged file keeps its URL — and its cached copy — across every deploy. Files whose name is
// already content-addressed (the packs, the `<name>-<hash8>.m4a` audio, vite/assetHashes.ts `contentNamed`) need no `?v=`.
function writeVersionsModule() {
  const all = hashTree('assets');
  const rows = Object.keys(all).filter((p) => !contentNamed(p)).map((p) => `  ${JSON.stringify(p)}: '${all[p]}',`);
  const src = `// generated by vite.config.ts from public/assets — do not edit. Regenerated by every vite build / dev.\nexport const ASSET_VERSIONS: Readonly<Record<string, string>> = {\n${rows.join('\n')}\n};\n`;
  const out = 'src/game/boot/versions.generated.ts';
  if (!existsSync(out) || readFileSync(out, 'utf8') !== src) writeFileSync(out, src);
}

// /asset-manifest.json (E160 / E161): every file under public/assets — the packs included — with its content hash: what
// this build names. The service worker reads it on activate to keep exactly those entries (a `?v=` key whose hash still
// matches, a content-named file still shipped) and to drop everything else: old pack blobs, old versions, files removed.

// src/game/boot/audio.generated.ts: every music style's music.json and every sound-effect set's sfx.json (public/assets/music/<style>/,
// public/assets/sfx/<set>/), compiled into the bundle minus their provenance notes (project/archive/2026-09-23-preload-offline.md). The boot
// declares and downloads every file they list at the loading bar and decodes the selected style + set there, so nothing
// fetches a manifest at runtime and the hashed bundle always carries the loop points of the files it ships with.
function writeAudioModule() {
  const read = (sub: string, name: string): Record<string, unknown> => {
    const out: Record<string, unknown> = {};
    const dir = join('public/assets', sub);
    if (!existsSync(dir)) return out;
    for (const d of readdirSync(dir).sort()) {
      const p = join(dir, d, name);
      if (!existsSync(p)) continue;
      try {
        const j = JSON.parse(readFileSync(p, 'utf8')) as Record<string, unknown>;
        out[d] = Object.fromEntries(Object.entries(j).filter(([k]) => k !== 'provenance' && k !== 'synth_keeps'));
      } catch (e) { console.warn(`[audio] ${p} is not JSON — that ${sub} entry ships without samples`, e); }
    }
    return out;
  };
  const src = '// generated by vite.config.ts from public/assets/music/*/music.json and public/assets/sfx/*/sfx.json — do not edit.\n'
    + `export const MUSIC_MANIFESTS: Readonly<Record<string, unknown>> = ${JSON.stringify(read('music', 'music.json'), null, 1)};\n`
    + `export const SFX_MANIFESTS: Readonly<Record<string, unknown>> = ${JSON.stringify(read('sfx', 'sfx.json'), null, 1)};\n`;
  const out = 'src/game/boot/audio.generated.ts';
  if (!existsSync(out) || readFileSync(out, 'utf8') !== src) writeFileSync(out, src);
}

// src/game/shard/art.generated.ts: the byte sizes of the title / explore art the manifests import (shard cards' thumbnails and
// hero stills) by their bundled URL — Vite copies them to /assets/<name>-<hash>.<ext> byte for byte, so the source size is the
// size the boot declares for the loading bar's "art" source (src/engine/boot/extras.ts).
function writeArtModule() {
  const closures = manifestClosure(process.cwd());
  const images = [...new Set(Object.values(closures).flat())].filter((path) => /\.(jpe?g|png|webp)$/.test(path)).sort((a, b) => a.localeCompare(b));
  const imports = images.map((path, i) => `import art${i} from ${JSON.stringify(`../../${path.slice(4)}`)};`).join('\n');
  const sizes = images.map((path, i) => `  [art${i}]: ${statSync(path).size},`).join('\n');
  const module = `// Generated manifest art only; undeclared mockups do not join the boot graph.\n${imports}\nexport const ART_URL_BYTES: Readonly<Record<string, number>> = {\n${sizes}\n};\n`;
  const urlOut = 'src/game/shard/art.generated.ts';
  if (!existsSync(urlOut) || readFileSync(urlOut, 'utf8') !== module) writeFileSync(urlOut, module);
}


export function generateBootTables(): void {
  genStarterBag();
  mkdirSync('src/game/boot', { recursive: true }); // the tables' folder holds only generated (untracked) files
  copyRapierWasm();
  copyBasisTranscoder();
  writeBytesModule();
  writeVersionsModule();
  writeAudioModule();
  writeArtModule();
  execFileSync(process.execPath, ['--import', './scripts/bake-loader.mjs', 'scripts/bake-packs.mjs'], { stdio: 'inherit' });
}
