// Generated by scripts/bake/movers.mjs: the winch and rope bridges' admitted module (behaviour/bridges.as).
export const BRIDGE_MODULE = { hash: '1371d8959aebb567404fc8db59592b0d63f7afeb7060f0b74ea4f12389e6bafd', bytes: 1297 } as const;
