"""Sky Reach panorama -> the shipped strips and look/panoramaData.ts (loop 4, E374).

  python3 prep.py <horizon row in panorama.png> [source image]      # e.g. 564 ../../round-17-mockup-loop/panorama-graded.jpg

Writes public/assets/far-reach/sky/panorama.webp (desktop, native 5530 px) and panorama.phone.webp (4096 px), each
carrying PAD columns of wrap on either side (a lossy codec encodes an image's edges on their own: an unpadded strip
comes back with a step at heading 0, the spawn's forward view), and src/shards/far-reach/look/panoramaData.ts: the
horizon row, the painted sun (heading, elevation), the zenith / nadir colours and the fog LUT (the haze just above the
horizon per heading, so the 3-D fog fades into the painting).
"""
import os, sys
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '../../../..'))
PAD = 16
PPD = 15.36
_png = os.path.join(HERE, 'panorama.png')  # the stitch's output; the committed source is its q92 JPEG
_src = os.path.abspath(sys.argv[2]) if len(sys.argv) > 2 else (_png if os.path.exists(_png) else os.path.join(HERE, 'panorama-5530x1024.jpg'))  # E392: a graded source
src = np.asarray(Image.open(_src).convert('RGB')).astype(np.float64)
H, W, _ = src.shape
hor = float(sys.argv[1])

out_dir = os.path.join(REPO, 'public/assets/far-reach/sky')
os.makedirs(out_dir, exist_ok=True)
for name, width in (('panorama.webp', W), ('panorama.phone.webp', 4096)):
    im = Image.fromarray(src.clip(0, 255).astype(np.uint8))
    if width != W:
        # resize as a loop: pad, resize, crop, so the two ends stay continuous
        k = 64
        loop = np.concatenate([src[:, -k:], src, src[:, :k]], axis=1)
        h = int(round(H * width / W))
        r = Image.fromarray(loop.clip(0, 255).astype(np.uint8)).resize((int(round(loop.shape[1] * width / W)), h), Image.LANCZOS)
        kk = int(round(k * width / W))
        im = r.crop((kk, 0, kk + width, h))
    a = np.asarray(im)
    padded = np.concatenate([a[:, -PAD:], a, a[:, :PAD]], axis=1)
    Image.fromarray(padded).save(os.path.join(out_dir, name), 'WEBP', quality=88, method=6)
    print(name, padded.shape, os.path.getsize(os.path.join(out_dir, name)) // 1024, 'KB')

# the painted sun: the centroid of the brightest pixels
lum = src.mean(axis=2)
lum[int(hor) - 8:] = 0  # the disc only: not its glitter on the cloud sea below the horizon
ys, xs = np.nonzero(lum > np.percentile(lum, 99.97))
# circular mean of x
ang = xs / W * 2 * np.pi
sx = (np.degrees(np.arctan2(np.sin(ang).mean(), np.cos(ang).mean())) + 360) % 360
sy = ys.mean()
sun_heading, sun_elev = sx, (hor - sy) / PPD
print('sun heading', round(sun_heading, 1), 'elevation', round(sun_elev, 2))

srgb = src / 255.0
zen = srgb[:12].reshape(-1, 3).mean(axis=0)
nad = srgb[-12:].reshape(-1, 3).mean(axis=0)
band = srgb[int(hor - 2.5 * PPD):int(hor - 0.5 * PPD)].mean(axis=0)  # (W, 3)
N = 64
lut = np.stack([band[int(i * W / N):int((i + 1) * W / N)].mean(axis=0) for i in range(N)])
# a circular blur over 3 texels each side
lut = np.stack([np.mean([lut[(i + j) % N] for j in range(-3, 4)], axis=0) for i in range(N)])

f = lambda v: ', '.join(f'{x:.4f}' for x in v)
ts = f"""// GENERATED by art/far-reach/round-14-loop-4/pano/prep.py from the loop-4 panorama: don't edit by hand.
/** the painted eye-level horizon, as a fraction of the strip's height from the top */
export const PANO_HORIZON_V = {hor / H:.4f};
/** the strip's vertical scale: degrees of elevation per unit of v ({PPD} px per degree over {H} rows) */
export const PANO_DEG_PER_V = {H / PPD:.3f};
/** columns of wrap on either side of the shipped strips (the shader maps the heading inside them) */
export const PANO_PAD_PX = {PAD};
/** the painted sun: heading (degrees, 0 = -z, 90 = +x) and elevation (degrees) */
export const PANO_SUN = {{ heading: {sun_heading:.2f}, elevation: {sun_elev:.2f} }} as const;
/** sRGB 0..1: the painting's top rows (the dome above them) and bottom rows (the dome below) */
export const PANO_ZENITH_SRGB = [{f(zen)}] as const;
export const PANO_NADIR_SRGB = [{f(nad)}] as const;
/** the fog LUT: per heading ({N} samples from 0), the painted haze just above the horizon, sRGB 0..1 (r, g, b interleaved) */
export const PANO_FOG_SRGB = [{f(lut.reshape(-1))}];
"""
open(os.path.join(REPO, 'src/shards/far-reach/look/panoramaData.ts'), 'w').write(ts)
print('wrote panoramaData.ts')
